"""ARP: hold a chord and it plays on the bar grid. Tense score pulses,
machine sequences and broken transmissions. LFOs run FREE (each arp step is
a new voice, so a per-note LFO would restart every step); performers follow
the song."""

from lunatk import Preset
from bank2._common import accents, echo, gate_seq, grit, seq, space, velocity


def A(name, a="ANALOG", b="BASIC"):
    return Preset(name, "ARP", a, b)


def bed(p, voices=8, vel=0.55):
    return p.voice(voices=voices, glide=0.0, vel=vel, bend=2)


def plate(p, mix=0.12, decay=0.28, amount=0.15):
    return space(p, mix, mode="PLATE", size=0.45, decay=decay, damp=0.55, predelay=0.04, width=0.75, amount=amount)


def presets():
    out = []

    p = A("PULSE WOUND", "BASIC", "BASIC")
    p.osc(0, level=0.7, wt=0.15)
    p.insert(1, "COMB", after=True, amount=0.45, freq=0.75, mix=0.25)
    p.insert(2, "DECIMATE", after=True, amount=0.15, mix=0.35)
    p.env(1, a=0.002, d=0.3, s=0.15, r=0.15)
    p.filter("LP12", hz=2600, res=0.05, keytrack=0.4)
    p.filter2("HP12", hz=200)
    p.arp("UP", rate="1/16", octaves=2, gate=0.55)
    bed(p)
    velocity(p, 0.6, 0.12)
    p.tone("CUTOFF", 0.18)
    p.lfo(1, "SINE", sync="1 BAR", mode="FREE")
    p.set("macro2", 0.4)
    p.motion("LFO1", "CUTOFF", 0.3)
    p.motion("LFO1", "INS1_AMOUNT", 0.35)
    echo(p, time="3/16", mix=0.16, feedback=0.35, amount=0.14, pingpong=True)
    plate(p)
    p.doc("A soft, tense sixteenth pulse with a ringing edge and a slightly broken sample rate", "C3–C5",
          "Film score, thriller, ambient, industrial ballads", "Hold minor chords for a bar or two", "RHYTHM",
          "Quiet tension under dialogue or a vocal; the filter opens over four bars")
    out.append(p)

    p = A("MACHINE LOOM", "ANALOG", "ANALOG")
    p.osc(0, level=0.65, wt=1.0)
    p.osc(1, level=0.3, wt=1.0, fine=6)
    p.insert(1, "FOLD", amount=0.2, mix=0.7)
    p.env(1, a=0.001, d=0.2, s=0.2, r=0.08)
    p.env(2, a=0.001, d=0.12, s=0.0, r=0.08)
    p.filter("LP24", hz=900, res=0.3, keytrack=0.5, env=0.35, drive=0.3)
    p.filter2("HP12", hz=180)
    p.arp("UP", rate="1/16", octaves=2, gate=0.5)
    bed(p)
    velocity(p, 0.6, 0.15)
    p.tone("CUTOFF", 0.18)
    p.performer(1, {0: accents("X--xX--xX-x-X--x", "DECAY"), 1: accents("X-x-X-x-XxXxX-x-", "DECAY")}, rate="1/16")
    p.set("macro2", 0.5)
    p.motion("PERF1", "INS1_AMOUNT", 0.45)
    p.motion("PERF1", "CUTOFF", 0.15)
    echo(p, time="1/8", mix=0.1, feedback=0.25, amount=0.12)
    grit(p, mode="TUBE", drive=0.45, tone=0.5, amount=0.4, base=0.25)
    p.doc("A saw sequence with a folded accent pattern of its own, locked to the bar", "C3–C5",
          "Industrial techno, EBM, darkwave", "Hold chords; accents and arp interlock", "RHYTHM",
          "Pattern B pushes harder for the drop; MOTION 0 plays every step alike")
    out.append(p)

    p = A("NEEDLE RAIN", "GLASS", "GLASS")
    p.osc(0, level=0.6, wt=0.7)
    p.osc(1, level=0.3, wt=0.4, octave=1)
    p.insert(1, "BITCRUSH", after=True, amount=0.5, mix=0.3)
    p.insert(2, "COMB", after=True, amount=0.4, freq=0.75, mix=0.2)
    p.env(1, a=0.001, d=0.15, s=0.0, r=0.1)
    p.filter("LP12", hz=1800, res=0.05, keytrack=0.5)
    p.filter2("HP12", hz=300)
    p.arp("RANDOM", rate="1/32", octaves=2, gate=0.4)
    bed(p)
    velocity(p, 0.6, 0.1)
    p.tone("EQ_HIGH", 0.25)
    p.eq(high=-4, high_hz=8000)
    p.lfo(1, "TRIANGLE", sync="2 BAR", mode="FREE")
    p.set("macro2", 0.4)
    p.motion("LFO1", "INS1_AMOUNT", 0.25)
    p.motion("LFO1", "CUTOFF", 0.12)
    echo(p, time="3/16", mix=0.14, feedback=0.3, amount=0.12, pingpong=True)
    plate(p)
    p.doc("Fast, random glass needles inside your chord, crushed at the edges", "C3–C5",
          "Glitch, IDM, film, ambient", "Hold chords under something slower", "TEXTURE",
          "Reads as texture, not melody; the notes only come from the chord you hold")
    out.append(p)

    p = A("FEVER CLOCK", "PWM", "BASIC")
    p.osc(0, level=0.7, wt=0.4)
    p.insert(1, "RING", after=True, amount=0.4, freq=0.625, mix=0.3)
    p.env(1, a=0.001, d=0.2, s=0.1, r=0.1)
    p.env(2, a=0.001, d=0.12, s=0.0, r=0.1)
    p.filter("LP24", hz=1500, res=0.2, keytrack=0.5, env=0.3)
    p.filter2("HP12", hz=200)
    p.arp("PLAYED", rate="1/16", octaves=1, gate=0.45, swing=0.3)
    bed(p)
    velocity(p, 0.6, 0.15)
    p.tone("CUTOFF", 0.18)
    p.lfo(1, "SQUARE", sync="1/4", mode="FREE")
    p.set("macro2", 0.4)
    p.motion("LFO1", "INS1_AMOUNT", 0.35)
    echo(p, time="1/8", mix=0.1, feedback=0.3, amount=0.12)
    grit(p, mode="HARD", drive=0.4, tone=0.5, amount=0.4, base=0.2)
    p.doc("A swung pulse arp in the order you play, ringing on the off-beats", "C3–C5",
          "Industrial, trip-hop, electro", "Play chords note by note in the order you want", "RHYTHM",
          "30% swing: line your drums up with it")
    out.append(p)

    p = A("RUST SPIRAL", "ANALOG", "SPECTRAL_COMB")
    p.osc(0, level=0.6, wt=0.8)
    p.osc(1, level=0.3, wt=0.4, octave=1)
    p.insert(1, "COMB", after=True, amount=0.6, freq=0.5, mix=0.35)
    p.env(1, a=0.002, d=0.3, s=0.2, r=0.15)
    p.filter("LP24", hz=1600, res=0.2, keytrack=0.5, env=0.25)
    p.filter2("HP12", hz=200)
    p.feedback(amount=0.15, drive=0.5, tone=0.6)
    p.arp("UPDOWN", rate="1/8", octaves=3, gate=0.6)
    bed(p)
    velocity(p, 0.6, 0.12)
    p.tone("CUTOFF", 0.18)
    p.lfo(1, "SINE", sync="2 BAR", mode="FREE")
    p.set("macro2", 0.4)
    p.motion("LFO1", "B_WTPOS", 0.3)
    p.motion("LFO1", "CUTOFF", 0.12)
    echo(p, time="3/16", mix=0.14, feedback=0.3, amount=0.12, pingpong=True)
    plate(p, mix=0.14)
    p.doc("A rusty eighth-note spiral up and down three octaves, ringing as it goes", "C3–C4 (it climbs)",
          "Film, industrial, gothic", "Hold two- or three-note chords low", "FOREGROUND",
          "Three octaves: keep the chord low or it climbs into the cymbals")
    out.append(p)

    p = A("SIGNAL FLARE", "DIGITAL", "ANALOG")
    p.osc(0, level=0.55, wt=0.6)
    p.osc(1, level=0.35, wt=1.0, fine=7)
    p.insert(1, "BITCRUSH", after=True, amount=0.45, mix=0.35)
    p.env(1, a=0.001, d=0.14, s=0.0, r=0.08)
    p.filter("LP24", hz=2800, res=0.15, keytrack=0.4)
    p.filter2("HP12", hz=240)
    p.arp("CHORD", rate="1/16", octaves=1, gate=0.3)
    bed(p)
    velocity(p, 0.6, 0.15)
    p.tone("CUTOFF", 0.15)
    p.performer(1, {0: gate_seq("x-xx-x-xx-x-xxx-"), 1: gate_seq("xxxxxxxx-x-x-x-x")}, rate="1/16")
    p.set("macro2", 0.6)
    p.motion("PERF1", "AMP", 0.9)
    echo(p, time="3/16", mix=0.1, feedback=0.25, amount=0.1)
    grit(p, mode="HARD", drive=0.4, tone=0.5, amount=0.4, base=0.25)
    p.doc("Crushed chord stabs stuttering in a gated pattern on the bar", "C3–C5",
          "Industrial, breakbeat, drum and bass, trailer", "Hold chords; the gate is the rhythm", "RHYTHM",
          "Pattern B builds; MOTION 0 plays every sixteenth")
    out.append(p)

    p = A("COLD PULSE", "BASIC", "BASIC")
    p.osc(0, level=0.7, wt=0.0)
    p.insert(1, "SINE", after=True, amount=0.25, mix=0.6)
    p.insert(2, "SHIFT", after=True, amount=1.0, freq=0.515, mix=0.2)
    p.env(1, a=0.002, d=0.25, s=0.3, r=0.15)
    p.filter("LP12", hz=3000, res=0.05, keytrack=0.3)
    p.filter2("HP12", hz=200)
    p.arp("UP", rate="1/16", octaves=1, gate=0.6)
    bed(p)
    velocity(p, 0.6, 0.0)
    p.mod("VELOCITY", "INS1_AMOUNT", 0.3)
    p.tone("INS1_AMOUNT", 0.25)
    p.lfo(1, "SINE", sync="4 BAR", mode="FREE")
    p.set("macro2", 0.4)
    p.motion("LFO1", "INS1_AMOUNT", 0.3)
    p.motion("LFO1", "INS2_FREQ", 0.02)
    echo(p, time="3/16", mix=0.16, feedback=0.35, amount=0.14, pingpong=True)
    plate(p, mix=0.14)
    p.doc("A plain sine pulse, gently shaped, with a shifted shadow drifting against it", "C3–C5",
          "Film score, thriller, minimal, ambient", "Hold chords for long stretches", "RHYTHM",
          "The shadow is where the unease lives; MOTION 0 makes it a clean pulse")
    out.append(p)

    p = A("THROAT SEQUENCE", "FORMANT", "PWM")
    p.osc(0, level=0.6, wt=0.4)
    p.osc(1, level=0.35, wt=0.5)
    p.env(1, a=0.002, d=0.25, s=0.25, r=0.12)
    p.filter("FORMANT", cut=0.4, res=0.3, keytrack=0.2, drive=0.3)
    p.filter2("HP12", hz=200)
    p.arp("UPDOWN", rate="1/16", octaves=2, gate=0.55)
    bed(p)
    velocity(p, 0.6, 0.12)
    p.tone("CUTOFF", 0.15)
    p.performer(1, {0: seq("aaaabbbbccccdddd", {"a": (-0.7, "GLIDE"), "b": (0.3, "GLIDE"), "c": (0.8, "GLIDE"), "d": (-0.1, "GLIDE")})},
                rate="1/8")
    p.set("macro2", 0.5)
    p.motion("PERF1", "CUTOFF", 0.45)
    echo(p, time="1/8", mix=0.1, feedback=0.3, amount=0.12)
    grit(p, mode="TUBE", drive=0.4, tone=0.5, amount=0.4, base=0.2)
    p.doc("A sequence that talks: the vowel glides through four shapes over two bars", "C3–C5",
          "Industrial, electro, darkwave", "Hold chords for two bars", "RHYTHM",
          "Vowels sit where a voice does; duck it under vocals")
    out.append(p)

    p = A("GLASS TENSION", "GLASS", "BASIC")
    p.osc(0, level=0.65, wt=0.5)
    p.insert(1, "RECTIFY", after=True, amount=0.5, mix=0.35)
    p.insert(2, "COMB", after=True, amount=0.4, freq=0.75, mix=0.2)
    p.env(1, a=0.002, d=0.3, s=0.1, r=0.2)
    p.filter("LP12", hz=3000, res=0.05, keytrack=0.3)
    p.filter2("HP12", hz=250)
    p.arp("UP", rate="3/16", octaves=2, gate=0.6)
    bed(p)
    velocity(p, 0.6, 0.12)
    p.tone("CUTOFF", 0.15)
    p.lfo(1, "SINE", sync="1 BAR", mode="FREE")
    p.set("macro2", 0.4)
    p.motion("LFO1", "INS1_AMOUNT", 0.3)
    echo(p, time="1/4", mix=0.14, feedback=0.35, amount=0.12, pingpong=True)
    plate(p, mix=0.14)
    p.doc("Dotted-eighth glass rolling against the beat, edged with a rectified buzz", "C3–C5",
          "Film, post-rock, ambient", "Hold chords for two bars; the 3-against-4 does the work", "RHYTHM",
          "Pairs with a straight-sixteenth hat for the push and pull")
    out.append(p)

    p = A("IRON STEPS", "ANALOG", "BASIC")
    p.osc(0, level=0.7, wt=0.9)
    p.insert(1, "FOLD", amount=0.25, mix=0.6)
    p.insert(2, "DECIMATE", after=True, amount=0.25, mix=0.4)
    p.env(1, a=0.002, d=0.3, s=0.2, r=0.12)
    p.env(2, a=0.001, d=0.15, s=0.0, r=0.1)
    p.filter("LP24", hz=1100, res=0.25, keytrack=0.5, env=0.3)
    p.filter2("HP12", hz=160)
    p.arp("DOWN", rate="1/8", octaves=2, gate=0.6)
    bed(p)
    velocity(p, 0.6, 0.15)
    p.tone("CUTOFF", 0.18)
    p.lfo(1, "TRIANGLE", sync="1 BAR", mode="FREE")
    p.set("macro2", 0.4)
    p.motion("LFO1", "INS1_AMOUNT", 0.3)
    echo(p, time="3/16", mix=0.1, feedback=0.3, amount=0.12)
    grit(p, mode="TUBE", drive=0.45, tone=0.5, amount=0.4, base=0.25)
    p.doc("Heavy eighth-note steps walking down two octaves, folded and crushed", "C3–C5",
          "Industrial rock, doom, trailer", "Hold minor chords for a bar", "RHYTHM",
          "Mid-heavy: carve 400 Hz from guitars under it")
    out.append(p)

    p = A("DATA DROPLETS", "DIGITAL", "DIGITAL")
    p.osc(0, level=0.6, wt=0.4)
    p.osc(1, level=0.3, wt=0.7, octave=1)
    p.insert(1, "BITCRUSH", after=True, amount=0.55, mix=0.4)
    p.env(1, a=0.001, d=0.18, s=0.0, r=0.1)
    p.filter("LP24", hz=2600, res=0.15, keytrack=0.4)
    p.filter2("HP12", hz=250)
    p.arp("RANDOM", rate="1/16", octaves=2, gate=0.5)
    bed(p)
    velocity(p, 0.6, 0.12)
    p.tone("CUTOFF", 0.15)
    p.lfo(1, "SAMPLE_HOLD", sync="1/16", mode="FREE")
    p.set("macro2", 0.4)
    p.motion("LFO1", "A_WTPOS", 0.3)
    p.motion("LFO1", "CUTOFF", 0.22)
    p.motion("LFO1", "INS1_AMOUNT", 0.25)
    echo(p, time="1/8", mix=0.12, feedback=0.3, amount=0.12, pingpong=True)
    grit(p, mode="BITCRUSH", drive=0.35, tone=0.5, amount=0.4, base=0.2)
    p.doc("Random digital droplets from your chord, each one a different timbre", "C3–C5",
          "Glitch, IDM, sci-fi, industrial", "Hold chords under a steady beat", "TEXTURE",
          "Only chord notes play; the timbre changes every step in time")
    out.append(p)

    p = A("HEARTBEAT MONITOR", "BASIC", "BASIC")
    p.osc(0, level=0.7, wt=0.0)
    p.insert(1, "RING", after=True, amount=0.3, freq=0.75, mix=0.3)
    p.insert(2, "BITCRUSH", after=True, amount=0.4, mix=0.2)
    p.env(1, a=0.002, d=0.35, s=0.0, r=0.3)
    p.filter("LP12", hz=4000, res=0.05, keytrack=0.3)
    p.filter2("HP12", hz=250)
    p.arp("UP", rate="1/4", octaves=1, gate=0.3)
    bed(p)
    velocity(p, 0.6, 0.1)
    p.tone("EQ_HIGH", 0.25)
    p.lfo(1, "SINE", sync="2 BAR", mode="FREE")
    p.set("macro2", 0.4)
    p.motion("LFO1", "INS1_AMOUNT", 0.3)
    echo(p, time="1/4", mix=0.2, feedback=0.4, amount=0.14)
    plate(p, mix=0.16)
    p.doc("A slow, sparse pulse like a monitor in an empty room, with long echoes", "C4–C6",
          "Film score, thriller, ambient", "Hold chords; one note per beat", "TEXTURE",
          "Sparse on purpose; the echo fills the gaps")
    out.append(p)

    p = A("SPARKING CHAIN", "SYNC_SWEEP", "BASIC")
    p.osc(0, level=0.65, wt=0.3)
    p.insert(1, "RING", after=True, amount=0.4, freq=0.625, mix=0.2)
    p.env(1, a=0.001, d=0.15, s=0.1, r=0.08)
    p.env(3, a=0.001, d=0.12, s=0.0, r=0.08)
    p.mod("ENV3", "A_WTPOS", 0.5)
    p.filter("LP24", hz=3000, res=0.15, keytrack=0.4)
    p.filter2("HP12", hz=240)
    p.arp("UP", rate="1/16", octaves=2, gate=0.45)
    bed(p)
    velocity(p, 0.6, 0.12)
    p.tone("A_WTPOS", 0.15)
    p.performer(1, {0: gate_seq("xxx-xxx-xx-xxxx-")}, rate="1/16")
    p.set("macro2", 0.55)
    p.motion("PERF1", "AMP", 0.85)
    echo(p, time="1/8", mix=0.1, feedback=0.25, amount=0.1)
    grit(p, mode="HARD", drive=0.4, tone=0.5, amount=0.4, base=0.25)
    p.doc("A sparking sync arp with gaps knocked into its rhythm", "C3–C5", "Industrial, electro, EBM",
          "Hold chords; the gaps line up with the bar", "RHYTHM", "MOTION 0 fills the gaps in")
    out.append(p)

    p = A("SUB MOTOR ARP", "ANALOG", "BASIC")
    p.osc(0, level=0.7, wt=0.95)
    p.sub(0.35, "SINE")
    p.route_filter(sub=False)
    p.insert(1, "FOLD", amount=0.2, mix=0.6)
    p.env(1, a=0.001, d=0.18, s=0.35, r=0.06)
    p.env(2, a=0.001, d=0.1, s=0.0, r=0.06)
    p.filter("LP24", hz=450, res=0.25, keytrack=0.4, env=0.35, drive=0.3)
    p.arp("UP", rate="1/16", octaves=1, gate=0.55)
    p.voice(voices=4, glide=0.0, vel=0.55, bend=2)
    velocity(p, 0.6, 0.15)
    p.tone("CUTOFF", 0.15)
    p.lfo(1, "SINE", sync="1 BAR", mode="FREE")
    p.set("macro2", 0.4)
    p.motion("LFO1", "CUTOFF", 0.12)
    p.motion("LFO1", "INS1_AMOUNT", 0.2)
    grit(p, mode="TUBE", drive=0.45, tone=0.45, amount=0.4, base=0.25)
    p.context(shift=-12, allow_low=True, pitch_note=48)
    p.doc("A rolling bass arp with a clean sub under a folded top", "C2–C4, sub an octave under",
          "Industrial techno, EBM, synthwave", "Hold two- or three-note shapes low", "RHYTHM",
          "Dry and mono in the lows; sidechain it to the kick")
    out.append(p)

    p = A("ANXIETY", "ANALOG", "PWM")
    p.osc(0, level=0.6, wt=0.9)
    p.osc(1, level=0.35, wt=0.3, octave=1)
    p.insert(1, "DECIMATE", after=True, amount=0.2, mix=0.35)
    p.env(1, a=0.001, d=0.18, s=0.25, r=0.1)
    p.filter("LP24", hz=700, res=0.3, keytrack=0.5, drive=0.3)
    p.filter2("HP12", hz=200)
    p.arp("UP", rate="1/16", octaves=1, gate=0.5)
    bed(p)
    velocity(p, 0.6, 0.12)
    p.tone("CUTOFF", 0.15)
    p.performer(1, {0: [(-1.0 + 2.0 * i / 15, "GLIDE") for i in range(16)]}, rate="1/4")
    p.set("macro2", 0.5)
    p.motion("PERF1", "CUTOFF", 0.4)
    p.motion("PERF1", "INS1_AMOUNT", 0.2)
    echo(p, time="1/8", mix=0.1, feedback=0.3, amount=0.12)
    grit(p, mode="TUBE", drive=0.4, tone=0.5, amount=0.4, base=0.2)
    p.doc("A tight sixteenth pulse whose filter climbs for four bars and resets: a build that won't stop", "C3–C5",
          "Trailer, thriller, techno builds", "Hold one chord through a four-bar build", "TRANSITION",
          "The climb is on the song grid; start the chord on the bar")
    out.append(p)

    p = A("LOST TRANSMISSION", "ANALOG", "GLASS")
    p.osc(0, level=0.6, wt=0.7)
    p.osc(1, level=0.3, wt=0.5, octave=1)
    p.noise(0.035, type="CRACKLE", color=0.6, keytrack=False)
    p.insert(1, "DECIMATE", after=True, amount=0.35, mix=0.45)
    p.env(1, a=0.002, d=0.25, s=0.2, r=0.15)
    p.filter("BP", hz=1500, res=0.25, keytrack=0.3, drive=0.35)
    p.filter2("HP12", hz=300)
    p.arp("UPDOWN", rate="1/8", octaves=2, gate=0.6)
    bed(p)
    velocity(p, 0.6, 0.12)
    p.tone("CUTOFF", 0.08)
    p.lfo(1, "SMOOTH_RANDOM", hz=0.4, mode="FREE")
    p.set("macro2", 0.4)
    p.motion("LFO1", "CUTOFF", 0.12)
    p.motion("LFO1", "NOISE_LEVEL", 0.06)
    echo(p, time="3/16", mix=0.14, feedback=0.35, amount=0.12)
    plate(p, mix=0.1)
    p.doc("An arpeggio caught on a failing radio: band-passed, crushed, drifting off station", "C3–C5",
          "Trip-hop, film, industrial, hip-hop", "Hold chords for two bars", "TEXTURE",
          "Band-passed: it never touches the bass or the air")
    out.append(p)

    return out
