"""BASS: mono, dry in the lows, and never polite. Damage sits in the mids,
where it reads on small speakers, while the sub stays clean and centred."""

from lunatk import Preset
from bank2._common import accents, gate_seq, grit, seq, velocity


def B(name, a="ANALOG", b="BASIC"):
    return Preset(name, "BASS", a, b)


def mono(p, glide=0.02, legato=True, vel=0.45):
    return p.voice(voices=1, glide=glide, legato=legato, glide_always=False, vel=vel, bend=2)


def dry_space(p, amount=0.2, time="1/8"):
    """SPACE on a bass is a high-passed delay; the lows stay dry."""
    p.delay(time=time, mix=0.0, feedback=0.25, lowcut=0.8, highcut=0.45, width=0.2)
    return p.space(reverb=0, delay=amount)


def presets():
    out = []

    p = B("RUSTED PISTON")
    p.osc(0, level=0.8, wt=0.95)
    p.sub(0.45, "SINE")
    p.insert(1, "FOLD", amount=0.35, mix=0.8)
    p.filter("LP24", hz=420, res=0.3, keytrack=0.4, env=0.42, drive=0.35)
    p.feedback(amount=0.18, drive=0.5, tone=0.35)
    p.env(1, a=0.002, d=0.3, s=0.8, r=0.08)
    p.env(2, a=0.001, d=0.22, s=0.15, r=0.1)
    mono(p)
    velocity(p, 0.5, 0.14)
    p.tone("CUTOFF", 0.16)
    p.lfo(1, "TRIANGLE", sync="1 BAR", mode="FREE")
    p.set("macro2", 0.35)
    p.motion("LFO1", "INS1_AMOUNT", 0.25)
    dry_space(p)
    grit(p, mode="TUBE", drive=0.45, tone=0.45, amount=0.5, base=0.3)
    p.doc("Folded saw bass that snarls on every note, with a clean sine underneath", "E0–E2",
          "Industrial rock, EBM, dark techno, trailer", "Driving eighths and held roots", "FOREGROUND",
          "The sub stays clean; if the snarl fights a guitar, cut 800 Hz before you touch GRIT")
    out.append(p)

    p = B("CORRODE LINE", "PWM", "BASIC")
    p.osc(0, level=0.8, wt=0.35)
    p.sub(0.5, "SINE")
    p.insert(1, "BITCRUSH", amount=0.62, mix=0.7)
    p.filter("LADDER", hz=520, res=0.35, keytrack=0.5, env=0.45)
    p.env(1, a=0.002, d=0.35, s=0.7, r=0.08)
    p.env(2, a=0.001, d=0.18, s=0.1, r=0.1)
    mono(p)
    velocity(p, 0.5, 0.16)
    p.tone("CUTOFF", 0.16)
    p.lfo(1, "SAMPLE_HOLD", sync="1/8", mode="FREE")
    p.set("macro2", 0.3)
    p.motion("LFO1", "INS1_AMOUNT", 0.3)
    p.motion("LFO1", "CUTOFF", 0.12)
    dry_space(p)
    grit(p, mode="DIODE", drive=0.4, tone=0.5, amount=0.45, base=0.15)
    p.doc("Pulse bass crushed before a ladder filter: the grain moves with every eighth", "E0–E2",
          "Industrial, darkwave, electro, glitch", "Sixteenth and eighth lines", "FOREGROUND",
          "Bit grain lives at 2–5 kHz; a low-pass at 6 kHz on the bus keeps it off the cymbals")
    out.append(p)

    p = B("BLOWN SPEAKER", "BASIC", "BASIC")
    p.osc(0, level=0.8, wt=1.0)
    p.sub(0.45, "SINE")
    p.filter("LP24", hz=650, res=0.45, keytrack=0.4, env=0.3, drive=0.5)
    p.feedback(amount=0.35, drive=0.7, tone=0.4)
    p.env(1, a=0.002, d=0.4, s=0.85, r=0.08)
    p.env(2, a=0.001, d=0.3, s=0.2, r=0.1)
    mono(p)
    velocity(p, 0.75, 0.3)
    p.mod("VELOCITY", "FEEDBACK", 0.3)
    p.tone("CUTOFF", 0.18)
    p.lfo(1, "SINE", hz=0.3, mode="TRIG")
    p.set("macro2", 0.3)
    p.motion("LFO1", "FB_TONE", 0.15)
    dry_space(p)
    grit(p, mode="HARD", drive=0.5, tone=0.45, amount=0.45, base=0.35)
    p.doc("Square bass through a filter feeding back on itself: harder notes break up more", "E0–E2",
          "Industrial rock, noise rock, trap, film", "Play dynamics: soft notes round, hard notes tear", "FOREGROUND",
          "Velocity drives the feedback; quantize velocity to about 90 for a steady part")
    out.append(p)

    p = B("GRINDER", "GROWL", "BASIC")
    p.osc(0, level=0.8, wt=0.3)
    p.sub(0.45, "SINE")
    p.insert(1, "FOLD", amount=0.2, mix=0.5)
    p.filter("LP24", hz=900, res=0.2, keytrack=0.4, env=0.25, drive=0.35)
    p.env(1, a=0.002, d=0.3, s=0.85, r=0.08)
    p.env(2, a=0.001, d=0.2, s=0.3, r=0.1)
    mono(p)
    velocity(p, 0.45, 0.1)
    p.tone("CUTOFF", 0.16)
    p.performer(1, {0: accents("X-x-X-xoX-x-Xox-", "DECAY")}, rate="1/16")
    p.set("macro2", 0.55)
    p.motion("PERF1", "A_WTPOS", 0.45)
    dry_space(p)
    grit(p, mode="TUBE", drive=0.5, tone=0.4, amount=0.5, base=0.3)
    p.doc("Growl table chewed by a sixteenth-note wavetable sequence locked to the bar", "E0–E2",
          "Industrial techno, bass music, EBM", "Hold notes; the grind is the rhythm", "RHYTHM",
          "MOTION sets how hard it chews; at 0 it is a steady growl")
    out.append(p)

    p = B("HOLLOW MOTOR", "BASIC", "BASIC")
    p.osc(0, level=0.8, wt=0.0)
    p.sub(0.35, "SINE")
    p.insert(1, "RECTIFY", after=True, amount=0.8, mix=0.7)
    p.insert(2, "SINE", after=True, amount=0.25, mix=0.5)
    p.filter("LP12", hz=1400, res=0.1, keytrack=0.5, env=0.2)
    p.env(1, a=0.003, d=0.4, s=0.9, r=0.1)
    p.env(2, a=0.001, d=0.25, s=0.3, r=0.1)
    mono(p, glide=0.04)
    velocity(p, 0.75, 0.3)
    p.tone("CUTOFF", 0.18)
    p.lfo(1, "SINE", sync="2 BAR", mode="FREE")
    p.set("macro2", 0.35)
    p.motion("LFO1", "INS2_AMOUNT", 0.3)
    dry_space(p)
    grit(p, mode="SOFT", drive=0.4, tone=0.5, amount=0.5, base=0.1)
    p.doc("A sine rectified into an octave-up buzz: hollow, mechanical, all mid", "E0–E2",
          "Minimal industrial, film, darkwave", "Slow lines and held notes", "SUPPORT",
          "No real sub harmonics beyond the sine; layer a kick-friendly sub if the track needs weight")
    out.append(p)

    p = B("WOUND SUB", "BASIC", "BASIC")
    p.osc(0, level=0.85, wt=0.0)
    p.insert(1, "SINE", after=True, amount=0.32, mix=0.75)
    p.filter("LP24", hz=1200, res=0.05, keytrack=0.6)
    p.env(1, a=0.003, d=0.4, s=0.95, r=0.08)
    mono(p)
    velocity(p, 0.4, 0.0)
    p.mod("VELOCITY", "INS1_AMOUNT", 0.25)
    p.tone("INS1_AMOUNT", 0.25)
    p.lfo(1, "SINE", hz=0.2, mode="TRIG")
    p.set("macro2", 0.25)
    p.motion("LFO1", "INS1_AMOUNT", 0.1)
    dry_space(p)
    grit(p, mode="TUBE", drive=0.4, tone=0.5, amount=0.55, base=0.2)
    p.doc("A sine sub wrapped in its own harmonics so it reads on laptops and phones", "C0–C2",
          "Trap, industrial pop, cinematic, techno", "Long notes and slides", "SUPPORT",
          "TONE and velocity add harmonics; the fundamental stays put for the kick to sit on")
    out.append(p)

    p = B("CHAIN DRAG", "ANALOG", "BASIC")
    p.osc(0, level=0.8, wt=0.9)
    p.sub(0.45, "SINE")
    p.insert(1, "DECIMATE", amount=0.45, mix=0.6)
    p.filter("LP24", hz=500, res=0.35, keytrack=0.5, env=0.45)
    p.env(1, a=0.002, d=0.3, s=0.7, r=0.08)
    p.env(2, a=0.001, d=0.2, s=0.05, r=0.08)
    mono(p)
    velocity(p, 0.5, 0.15)
    p.tone("CUTOFF", 0.16)
    p.performer(1, {0: seq("x--x--x-x--x-x--", {"x": (0.8, "DECAY")})}, rate="1/16")
    p.set("macro2", 0.4)
    p.motion("PERF1", "INS1_AMOUNT", 0.35)
    dry_space(p)
    grit(p, mode="HARD", drive=0.4, tone=0.45, amount=0.45, base=0.2)
    p.doc("Saw bass with a sample-rate crush that spikes on a syncopated grid", "E0–E2",
          "Industrial, breakbeat, EBM, horror", "Eighths and held roots", "RHYTHM",
          "The crush spikes land on the song's grid; MOTION 0 leaves a steady, lightly crushed tone")
    out.append(p)

    p = B("KNIFE REESE", "ANALOG", "ANALOG")
    p.osc(0, level=0.6, wt=1.0, unison=3, detune=0.28, width=0.1)
    p.osc(1, level=0.45, wt=1.0, fine=-9, unison=2, detune=0.2, width=0.08)
    p.sub(0.4, "SINE")
    p.route_filter(sub=False)
    p.insert(1, "COMB", after=True, amount=0.4, freq=0.75, mix=0.35)
    p.filter("LP24", hz=750, res=0.25, keytrack=0.4, drive=0.3)
    p.env(1, a=0.004, d=0.5, s=0.9, r=0.1)
    mono(p, glide=0.05)
    velocity(p, 0.4, 0.08)
    p.tone("CUTOFF", 0.18)
    p.lfo(1, "TRIANGLE", sync="2 BAR", mode="FREE")
    p.set("macro2", 0.45)
    p.motion("LFO1", "CUTOFF", 0.14)
    p.motion("LFO1", "INS1_FREQ", 0.06)
    dry_space(p)
    grit(p, mode="TUBE", drive=0.45, tone=0.45, amount=0.45, base=0.25)
    p.doc("Detuned saw reese with a tuned comb ringing an octave up", "E0–E2", "Drum and bass, industrial, dark techno",
          "Long notes; slides between them", "FOREGROUND",
          "The detune is narrow on purpose, so it survives mono. The comb ring sits near 200–400 Hz; dip there if it boxes")
    out.append(p)

    p = B("DOWNSHIFT", "ANALOG", "BASIC")
    p.osc(0, level=0.8, wt=0.8)
    p.sub(0.45, "SINE")
    p.route_filter(sub=False)
    p.insert(1, "SHIFT", after=True, amount=1.0, freq=0.47, mix=0.4)
    p.filter("LP24", hz=800, res=0.2, keytrack=0.5, env=0.25)
    p.env(1, a=0.003, d=0.4, s=0.85, r=0.1)
    p.env(2, a=0.001, d=0.3, s=0.2, r=0.1)
    mono(p)
    velocity(p, 0.45, 0.1)
    p.tone("CUTOFF", 0.16)
    p.lfo(1, "SINE", hz=0.15, mode="TRIG")
    p.set("macro2", 0.35)
    p.motion("LFO1", "INS1_FREQ", 0.02)
    dry_space(p)
    grit(p, mode="SOFT", drive=0.4, tone=0.5, amount=0.5, base=0.2)
    p.doc("Saw bass blended with a copy shifted a few hertz down: it beats and sours against itself", "E0–E2",
          "Film score, dark ambient, industrial", "Held notes, slow lines", "SUPPORT",
          "The beating is the point; for a tighter low end high-pass the shifted copy with TONE down")
    out.append(p)

    p = B("IRON LUNG", "FORMANT", "ANALOG")
    p.osc(0, level=0.7, wt=0.3)
    p.osc(1, level=0.35, wt=0.9, octave=-1)
    p.noise(0.08, type="BREATH", color=0.4)
    p.filter("FORMANT", cut=0.35, res=0.3, keytrack=0.2, env=0.15)
    p.filter2("LP24", hz=1800)
    p.feedback(amount=0.22, drive=0.4, tone=0.5)
    p.env(1, a=0.004, d=0.4, s=0.85, r=0.1)
    p.env(2, a=0.001, d=0.4, s=0.3, r=0.1)
    mono(p, glide=0.04)
    velocity(p, 0.75, 0.3)
    p.tone("CUTOFF", 0.2)
    p.lfo(1, "TRIANGLE", sync="1 BAR", mode="FREE")
    p.set("macro2", 0.45)
    p.motion("LFO1", "CUTOFF", 0.18)
    dry_space(p)
    grit(p, mode="TUBE", drive=0.4, tone=0.5, amount=0.45, base=0.15)
    p.doc("A breathing, vowel-shaped bass that opens and closes over the bar", "E0–E2", "Industrial, trip-hop, horror, darkwave",
          "Held notes and slow riffs", "FOREGROUND",
          "The vowel lives at 400–900 Hz; keep vocals out of that band or automate TONE down under them")
    out.append(p)

    p = B("STATIC PRESSURE", "ANALOG", "BASIC")
    p.osc(0, level=0.8, wt=1.0)
    p.sub(0.4, "SINE")
    p.route_filter(sub=False)
    p.filter("LP24", hz=260, res=0.55, keytrack=0.4, env=0.3, drive=0.3)
    p.env(1, a=0.002, d=0.3, s=0.85, r=0.06)
    p.env(2, a=0.001, d=0.14, s=0.0, r=0.08)
    mono(p, glide=0.03)
    velocity(p, 0.5, 0.18)
    p.tone("CUTOFF", 0.16)
    p.performer(1, {0: accents("X-o-x-X-o-x-Xxo-", "DECAY"), 1: accents("x-x-x-x-X-x-x-X-", "DECAY")}, rate="1/16")
    p.set("macro2", 0.55)
    p.motion("PERF1", "CUTOFF", 0.4)
    dry_space(p)
    grit(p, mode="DIODE", drive=0.45, tone=0.5, amount=0.45, base=0.25)
    p.doc("Acid-style resonant saw with a sixteenth accent pattern locked to the bar", "E0–E2", "Industrial techno, EBM, acid",
          "Hold notes and let the accents play; pattern B is straighter", "RHYTHM",
          "Resonance peaks move with the accents; a dynamic EQ at 300–600 Hz tames the loudest ones")
    out.append(p)

    p = B("BENT RAIL", "BASIC", "BASIC")
    p.osc(0, level=0.8, wt=0.66)
    p.sub(0.4, "SINE")
    p.insert(1, "FOLD", amount=0.5, mix=0.7)
    p.filter("LP24", hz=700, res=0.2, keytrack=0.5, env=0.3)
    p.env(1, a=0.002, d=0.4, s=0.9, r=0.08)
    p.env(2, a=0.001, d=0.3, s=0.2, r=0.1)
    p.voice(voices=1, glide=0.12, legato=True, glide_always=True, vel=0.45, bend=7)
    velocity(p, 0.45, 0.1)
    p.tone("INS1_AMOUNT", 0.25)
    p.lfo(1, "SINE", hz=0.4, mode="TRIG", delay=0.3, rise=0.4)
    p.set("macro2", 0.3)
    p.motion("LFO1", "INS1_AMOUNT", 0.2)
    dry_space(p)
    grit(p, mode="SOFT", drive=0.4, tone=0.5, amount=0.5, base=0.15)
    p.doc("Square bass that always slides and folds harder as notes hold", "E0–E2", "Industrial, synthwave, electro, film",
          "Legato lines; every note glides into the next", "FOREGROUND",
          "Glide is always on: quantize note starts so the slides land on time")
    out.append(p)

    p = B("CONCRETE FM", "BASIC", "BASIC")
    p.osc(0, level=0.8, wt=0.0, warp="FM", warp_amt=0.35)
    p.osc(1, level=0.002, wt=0.0, octave=1)
    p.sub(0.4, "SINE")
    p.route_filter(sub=False)
    p.filter("LP24", hz=900, res=0.15, keytrack=0.4, env=0.3)
    p.env(1, a=0.002, d=0.35, s=0.8, r=0.08)
    p.env(2, a=0.001, d=0.2, s=0.2, r=0.1)
    p.env(3, a=0.001, d=0.25, s=0.3, r=0.1)
    p.mod("ENV3", "A_WARP", 0.3)
    mono(p)
    velocity(p, 0.75, 0.3)
    p.tone("A_WARP", 0.2)
    p.lfo(1, "TRIANGLE", sync="1/2", mode="FREE")
    p.set("macro2", 0.3)
    p.motion("LFO1", "A_WARP", 0.12)
    dry_space(p)
    grit(p, mode="HARD", drive=0.45, tone=0.45, amount=0.45, base=0.25)
    p.doc("FM bass with a hard metallic bark on the attack", "E0–E2", "Industrial, EBM, techno, game",
          "Short notes; the bark is on every attack", "FOREGROUND",
          "The bark sits at 1–2 kHz; that is where to cut if it covers the snare")
    out.append(p)

    p = B("VOID PUNCH", "BASIC", "BASIC")
    p.osc(0, level=0.8, wt=0.0)
    p.sub(0.5, "SINE")
    p.noise(0.12, type="CRACKLE", color=0.3)
    p.insert(1, "BITCRUSH", after=True, amount=0.5, mix=0.3)
    p.filter("LP24", hz=500, res=0.1, keytrack=0.4, env=0.5)
    p.env(1, a=0.001, d=0.45, s=0.3, r=0.15)
    p.env(2, a=0.001, d=0.08, s=0.0, r=0.1)
    p.env(3, a=0.001, d=0.06, s=0.0, r=0.05)
    p.mod("ENV3", "PITCH", 0.25)
    mono(p, legato=False)
    velocity(p, 0.75, 0.3)
    p.tone("CUTOFF", 0.18)
    p.lfo(1, "SAMPLE_HOLD", sync="1/16", mode="FREE")
    p.set("macro2", 0.3)
    p.motion("LFO1", "INS1_AMOUNT", 0.4)
    p.motion("LFO1", "NOISE_LEVEL", 0.1)
    dry_space(p)
    grit(p, mode="HARD", drive=0.5, tone=0.45, amount=0.5, base=0.3)
    p.context(allow_air=True, motion_window=(0.05, 1.5))
    p.doc("A pitch-dropping punch bass with crackle and crush on the hit", "E0–E2", "Industrial hip-hop, trap, breakbeat",
          "Short notes on the beat; a kick-bass for sparse beats", "RHYTHM",
          "It fights the kick: pick one to own 50 Hz, or sidechain this to the kick")
    out.append(p)

    p = B("TAPE SNARL", "ANALOG", "BASIC")
    p.osc(0, level=0.8, wt=0.85)
    p.sub(0.4, "SINE")
    p.route_filter(sub=False)
    p.insert(1, "DECIMATE", after=True, amount=0.18, mix=0.5)
    p.filter("LP24", hz=600, res=0.2, keytrack=0.4, env=0.3, drive=0.35)
    p.env(1, a=0.003, d=0.4, s=0.85, r=0.1)
    p.env(2, a=0.001, d=0.25, s=0.2, r=0.1)
    mono(p)
    velocity(p, 0.45, 0.1)
    p.tone("CUTOFF", 0.18)
    p.lfo(1, "SMOOTH_RANDOM", hz=1.2, mode="TRIG")
    p.set("macro2", 0.4)
    p.motion("LFO1", "A_FINE", 0.06)
    p.motion("LFO1", "CUTOFF", 0.05)
    dry_space(p)
    grit(p, mode="TUBE", drive=0.5, tone=0.4, amount=0.45, base=0.35)
    p.doc("Overdriven saw bass that wobbles like a stretched tape", "E0–E2", "Industrial rock, lo-fi, film, darkwave",
          "Held notes and slow riffs", "FOREGROUND",
          "The wobble is a few cents; pull MOTION down if it rubs against a tuned guitar")
    out.append(p)

    p = B("WIRE BITE", "BASIC", "BASIC")
    p.osc(0, level=0.8, wt=0.33)
    p.sub(0.4, "SINE")
    p.route_filter(sub=False)
    p.insert(1, "RING", after=True, amount=0.6, freq=0.625, mix=0.45)
    p.filter("LP24", hz=1100, res=0.15, keytrack=0.5, env=0.3)
    p.env(1, a=0.002, d=0.35, s=0.8, r=0.08)
    p.env(2, a=0.001, d=0.2, s=0.2, r=0.1)
    mono(p)
    velocity(p, 0.75, 0.3)
    p.tone("INS1_AMOUNT", 0.25)
    p.lfo(1, "TRIANGLE", sync="1 BAR", mode="FREE")
    p.set("macro2", 0.35)
    p.motion("LFO1", "INS1_AMOUNT", 0.2)
    dry_space(p)
    grit(p, mode="HARD", drive=0.4, tone=0.5, amount=0.45, base=0.2)
    p.doc("Triangle bass with a ring-modulated wire edge an octave up", "E0–E2", "Industrial, EBM, post-punk",
          "Picked-bass style lines", "FOREGROUND",
          "The wire edge reads through distorted guitars; TONE down if it gets thin")
    out.append(p)

    p = B("GUT PUNCH", "BASIC", "BASIC")
    p.osc(0, level=0.85, wt=0.0)
    p.insert(1, "SINE", after=True, amount=0.4, mix=0.6)
    p.filter("LP24", hz=2500, res=0.05, keytrack=0.3)
    p.env(1, a=0.001, d=0.9, s=0.0, r=0.3)
    p.env(3, a=0.001, d=0.05, s=0.0, r=0.05)
    p.mod("ENV3", "PITCH", 0.3)
    mono(p, legato=False, glide=0.0)
    velocity(p, 0.55, 0.0)
    p.mod("VELOCITY", "INS1_AMOUNT", 0.3)
    p.tone("INS1_AMOUNT", 0.25)
    p.lfo(1, "SINE", hz=3.0, mode="TRIG")
    p.set("macro2", 0.2)
    p.motion("LFO1", "INS1_AMOUNT", 0.3)
    p.motion("LFO1", "PITCH", 0.004)
    dry_space(p)
    grit(p, mode="HARD", drive=0.55, tone=0.45, amount=0.5, base=0.35)
    p.context(allow_low=True, motion_window=(0.05, 0.9))
    p.doc("A long 808-style boom, saturated so the tail growls", "C0–C2", "Industrial hip-hop, trap, cinematic hits",
          "One note per hit; tune it to the song", "RHYTHM",
          "It is a kick and a bass at once: leave room by thinning the kick below 80 Hz")
    out.append(p)

    p = B("SEIZURE", "ANALOG", "PWM")
    p.osc(0, level=0.7, wt=0.9)
    p.osc(1, level=0.35, wt=0.4, octave=-1)
    p.sub(0.35, "SINE")
    p.filter("LP24", hz=750, res=0.3, keytrack=0.4, env=0.2, drive=0.3)
    p.filter2("HP12", hz=25)
    p.env(1, a=0.002, d=0.4, s=0.9, r=0.06)
    mono(p)
    velocity(p, 0.45, 0.1)
    p.tone("CUTOFF", 0.18)
    p.performer(1, {0: gate_seq("xx-xx-x-xx-x--x-"), 1: gate_seq("x-x-x-x-xxxxx-x-"),
                    2: gate_seq("xxx-xx-x-x-xxx--"), 3: gate_seq("x---x---x-x-xxxx")}, rate="1/16")
    p.set("macro2", 0.7)
    p.motion("PERF1", "AMP", 0.95)
    dry_space(p)
    grit(p, mode="HARD", drive=0.45, tone=0.45, amount=0.45, base=0.25)
    p.doc("Held bass chopped into stuttering sixteenths on the bar; four patterns", "E0–E2",
          "Industrial, glitch, breakbeat, trailer", "Hold roots; switch patterns with PATTERN or the switch keys", "RHYTHM",
          "MOTION 0 opens the gate fully for a plain drone; half way is a softer stutter")
    out.append(p)

    p = B("SLUDGE", "ANALOG", "BASIC")
    p.osc(0, level=0.8, wt=0.95)
    p.osc(1, level=0.5, wt=0.66, fine=6)
    p.sub(0.35, "SINE")
    p.route_filter(sub=False)
    p.filter("LP12", hz=380, res=0.2, keytrack=0.5, env=0.2, drive=0.4)
    p.filter2("HP12", hz=25)
    p.feedback(amount=0.16, drive=0.6, tone=0.45)
    p.env(1, a=0.004, d=0.5, s=0.9, r=0.1)
    p.env(2, a=0.001, d=0.4, s=0.3, r=0.1)
    mono(p, glide=0.06)
    velocity(p, 0.4, 0.08)
    p.tone("CUTOFF", 0.2)
    p.lfo(1, "SINE", hz=0.25, mode="TRIG")
    p.set("macro2", 0.3)
    p.motion("LFO1", "FEEDBACK", 0.12)
    dry_space(p)
    grit(p, mode="TUBE", drive=0.5, tone=0.4, amount=0.4, base=0.35)
    p.doc("Thick, low, saturated through a feedback loop: slow and heavy", "E0–E2", "Doom industrial, trailer, noise rock",
          "Slow, heavy notes", "FOREGROUND",
          "A lot of 150–300 Hz: carve that out of guitars, not out of this")
    out.append(p)

    p = B("METAL TONGUE", "BASIC", "BASIC")
    p.osc(0, level=0.8, wt=0.66)
    p.sub(0.4, "SINE")
    p.route_filter(sub=False)
    p.insert(1, "COMB", amount=0.75, freq=0.5, mix=0.6)
    p.filter("LP24", hz=1400, res=0.1, keytrack=0.5, env=0.35)
    p.env(1, a=0.001, d=0.6, s=0.35, r=0.12)
    p.env(2, a=0.001, d=0.3, s=0.1, r=0.1)
    mono(p, legato=False)
    velocity(p, 0.5, 0.14)
    p.tone("INS1_AMOUNT", 0.2)
    p.lfo(1, "TRIANGLE", sync="1/2", mode="FREE")
    p.set("macro2", 0.3)
    p.motion("LFO1", "INS1_FREQ", 0.03)
    dry_space(p)
    grit(p, mode="SOFT", drive=0.4, tone=0.5, amount=0.45, base=0.15)
    p.doc("Plucked metal bass: a tuned comb rings on each note", "E0–E2", "Industrial, darkwave, film, experimental",
          "Plucked eighths and held roots", "FOREGROUND",
          "The ring is tuned to the note, so it stays musical; shorten notes if the rings pile up")
    out.append(p)

    p = B("RED LINE", "DIGITAL", "ANALOG")
    p.osc(0, level=0.6, wt=0.5)
    p.osc(1, level=0.45, wt=1.0, fine=7)
    p.sub(0.4, "SINE")
    p.route_filter(sub=False)
    p.insert(1, "BITCRUSH", amount=0.5, mix=0.6)
    p.filter("LP24", hz=1300, res=0.2, keytrack=0.4, env=0.2, drive=0.4)
    p.env(1, a=0.002, d=0.4, s=0.9, r=0.08)
    mono(p)
    velocity(p, 0.4, 0.1)
    p.tone("CUTOFF", 0.18)
    p.lfo(1, "SQUARE", sync="1/4", mode="FREE")
    p.set("macro2", 0.3)
    p.motion("LFO1", "INS1_AMOUNT", 0.15)
    dry_space(p)
    grit(p, mode="HARD", drive=0.55, tone=0.45, amount=0.4, base=0.45)
    p.doc("Wall-of-noise bass for choruses: crushed, clipped and bright", "E0–E2", "Industrial rock, metal, noise, trailer",
          "Driving eighths under guitars", "FOREGROUND",
          "It is loud in the mids by design; give it the chorus and something cleaner for the verse")
    out.append(p)

    p = B("BLACK SIGNAL", "BASIC", "PWM")
    p.osc(0, level=0.6, wt=0.0)
    p.osc(1, level=0.5, wt=0.2, octave=-1)
    p.filter("FORMANT", cut=0.3, res=0.35, keytrack=0.2, drive=0.35)
    p.filter2("LP24", hz=1600)
    p.env(1, a=0.004, d=0.4, s=0.9, r=0.1)
    mono(p, glide=0.05)
    velocity(p, 0.75, 0.3)
    p.tone("CUTOFF", 0.2)
    p.performer(1, {0: seq("aaaabbbbccccdddd", {"a": (-0.8, "GLIDE"), "b": (0.2, "GLIDE"), "c": (0.8, "GLIDE"), "d": (-0.2, "GLIDE")})},
                rate="1/8")
    p.set("macro2", 0.5)
    p.motion("PERF1", "CUTOFF", 0.55)
    p.motion("PERF1", "A_WTPOS", 0.45)
    dry_space(p)
    grit(p, mode="TUBE", drive=0.45, tone=0.5, amount=0.45, base=0.2)
    p.doc("Talking bass: the vowel glides through four shapes over two bars", "E0–E2", "Industrial funk, darkwave, electro",
          "Held notes; the vowels move by themselves", "FOREGROUND",
          "MOTION 0 freezes the vowel; TONE picks which one")
    out.append(p)

    p = B("SIREN FLOOR", "BASIC", "BASIC")
    p.osc(0, level=0.8, wt=0.3)
    p.sub(0.45, "SINE")
    p.route_filter(sub=False)
    p.insert(1, "SINE", after=True, amount=0.3, mix=0.5)
    p.filter("LP24", hz=550, res=0.35, keytrack=0.4, drive=0.3)
    p.env(1, a=0.01, d=0.5, s=0.95, r=0.15)
    mono(p, glide=0.08)
    velocity(p, 0.75, 0.3)
    p.tone("CUTOFF", 0.2)
    p.lfo(1, "SINE", sync="2 BAR", mode="FREE")
    p.lfo(4, "SINE", hz=5.0, mode="TRIG", delay=0.3, rise=0.5)
    p.mod("LFO4", "PITCH", 0.03, aux="MODWHEEL")
    p.set("macro2", 0.4)
    p.motion("LFO1", "CUTOFF", 0.2)
    dry_space(p)
    grit(p, mode="SOFT", drive=0.4, tone=0.5, amount=0.5, base=0.15)
    p.doc("Slow-sweeping sub bass that rises and falls over two bars; mod wheel for vibrato", "E0–E2",
          "Cinematic, dark ambient, trap", "Long held notes", "SUPPORT",
          "The sweep is slow enough to feel like tension, not wobble; MOTION 0 fixes it")
    out.append(p)

    p = B("TORN CABLE", "SYNC_SWEEP", "BASIC")
    p.osc(0, level=0.7, wt=0.4)
    p.sub(0.45, "SINE")
    p.route_filter(sub=False)
    p.filter("LP24", hz=1100, res=0.2, keytrack=0.4, env=0.3)
    p.feedback(amount=0.2, drive=0.5, tone=0.5)
    p.env(1, a=0.002, d=0.35, s=0.85, r=0.08)
    p.env(2, a=0.001, d=0.2, s=0.2, r=0.1)
    p.env(3, a=0.001, d=0.3, s=0.0, r=0.1)
    p.mod("ENV3", "A_WTPOS", 0.4)
    mono(p)
    velocity(p, 0.45, 0.1)
    p.tone("A_WTPOS", 0.2)
    p.lfo(1, "TRIANGLE", sync="1/4", mode="FREE")
    p.set("macro2", 0.3)
    p.motion("LFO1", "A_WTPOS", 0.15)
    dry_space(p)
    grit(p, mode="HARD", drive=0.45, tone=0.45, amount=0.45, base=0.25)
    p.doc("Hard-sync bass that rips on every attack, then settles", "E0–E2", "Industrial, electro, EBM",
          "Staccato eighths", "FOREGROUND",
          "The rip is fast; if it clicks against the kick, delay the bass a few milliseconds")
    out.append(p)

    return out
