"""DRONE: sustained dread. Every drone evolves over bars, carries damage, and
keeps its lows mono so it sits under a mix instead of swallowing it."""

from lunatk import Preset
from bank2._common import grit, seq, space, velocity


def D(name, a="ANALOG", b="ANALOG"):
    return Preset(name, "DRONE", a, b)


def bed(p, voices=6, vel=0.25):
    return p.voice(voices=voices, glide=0.0, vel=vel, bend=2)


def cave(p, mix=0.22, decay=0.42, amount=0.16, width=0.25):
    """Narrow reverb: LUNATK's reverb has no low cut, so width stays low."""
    return space(p, mix, mode="HALL", size=0.7, decay=decay, damp=0.6, predelay=0.1, width=width, amount=amount)


def presets():
    out = []

    p = D("DREAD ENGINE", "ANALOG", "ANALOG")
    p.osc(0, level=0.6, wt=1.0, unison=3, detune=0.12, width=0.15)
    p.osc(1, level=0.4, wt=0.9, fine=-6)
    p.filter("LP24", hz=500, res=0.35, keytrack=0.3, drive=0.35)
    p.filter2("HP12", hz=30)
    p.feedback(amount=0.2, drive=0.5, tone=0.5)
    p.env(1, a=1.5, d=2.0, s=1.0, r=2.5)
    bed(p)
    velocity(p, 0.25, 0.05)
    p.tone("CUTOFF", 0.2)
    p.lfo(1, "TRIANGLE", sync="4 BAR", mode="FREE")
    p.lfo(2, "SMOOTH_RANDOM", hz=0.15, mode="FREE")
    p.set("macro2", 0.5)
    p.motion("LFO1", "CUTOFF", 0.2)
    p.motion("LFO2", "FEEDBACK", 0.2)
    cave(p)
    grit(p, mode="TUBE", drive=0.45, tone=0.45, amount=0.4, base=0.25)
    p.doc("A low saw engine whose filter slowly opens and feeds back on itself", "D1–D3",
          "Film score, trailer, industrial, dark ambient", "Hold a root and fifth for bars", "SUPPORT",
          "Mono below 150 Hz; sits under anything. MOTION 0 is a steady hum")
    out.append(p)

    p = D("FERROUS HUM", "PWM", "BASIC")
    p.osc(0, level=0.65, wt=0.2)
    p.osc(1, level=0.35, wt=0.0, octave=-1)
    p.insert(1, "COMB", after=True, amount=0.6, freq=0.75, mix=0.35)
    p.insert(2, "DECIMATE", after=True, amount=0.2, mix=0.4)
    p.filter("LP24", hz=1200, res=0.15, keytrack=0.3)
    p.filter2("HP12", hz=30)
    p.env(1, a=0.8, d=2.0, s=1.0, r=2.0)
    bed(p)
    velocity(p, 0.25, 0.05)
    p.tone("CUTOFF", 0.2)
    p.lfo(1, "SINE", sync="2 BAR", mode="FREE")
    p.set("macro2", 0.45)
    p.motion("LFO1", "INS1_AMOUNT", 0.3)
    p.motion("LFO1", "CUTOFF", 0.12)
    cave(p, mix=0.16)
    grit(p, mode="HARD", drive=0.4, tone=0.5, amount=0.35, base=0.2)
    p.doc("An electrical hum through iron: buzzing pulse, ringing octaves, broken sample rate", "D1–D3",
          "Industrial, horror, sci-fi, noise", "Hold one note; the machine does the rest", "TEXTURE",
          "Buzzy in the mids: a band cut at 1–2 kHz pushes it into the background")
    out.append(p)

    p = D("CATHEDRAL ROT", "CHOIR", "ANALOG")
    p.osc(0, level=0.6, wt=0.5, unison=3, detune=0.1, width=0.0)
    p.osc(1, level=0.35, wt=0.8, octave=-1)
    p.insert(1, "COMB", after=True, amount=0.7, freq=0.5, mix=0.35)
    p.filter("LP12", hz=1800, res=0.1, keytrack=0.3)
    p.filter2("HP12", hz=40)
    p.feedback(amount=0.12, drive=0.4, tone=0.6)
    p.env(1, a=2.0, d=2.0, s=1.0, r=3.0)
    bed(p)
    velocity(p, 0.25, 0.05)
    p.tone("CUTOFF", 0.2)
    p.lfo(1, "SINE", sync="4 BAR", mode="FREE")
    p.set("macro2", 0.45)
    p.motion("LFO1", "A_WTPOS", 0.3)
    p.motion("LFO1", "INS1_AMOUNT", 0.2)
    cave(p, mix=0.26, width=0.12)
    grit(p, mode="SOFT", drive=0.35, tone=0.5, amount=0.35, base=0.15)
    p.doc("A choir rotting in a stone room: vowels drift, a comb rings, a filter loop hums under it", "D2–D4",
          "Film score, doom, gothic, horror", "Long held notes and fifths", "TEXTURE",
          "Long release: end it early before a cut")
    out.append(p)

    p = D("BLACK TIDE", "ANALOG", "BASIC")
    p.osc(0, level=0.55, wt=0.9)
    p.osc(1, level=0.45, wt=0.0, octave=-1)
    p.noise(0.08, type="BROWN", color=0.7, keytrack=False)
    p.filter("LP24", hz=350, res=0.25, keytrack=0.3, drive=0.35)
    p.filter2("HP12", hz=28)
    p.env(1, a=2.0, d=2.0, s=1.0, r=3.0)
    bed(p)
    velocity(p, 0.25, 0.05)
    p.tone("CUTOFF", 0.22)
    p.performer(1, {0: seq("aaaabbbbccccbbbb", {"a": (-0.6, "GLIDE"), "b": (0.2, "GLIDE"), "c": (0.8, "GLIDE")})}, rate="1/4")
    p.set("macro2", 0.5)
    p.motion("PERF1", "CUTOFF", 0.3)
    p.motion("PERF1", "NOISE_LEVEL", 0.06)
    cave(p, mix=0.18)
    grit(p, mode="TUBE", drive=0.45, tone=0.4, amount=0.35, base=0.25)
    p.doc("A low swell that rolls in and out over four bars, with a dark surf of noise", "D1–D3",
          "Trailer, dark ambient, doom, film", "Hold a low note through a whole section", "SUPPORT",
          "The swell follows the bar; start it on a downbeat")
    out.append(p)

    p = D("BOWED GIRDER", "BASIC", "SPECTRAL_COMB")
    p.osc(0, level=0.3, wt=0.66)
    p.osc(1, level=0.3, wt=0.5)
    p.noise(0.35, type="METAL", color=0.4)
    p.insert(1, "COMB", amount=0.9, freq=0.5, mix=0.8)
    p.filter("BP", hz=900, res=0.2, keytrack=0.4)
    p.filter2("HP12", hz=60)
    p.feedback(amount=0.18, drive=0.5, tone=0.6)
    p.env(1, a=2.5, d=2.0, s=1.0, r=2.5)
    bed(p)
    velocity(p, 0.25, 0.05)
    p.tone("CUTOFF", 0.1)
    p.lfo(1, "SMOOTH_RANDOM", hz=0.3, mode="FREE")
    p.set("macro2", 0.45)
    p.motion("LFO1", "NOISE_COLOR", 0.25)
    p.motion("LFO1", "CUTOFF", 0.12)
    cave(p, mix=0.24)
    grit(p, mode="SOFT", drive=0.35, tone=0.5, amount=0.35, base=0.15)
    p.doc("A steel girder bowed until it sings: metal noise ringing a comb tuned to the note", "D2–D4",
          "Horror, film score, industrial, experimental", "Long notes; the swell takes three seconds", "TEXTURE",
          "Band-passed: it sits in the middle and never muddies the lows")
    out.append(p)

    p = D("NERVE HUM", "BASIC", "BASIC")
    p.osc(0, level=0.7, wt=0.0)
    p.insert(1, "RECTIFY", after=True, amount=0.6, mix=0.5)
    p.insert(2, "SHIFT", after=True, amount=1.0, freq=0.51, mix=0.3)
    p.filter("LP12", hz=2500, res=0.05, keytrack=0.3)
    p.filter2("HP12", hz=30)
    p.env(1, a=1.0, d=2.0, s=1.0, r=2.0)
    bed(p)
    velocity(p, 0.25, 0.05)
    p.tone("INS1_AMOUNT", 0.25)
    p.lfo(1, "SINE", sync="4 BAR", mode="FREE")
    p.set("macro2", 0.45)
    p.motion("LFO1", "INS1_AMOUNT", 0.3)
    p.motion("LFO1", "INS2_FREQ", 0.01)
    cave(p, mix=0.16)
    p.doc("A sine hum rectified into a buzz, beating slowly against a shifted copy", "D2–D4",
          "Film score, thriller, minimal, horror", "Hold single notes", "TEXTURE",
          "The beating is slow: tension without melody")
    out.append(p)

    p = D("TAPE GRAVE", "ORGAN", "ANALOG")
    p.osc(0, level=0.6, wt=0.6)
    p.osc(1, level=0.35, wt=0.9, octave=-1, fine=6)
    p.noise(0.07, type="VINYL", color=0.5, keytrack=False)
    p.insert(1, "DECIMATE", after=True, amount=0.3, mix=0.4)
    p.filter("LP12", hz=1500, res=0.1, keytrack=0.3)
    p.filter2("HP12", hz=35)
    p.env(1, a=1.2, d=2.0, s=1.0, r=2.0)
    bed(p)
    velocity(p, 0.25, 0.05)
    p.tone("CUTOFF", 0.2)
    p.lfo(1, "SMOOTH_RANDOM", hz=0.5, mode="FREE")
    p.lfo(2, "SINE", sync="4 BAR", mode="FREE")
    p.set("macro2", 0.45)
    p.motion("LFO1", "PITCH", 0.003)
    p.motion("LFO2", "CUTOFF", 0.15)
    cave(p, mix=0.2)
    grit(p, mode="TUBE", drive=0.4, tone=0.45, amount=0.35, base=0.2)
    p.doc("An organ chord buried on an old tape: wow, dust and a broken sample rate", "D2–D4",
          "Film score, lo-fi, horror, ambient", "Hold chords or fifths", "TEXTURE",
          "The wow is up to 7 cents; MOTION 0 steadies it against tuned parts")
    out.append(p)

    p = D("SULFUR", "ANALOG", "ANALOG")
    p.osc(0, level=0.6, wt=0.9, unison=3, detune=0.14, width=0.2)
    p.osc(1, level=0.35, wt=0.8, fine=-9)
    p.insert(1, "RING", after=True, amount=0.4, freq=0.5625, mix=0.2)
    p.filter("LP24", hz=700, res=0.2, keytrack=0.3, drive=0.3)
    p.filter2("HP12", hz=35)
    p.env(1, a=1.5, d=2.0, s=1.0, r=2.5)
    bed(p)
    velocity(p, 0.25, 0.05)
    p.tone("CUTOFF", 0.2)
    p.lfo(1, "TRIANGLE", sync="2 BAR", mode="FREE")
    p.set("macro2", 0.45)
    p.motion("LFO1", "INS1_AMOUNT", 0.3)
    p.motion("LFO1", "CUTOFF", 0.12)
    cave(p)
    grit(p, mode="HARD", drive=0.4, tone=0.45, amount=0.35, base=0.2)
    p.doc("A dark detuned drone with a tritone ring breathing in and out", "D1–D3",
          "Horror, doom, industrial", "Hold single notes", "TEXTURE",
          "Dissonant by design; MOTION 0 keeps the ring faint")
    out.append(p)

    p = D("PRESSURE CHAMBER", "ANALOG", "PWM")
    p.osc(0, level=0.6, wt=0.95, unison=3, detune=0.12, width=0.0)
    p.osc(1, level=0.35, wt=0.3)
    p.filter("LP24", hz=800, res=0.3, keytrack=0.3, drive=0.35)
    p.filter2("HP12", hz=35)
    p.feedback(amount=0.15, drive=0.6, tone=0.5)
    p.env(1, a=1.0, d=2.0, s=1.0, r=2.0)
    bed(p)
    velocity(p, 0.25, 0.05)
    p.tone("CUTOFF", 0.2)
    p.performer(1, {0: [(-1.0 + 2.0 * i / 15, "GLIDE") for i in range(16)]}, rate="1/4")
    p.set("macro2", 0.5)
    p.motion("PERF1", "FEEDBACK", 0.35)
    p.motion("PERF1", "CUTOFF", 0.2)
    cave(p, mix=0.18, width=0.12)
    grit(p, mode="TUBE", drive=0.45, tone=0.45, amount=0.35, base=0.25)
    p.doc("Pressure building for four bars as the filter loop begins to howl, then release", "D1–D3",
          "Trailer, thriller, industrial builds", "Hold a note through four-bar builds", "TRANSITION",
          "The build follows the song grid; MOTION sets how hard it howls")
    out.append(p)

    p = D("RADIATION", "DIGITAL", "BASIC")
    p.osc(0, level=0.45, wt=0.5)
    p.noise(0.25, type="DIGITAL", color=0.4)
    p.insert(1, "BITCRUSH", after=True, amount=0.5, mix=0.4)
    p.filter("BP", hz=1200, res=0.2, keytrack=0.3)
    p.filter2("HP12", hz=80)
    p.env(1, a=1.0, d=2.0, s=1.0, r=2.0)
    bed(p)
    velocity(p, 0.25, 0.05)
    p.tone("CUTOFF", 0.1)
    p.lfo(1, "SAMPLE_HOLD", sync="1/8", mode="FREE")
    p.lfo(2, "SINE", sync="4 BAR", mode="FREE")
    p.set("macro2", 0.45)
    p.motion("LFO1", "NOISE_LEVEL", 0.1)
    p.motion("LFO2", "CUTOFF", 0.15)
    cave(p, mix=0.14)
    p.context(allow_air=True)
    p.doc("A Geiger-counter drone: digital noise crackling over a crushed tone", "D2–D4",
          "Sci-fi, horror, noise, industrial", "Hold a note under a scene", "TEXTURE",
          "The crackle jumps in eighths on MOTION; band-passed, so it stays out of the lows")
    out.append(p)

    p = D("DEEP STRUCTURE", "BASIC", "BASIC")
    p.osc(0, level=0.65, wt=0.0, warp="FM", warp_amt=0.25)
    p.osc(1, level=0.002, wt=0.0, octave=1, semi=7)
    p.filter("LP24", hz=900, res=0.1, keytrack=0.3, drive=0.3)
    p.filter2("HP12", hz=30)
    p.env(1, a=1.5, d=2.0, s=1.0, r=2.5)
    bed(p)
    velocity(p, 0.25, 0.05)
    p.tone("A_WARP", 0.2)
    p.lfo(1, "SINE", sync="4 BAR", mode="FREE")
    p.set("macro2", 0.45)
    p.motion("LFO1", "A_WARP", 0.25)
    cave(p, mix=0.2)
    grit(p, mode="SOFT", drive=0.35, tone=0.45, amount=0.35, base=0.15)
    p.doc("A low FM drone whose metal grows and fades over four bars", "D1–D3",
          "Film score, sci-fi, ambient", "Hold single low notes", "SUPPORT",
          "The FM ratio is a twelfth, so the partials stay harmonic")
    out.append(p)

    p = D("HOLLOW SIGNAL", "FORMANT", "CHOIR")
    p.osc(0, level=0.55, wt=0.4, unison=3, detune=0.1, width=0.25)
    p.osc(1, level=0.35, wt=0.6)
    p.noise(0.08, type="BREATH", color=0.5)
    p.filter("FORMANT", cut=0.4, res=0.3, keytrack=0.2)
    p.filter2("HP12", hz=60)
    p.env(1, a=1.5, d=2.0, s=1.0, r=2.5)
    bed(p)
    velocity(p, 0.25, 0.05)
    p.tone("CUTOFF", 0.15)
    p.performer(1, {0: seq("aaaabbbbccccdddd", {"a": (-0.6, "GLIDE"), "b": (0.3, "GLIDE"), "c": (0.8, "GLIDE"), "d": (-0.2, "GLIDE")})}, rate="1/4")
    p.set("macro2", 0.5)
    p.motion("PERF1", "CUTOFF", 0.4)
    cave(p, mix=0.22)
    grit(p, mode="SOFT", drive=0.3, tone=0.5, amount=0.35, base=0.15)
    p.doc("A hollow voice drone speaking four slow vowels over four bars", "D2–D4",
          "Horror, dark ambient, film", "Hold one note through a scene", "TEXTURE",
          "Vowels follow the bar; MOTION 0 holds one")
    out.append(p)

    p = D("RUST FIELD", "SPECTRAL_COMB", "ANALOG")
    p.osc(0, level=0.6, wt=0.3, unison=3, detune=0.1, width=0.0)
    p.osc(1, level=0.35, wt=0.9, octave=-1)
    p.insert(1, "FOLD", after=True, amount=0.2, mix=0.4)
    p.filter("LP24", hz=1500, res=0.15, keytrack=0.3)
    p.filter2("HP12", hz=35)
    p.env(1, a=1.5, d=2.0, s=1.0, r=2.5)
    bed(p)
    velocity(p, 0.25, 0.05)
    p.tone("CUTOFF", 0.2)
    p.lfo(1, "TRIANGLE", sync="4 BAR", mode="FREE")
    p.set("macro2", 0.45)
    p.motion("LFO1", "A_WTPOS", 0.35)
    p.motion("LFO1", "INS1_AMOUNT", 0.2)
    cave(p, mix=0.2, width=0.12)
    grit(p, mode="TUBE", drive=0.4, tone=0.45, amount=0.35, base=0.2)
    p.doc("A combed, folded drone sweeping slowly through rust-coloured harmonics", "D1–D3",
          "Industrial, doom, film", "Hold notes for bars", "TEXTURE",
          "Four-bar sweep: pair it with section changes")
    out.append(p)

    p = D("WAR ROOM", "ANALOG", "BASIC")
    p.osc(0, level=0.6, wt=0.85, unison=3, detune=0.1, width=0.15)
    p.osc(1, level=0.4, wt=0.0, octave=-1)
    p.filter("LP24", hz=450, res=0.2, keytrack=0.3, drive=0.35)
    p.filter2("HP12", hz=30)
    p.env(1, a=0.8, d=2.0, s=1.0, r=2.0)
    bed(p)
    velocity(p, 0.25, 0.05)
    p.tone("CUTOFF", 0.2)
    p.performer(1, {0: seq("x---x---x---x---", {"x": (-1.0, "DECAY")})}, rate="1/16")
    p.set("macro2", 0.5)
    p.motion("PERF1", "AMP", 0.85)
    p.motion("PERF1", "CUTOFF", 0.25)
    cave(p, mix=0.16)
    grit(p, mode="TUBE", drive=0.45, tone=0.45, amount=0.35, base=0.25)
    p.doc("A low drone that throbs on every beat, like a war-room hum under a briefing", "D1–D3",
          "Thriller, trailer, film score", "Hold a low note under a scene", "SUPPORT",
          "The throb is on the beat; it keeps tension without drums")
    out.append(p)

    p = D("SINGING WIRE", "BASIC", "BASIC")
    p.osc(0, level=0.6, wt=0.66)
    p.filter("LP24", hz=520, res=0.55, keytrack=1.0)
    p.filter2("HP12", hz=40)
    p.feedback(amount=0.3, drive=0.4, tone=0.7)
    p.env(1, a=1.5, d=2.0, s=1.0, r=2.5)
    bed(p)
    velocity(p, 0.25, 0.05)
    p.tone("CUTOFF", 0.12)
    p.lfo(1, "SINE", sync="4 BAR", mode="FREE")
    p.set("macro2", 0.45)
    p.motion("LFO1", "FEEDBACK", 0.25)
    p.motion("LFO1", "RES", 0.08)
    cave(p, mix=0.22)
    grit(p, mode="SOFT", drive=0.3, tone=0.5, amount=0.35, base=0.15)
    p.doc("A resonant filter loop tuned to the note until it sings like feedback from an amp", "D2–D4",
          "Noise rock, film, industrial, ambient", "Hold single notes", "TEXTURE",
          "It rises and falls in volume on its own over four bars")
    out.append(p)

    p = D("GLASS STORM", "GLASS", "GLASS")
    p.osc(0, level=0.55, wt=0.6, unison=5, detune=0.12, width=0.4)
    p.osc(1, level=0.3, wt=0.3, octave=1)
    p.insert(1, "SHIFT", after=True, amount=1.0, freq=0.53, mix=0.3)
    p.insert(2, "DECIMATE", after=True, amount=0.2, mix=0.3)
    p.filter("LP12", hz=3500, res=0.05, keytrack=0.2)
    p.filter2("HP12", hz=200)
    p.env(1, a=2.0, d=2.0, s=1.0, r=3.0)
    bed(p)
    velocity(p, 0.25, 0.05)
    p.tone("EQ_HIGH", 0.25)
    p.eq(high=-3, high_hz=8000)
    p.lfo(1, "SMOOTH_RANDOM", hz=0.25, mode="FREE")
    p.set("macro2", 0.45)
    p.motion("LFO1", "INS1_FREQ", 0.04)
    p.motion("LFO1", "A_WTPOS", 0.25)
    cave(p, mix=0.24, width=0.5)
    p.context(root=62, pitch_note=69)
    p.doc("A high cloud of glass, shifted and crushed, blown around slowly", "D3–D5",
          "Film score, ambient, sci-fi", "Hold notes high above everything", "TEXTURE",
          "High-passed at 200 Hz: pure atmosphere, no weight")
    out.append(p)

    p = D("SUBTERRANEAN", "BASIC", "ANALOG")
    p.osc(0, level=0.6, wt=0.0)
    p.osc(1, level=0.4, wt=0.9, fine=-5)
    p.insert(1, "COMB", after=True, amount=0.5, freq=0.25, mix=0.3)
    p.insert(2, "SINE", after=True, amount=0.25, mix=0.5)
    p.filter("LP24", hz=400, res=0.15, keytrack=0.3)
    p.filter2("HP12", hz=30)
    p.env(1, a=2.0, d=2.0, s=1.0, r=3.0)
    bed(p)
    velocity(p, 0.25, 0.05)
    p.tone("CUTOFF", 0.2)
    p.lfo(1, "SINE", sync="4 BAR", mode="FREE")
    p.set("macro2", 0.45)
    p.motion("LFO1", "CUTOFF", 0.2)
    p.motion("LFO1", "INS1_AMOUNT", 0.2)
    cave(p, mix=0.16)
    p.doc("The low, hollow resonance of something enormous underground", "D1–D3",
          "Trailer, doom, horror, dark ambient", "Hold one low note", "SUPPORT",
          "Mono and dark; ride TONE up for the reveal")
    out.append(p)

    p = D("ASH RAIN", "ANALOG", "CHOIR")
    p.osc(0, level=0.55, wt=0.7, unison=3, detune=0.12, width=0.0)
    p.osc(1, level=0.35, wt=0.4)
    p.noise(0.08, type="CRACKLE", color=0.5, keytrack=False)
    p.insert(1, "BITCRUSH", after=True, amount=0.4, mix=0.25)
    p.filter("LP12", hz=1600, res=0.1, keytrack=0.3)
    p.filter2("HP12", hz=40)
    p.env(1, a=1.5, d=2.0, s=1.0, r=2.5)
    bed(p)
    velocity(p, 0.25, 0.05)
    p.tone("CUTOFF", 0.2)
    p.lfo(1, "SINE", sync="4 BAR", mode="FREE")
    p.lfo(2, "SAMPLE_HOLD", sync="1/4", mode="FREE")
    p.set("macro2", 0.45)
    p.motion("LFO1", "CUTOFF", 0.18)
    p.motion("LFO2", "NOISE_LEVEL", 0.06)
    cave(p, mix=0.22, width=0.12)
    grit(p, mode="SOFT", drive=0.3, tone=0.5, amount=0.35, base=0.15)
    p.doc("A soft chord under falling ash: crackle, crush and a slow sweep", "D2–D4",
          "Film score, post-apocalyptic, ambient", "Hold chords or fifths", "TEXTURE",
          "Gentle enough to sit under dialogue")
    out.append(p)

    return out
