"""FX: transitions, impacts and noises you can play. Each starts on the key
(NOTE-mode performers and per-note envelopes), so it lands where you place
it; lows stay mono."""

from lunatk import Preset
from bank2._common import gate_seq, grit, seq, space


def F(name, a="ANALOG", b="BASIC"):
    return Preset(name, "FX", a, b)


def one(p, voices=2, vel=0.4):
    return p.voice(voices=voices, glide=0.0, legato=False, vel=vel, bend=12)


def hall(p, mix=0.22, decay=0.4, amount=0.18, width=0.35):
    return space(p, mix, mode="HALL", size=0.7, decay=decay, damp=0.55, predelay=0.08, width=width, amount=amount)


RAMP_UP = [(-1.0 + 2.0 * i / 15, "GLIDE") for i in range(16)]
RAMP_DOWN = [(1.0 - 2.0 * i / 15, "GLIDE") for i in range(16)]


def presets():
    out = []

    p = F("TENSION RISER", "ANALOG", "ANALOG")
    p.osc(0, level=0.5, wt=1.0, unison=5, detune=0.2, width=0.4)
    p.noise(0.3, "WHITE", color=0.4)
    p.insert(1, "SHIFT", after=True, amount=1.0, freq=0.5, mix=0.35)
    p.filter("LP24", hz=400, res=0.3, keytrack=0.2)
    p.filter2("HP12", hz=120)
    p.feedback(amount=0.1, drive=0.5, tone=0.7)
    p.env(1, a=0.3, d=1.0, s=1.0, r=1.0)
    one(p)
    p.performer(1, {0: RAMP_UP}, mode="TRIG", rate="1/8", steps=16)
    p.set("macro2", 0.6)
    p.motion("PERF1", "CUTOFF", 0.6)
    p.motion("PERF1", "INS1_FREQ", 0.12)
    p.motion("PERF1", "FEEDBACK", 0.3)
    p.tone("F2_CUTOFF", 0.2)
    hall(p)
    grit(p, mode="SOFT", drive=0.35, tone=0.5, amount=0.35, base=0.15)
    p.context(unpitched=True)
    p.doc("A two-bar riser: filter, shift and feedback all climbing from the key press", "C3–C5",
          "Trailer, EDM-noir, industrial, film", "Hold a note two bars before the drop", "TRANSITION",
          "Starts when you press the key, so place it two bars early; MOTION sets how far it climbs")
    out.append(p)

    p = F("DOWNFALL", "ANALOG", "BASIC")
    p.osc(0, level=0.7, wt=0.9)
    p.sub(0.3, "SINE")
    p.insert(1, "DECIMATE", after=True, amount=0.1, mix=0.6)
    p.filter("LP24", hz=2500, res=0.2, keytrack=0.3)
    p.filter2("HP12", hz=40)
    p.env(1, a=0.005, d=2.0, s=0.6, r=1.0)
    p.env(4, a=0.001, d=2.5, s=0.0, r=1.0, dcurve=0.4)
    p.mod("ENV4", "PITCH", 0.5)
    p.mod("ENV4", "CUTOFF", 0.3)
    one(p)
    p.performer(1, {0: RAMP_UP}, mode="TRIG", rate="1/16", steps=16)
    p.set("macro2", 0.5)
    p.motion("PERF1", "INS1_AMOUNT", 0.6)
    p.tone("CUTOFF", 0.2)
    hall(p, mix=0.16)
    grit(p, mode="TUBE", drive=0.45, tone=0.45, amount=0.4, base=0.25)
    p.context(unpitched=True)
    p.doc("A fall: pitch dives an octave while the sample rate crumbles", "C3–C5", "Trailer, industrial, film, bass music",
          "Hit it on the last beat before a break", "TRANSITION", "The dive takes about two seconds regardless of tempo")
    out.append(p)

    p = F("RADIO GHOSTS", "ANALOG", "GLASS")
    p.osc(0, level=0.4, wt=0.6)
    p.osc(1, level=0.3, wt=0.4, octave=1)
    p.noise(0.3, "CRACKLE", color=0.4, keytrack=False)
    p.insert(1, "SHIFT", after=True, amount=1.0, freq=0.56, mix=0.5)
    p.insert(2, "DECIMATE", after=True, amount=0.3, mix=0.4)
    p.filter("BP", hz=1400, res=0.3, keytrack=0.2)
    p.filter2("HP12", hz=250)
    p.env(1, a=0.3, d=1.0, s=1.0, r=1.5)
    one(p)
    p.lfo(1, "SMOOTH_RANDOM", hz=0.8, mode="FREE")
    p.lfo(2, "SAMPLE_HOLD", sync="1/8", mode="FREE")
    p.set("macro2", 0.55)
    p.motion("LFO1", "CUTOFF", 0.3)
    p.motion("LFO1", "INS1_FREQ", 0.1)
    p.motion("LFO2", "NOISE_LEVEL", 0.15)
    p.tone("CUTOFF", 0.08)
    hall(p, mix=0.18)
    p.context(unpitched=True)
    p.doc("Tuning through a dead band: voices, whistles and static drifting past", "C3–C5",
          "Film, horror, sci-fi, trip-hop", "Hold under a scene or an intro", "TEXTURE",
          "Band-passed, so it sits anywhere; automate TONE to tune it")
    out.append(p)

    p = F("HYDRAULIC", "BASIC", "BASIC")
    p.osc(0, level=0.0, wt=0.0, on=False)
    p.noise(0.8, "WHITE", color=0.4, keytrack=False)
    p.insert(1, "COMB", after=True, amount=0.5, freq=0.4, mix=0.3)
    p.filter("BP", hz=2000, res=0.2)
    p.filter2("HP12", hz=200)
    p.env(1, a=0.05, d=0.8, s=0.7, r=0.6)
    one(p)
    p.performer(1, {0: seq("aaaabbbbaaaabbbb", {"a": (0.8, "GLIDE"), "b": (-0.8, "GLIDE")}), 1: gate_seq("xx--xx--xx--xxxx")},
                mode="TRIG", rate="1/16")
    p.set("macro2", 0.55)
    p.motion("PERF1", "CUTOFF", 0.35)
    p.tone("CUTOFF", 0.1)
    hall(p, mix=0.12)
    grit(p, mode="HARD", drive=0.35, tone=0.5, amount=0.35, base=0.15)
    p.context(unpitched=True, allow_air=True)
    p.doc("Hydraulic pistons venting air in rhythm", "Any", "Industrial, sci-fi, film, techno",
          "Hold for a mechanical texture; pattern B chops it", "TEXTURE", "Place it in the gaps between drums")
    out.append(p)

    p = F("IMPACT BLOOM", "BASIC", "ANALOG")
    p.osc(0, level=0.8, wt=0.0)
    p.osc(1, level=0.4, wt=0.9, octave=1)
    p.noise(0.4, "WHITE", color=0.3, keytrack=False)
    p.insert(1, "BITCRUSH", after=True, amount=0.4, mix=0.3)
    p.filter("LP24", hz=2000, res=0.1, keytrack=0.2, env=0.4)
    p.filter2("HP12", hz=30)
    p.env(1, a=0.0005, d=2.5, s=0.0, r=2.0, dcurve=-0.6)
    p.env(2, a=0.0005, d=0.4, s=0.0, r=0.3)
    p.env(4, a=0.0005, d=0.3, s=0.0, r=0.2)
    p.mod("ENV4", "PITCH", 0.3)
    p.mod("ENV4", "NOISE_LEVEL", 0.4)
    one(p)
    p.lfo(1, "SAMPLE_HOLD", sync="1/16", mode="FREE")
    p.set("macro2", 0.45)
    p.motion("LFO1", "INS1_AMOUNT", 0.5)
    p.motion("LFO1", "CUTOFF", 0.2)
    p.tone("CUTOFF", 0.2)
    hall(p, mix=0.26, decay=0.45)
    grit(p, mode="HARD", drive=0.5, tone=0.45, amount=0.4, base=0.35)
    p.context(unpitched=True, motion_window=(0.05, 1.5))
    p.doc("A hit that blooms into a long, crushed tail in a big room", "C1–C3 for weight", "Trailer, film, industrial",
          "One hit on a downbeat or a cut", "TRANSITION", "The tail runs two seconds; leave space after it")
    out.append(p)

    p = F("ALARM DECAY", "PWM", "BASIC")
    p.osc(0, level=0.7, wt=0.2)
    p.insert(1, "RING", after=True, amount=0.4, freq=0.5625, mix=0.3)
    p.filter("BP", hz=1500, res=0.2, keytrack=0.4)
    p.filter2("HP12", hz=250)
    p.env(1, a=0.01, d=3.0, s=0.4, r=1.0)
    one(p)
    p.lfo(1, "TRIANGLE", hz=1.2, mode="TRIG")
    p.set("macro2", 0.55)
    p.motion("LFO1", "PITCH", 0.12)
    p.motion("LFO1", "INS1_AMOUNT", 0.2)
    p.tone("CUTOFF", 0.08)
    hall(p, mix=0.2)
    grit(p, mode="HARD", drive=0.4, tone=0.5, amount=0.35, base=0.2)
    p.context(unpitched=True)
    p.doc("A siren wailing and fading into a big space", "C3–C5", "Film, industrial, trailer, horror",
          "Hold for an alarm; release to let it fade", "TRANSITION", "The wail is on MOTION; 0 is a steady tone")
    out.append(p)

    p = F("SWARM", "DIGITAL", "BASIC")
    p.osc(0, level=0.5, wt=0.4, unison=7, detune=0.4, width=0.1)
    p.insert(1, "RING", after=True, amount=0.8, freq=0.73, mix=0.5)
    p.insert(2, "BITCRUSH", after=True, amount=0.4, mix=0.3)
    p.filter("BP", hz=2500, res=0.2, keytrack=0.3)
    p.filter2("HP12", hz=300)
    p.env(1, a=0.5, d=1.0, s=1.0, r=1.0)
    one(p)
    p.lfo(1, "SAMPLE_HOLD", sync="1/32", mode="FREE")
    p.lfo(2, "SMOOTH_RANDOM", hz=0.7, mode="FREE")
    p.set("macro2", 0.55)
    p.motion("LFO1", "INS1_FREQ", 0.08)
    p.motion("LFO2", "CUTOFF", 0.25)
    p.tone("CUTOFF", 0.08)
    hall(p, mix=0.16)
    p.context(unpitched=True, allow_air=True)
    p.doc("An insect swarm of ring-modulated, crushed buzzing", "C3–C6", "Horror, sci-fi, industrial, noise",
          "Hold under a scene; bend for panic", "TEXTURE", "Band-passed and busy; keep it low in the mix")
    out.append(p)

    p = F("TAPE STOP", "ANALOG", "ANALOG")
    p.osc(0, level=0.6, wt=1.0, unison=3, detune=0.12, width=0.3)
    p.osc(1, level=0.35, wt=0.9)
    p.insert(1, "DECIMATE", after=True, amount=0.1, mix=0.5)
    p.filter("LP24", hz=3000, res=0.1, keytrack=0.3)
    p.filter2("HP12", hz=40)
    p.env(1, a=0.005, d=1.5, s=0.8, r=0.3)
    p.env(4, a=1.2, d=0.1, s=1.0, r=0.3, acurve=0.5)
    p.mod("ENV4", "PITCH", -0.6)
    p.mod("ENV4", "CUTOFF", -0.5)
    one(p)
    p.mod("ENV4", "INS1_AMOUNT", 0.5)
    p.set("macro2", 0.4)
    p.lfo(1, "SINE", hz=4.0, mode="TRIG")
    p.motion("LFO1", "PITCH", 0.01)
    p.tone("CUTOFF", 0.1)
    hall(p, mix=0.1)
    grit(p, mode="TUBE", drive=0.4, tone=0.45, amount=0.35, base=0.2)
    p.context(unpitched=True, allow_low=True)
    p.doc("A chord that grinds to a halt like a stopped tape, crumbling as it slows", "C3–C5",
          "Industrial, hip-hop, trailer, electronic breaks", "Hit a chord on the last beat before a gap", "TRANSITION",
          "The stop takes about a second; release the keys when you want silence")
    out.append(p)

    p = F("VACUUM", "ANALOG", "CHOIR")
    p.osc(0, level=0.5, wt=0.9, unison=5, detune=0.15, width=0.4)
    p.osc(1, level=0.3, wt=0.5)
    p.noise(0.2, "PINK", color=0.5)
    p.filter("LP24", hz=600, res=0.3, keytrack=0.2, env=0.5)
    p.filter2("HP12", hz=100)
    p.feedback(amount=0.2, drive=0.5, tone=0.6)
    p.env(1, a=2.0, d=0.1, s=1.0, r=0.05, acurve=0.7)
    p.env(2, a=2.0, d=0.1, s=1.0, r=0.05, acurve=0.7)
    one(p)
    p.lfo(1, "TRIANGLE", sync="1/2", mode="FREE")
    p.set("macro2", 0.45)
    p.motion("LFO1", "FEEDBACK", 0.2)
    p.tone("CUTOFF", 0.2)
    hall(p, mix=0.12)
    grit(p, mode="SOFT", drive=0.35, tone=0.5, amount=0.35, base=0.15)
    p.context(unpitched=True)
    p.doc("A reverse-style swell sucked in over two seconds and cut dead", "C3–C5", "Trailer, EDM-noir, film, industrial",
          "Press two seconds before the downbeat, release on it", "TRANSITION",
          "The cut is the release: let go exactly on the beat")
    out.append(p)

    p = F("STATIC STORM", "BASIC", "BASIC")
    p.osc(0, level=0.0, wt=0.0, on=False)
    p.noise(0.8, "DIGITAL", color=0.4, pitch=0.6, keytrack=False)
    p.insert(1, "BITCRUSH", after=True, amount=0.5, mix=0.5)
    p.filter("BP", hz=2500, res=0.2)
    p.filter2("HP12", hz=300)
    p.env(1, a=0.05, d=1.0, s=1.0, r=0.8)
    one(p)
    p.performer(1, {0: gate_seq("x-xx-x--xxx-x-x-"), 1: gate_seq("x.x.x.x.xxxxxxxx")}, mode="TRIG", rate="1/32")
    p.lfo(1, "SAMPLE_HOLD", sync="1/16", mode="FREE")
    p.set("macro2", 0.6)
    p.motion("PERF1", "AMP", 0.9)
    p.motion("LFO1", "CUTOFF", 0.2)
    p.tone("CUTOFF", 0.1)
    hall(p, mix=0.12)
    p.context(unpitched=True, allow_air=True)
    p.doc("A storm of digital static bursting in thirty-seconds", "Any", "Glitch, industrial, sci-fi, horror",
          "Hold for bursts of interference", "TEXTURE", "Very bright; keep it short or low")
    out.append(p)

    p = F("SUB DROP", "BASIC", "BASIC")
    p.osc(0, level=0.9, wt=0.0)
    p.insert(1, "SINE", after=True, amount=0.25, mix=0.5)
    p.filter("LP24", hz=1200, res=0.05)
    p.filter2("HP12", hz=25)
    p.env(1, a=0.001, d=2.5, s=0.0, r=1.0, dcurve=-0.4)
    p.env(4, a=0.001, d=1.5, s=0.0, r=0.5, dcurve=0.3)
    p.mod("ENV4", "PITCH", 0.5)
    one(p, voices=1)
    p.set("macro2", 0.4)
    p.lfo(1, "SINE", hz=3.0, mode="TRIG")
    p.motion("LFO1", "INS1_AMOUNT", 0.2)
    p.tone("INS1_AMOUNT", 0.25)
    grit(p, mode="TUBE", drive=0.45, tone=0.45, amount=0.4, base=0.25)
    p.context(unpitched=True, allow_low=True)
    p.doc("A sine sub dropping an octave into the floor, with a wrinkled edge", "C1–C3", "Trailer, trap, bass music, film",
          "One hit on a downbeat after a build", "TRANSITION", "Huge in the lows: nothing else should play 30–80 Hz under it")
    out.append(p)

    p = F("SIGNAL LOSS", "GLASS", "ANALOG")
    p.osc(0, level=0.6, wt=0.5)
    p.osc(1, level=0.3, wt=0.9, octave=-1)
    p.insert(1, "BITCRUSH", after=True, amount=0.1, mix=0.8)
    p.insert(2, "DECIMATE", after=True, amount=0.05, mix=0.6)
    p.filter("LP12", hz=4000, res=0.05, keytrack=0.3)
    p.filter2("HP12", hz=100)
    p.env(1, a=0.01, d=1.0, s=1.0, r=0.5)
    one(p)
    p.performer(1, {0: RAMP_UP}, mode="TRIG", rate="1/8", steps=16)
    p.performer(2, {0: gate_seq("xxxxxxxxxxx-xx--"), 1: gate_seq("xxxxxxx-x-x--x--")}, mode="TRIG", rate="1/8")
    p.set("macro2", 0.6)
    p.motion("PERF1", "INS1_AMOUNT", 0.6)
    p.motion("PERF1", "INS2_AMOUNT", 0.5)
    p.motion("PERF2", "AMP", 0.9)
    p.tone("CUTOFF", 0.2)
    hall(p, mix=0.14)
    p.context(unpitched=True)
    p.doc("A clean tone that crumbles and drops out over two bars, like a signal dying", "C3–C5",
          "Film, sci-fi, thriller, industrial outros", "Hold a note or chord for two bars", "TRANSITION",
          "Starts on the key: press it two bars before the cut")
    out.append(p)

    p = F("METAL FATIGUE", "SPECTRAL_COMB", "BASIC")
    p.osc(0, level=0.5, wt=0.3)
    p.noise(0.25, "METAL", color=0.5, pitch=0.3)
    p.insert(1, "COMB", after=True, amount=0.8, freq=0.3, mix=0.5)
    p.insert(2, "SHIFT", after=True, amount=1.0, freq=0.46, mix=0.35)
    p.filter("LP24", hz=1500, res=0.15, keytrack=0.2)
    p.filter2("HP12", hz=60)
    p.env(1, a=1.0, d=1.5, s=1.0, r=2.0)
    one(p)
    p.lfo(1, "SMOOTH_RANDOM", hz=0.3, mode="FREE")
    p.set("macro2", 0.5)
    p.motion("LFO1", "INS2_FREQ", 0.04)
    p.motion("LFO1", "INS1_FREQ", 0.06)
    p.tone("CUTOFF", 0.2)
    hall(p, mix=0.22)
    grit(p, mode="SOFT", drive=0.35, tone=0.45, amount=0.35, base=0.15)
    p.context(unpitched=True)
    p.doc("The groan of a steel structure under load", "C1–C3", "Horror, film, submarine, industrial",
          "Hold low notes for creaks and groans", "TEXTURE", "Low and moving; sits under a scene without melody")
    out.append(p)

    p = F("GLITCH SPRAY", "DIGITAL", "ANALOG")
    p.osc(0, level=0.6, wt=0.5)
    p.osc(1, level=0.3, wt=1.0, fine=12)
    p.insert(1, "BITCRUSH", after=True, amount=0.5, mix=0.5)
    p.filter("LP24", hz=4000, res=0.2, keytrack=0.3)
    p.filter2("HP12", hz=200)
    p.env(1, a=0.001, d=1.0, s=1.0, r=0.2)
    one(p)
    p.performer(1, {0: gate_seq("x-xxx-x-xx-x-x-x"), 1: gate_seq("xx-x--xx-xxx-x--")}, mode="TRIG", rate="1/32")
    p.performer(2, {0: seq("abcdbadcabcdbadc", {"a": (0.0, "HOLD"), "b": (0.5, "HOLD"), "c": (-0.5, "HOLD"), "d": (1.0, "HOLD")})},
                mode="TRIG", rate="1/32")
    p.set("macro2", 0.6)
    p.motion("PERF1", "AMP", 0.9)
    p.motion("PERF2", "PITCH", 0.25)
    p.motion("PERF2", "INS1_AMOUNT", 0.3)
    p.tone("CUTOFF", 0.2)
    hall(p, mix=0.1)
    grit(p, mode="HARD", drive=0.4, tone=0.5, amount=0.35, base=0.2)
    p.context(unpitched=True)
    p.doc("A spray of glitches: pitch jumping by octaves in thirty-seconds, gated and crushed", "C3–C5",
          "Glitch, IDM, industrial, fills", "Short hits as fills; hold longer for chaos", "TRANSITION",
          "The pitch jumps are octaves of the note, so it still fits the key")
    out.append(p)

    p = F("HOLLOW WIND", "BASIC", "BASIC")
    p.osc(0, level=0.0, wt=0.0, on=False)
    p.noise(0.8, "PINK", color=0.5, keytrack=False)
    p.filter("FORMANT", cut=0.4, res=0.4, keytrack=0.0)
    p.filter2("HP12", hz=150)
    p.feedback(amount=0.12, drive=0.4, tone=0.6)
    p.env(1, a=1.0, d=1.0, s=1.0, r=2.0)
    one(p)
    p.lfo(1, "SMOOTH_RANDOM", hz=0.25, mode="FREE")
    p.lfo(2, "SMOOTH_RANDOM", hz=0.6, mode="FREE")
    p.set("macro2", 0.55)
    p.motion("LFO1", "CUTOFF", 0.35)
    p.motion("LFO2", "AMP", 0.3)
    p.tone("CUTOFF", 0.1)
    hall(p, mix=0.24)
    p.context(unpitched=True)
    p.doc("Wind moaning through a hollow structure, gusting on its own", "Any", "Film, horror, ambient, western-noir",
          "Hold under a scene", "TEXTURE", "No pitch, so it sits under any key")
    out.append(p)

    p = F("PRESSURE RELEASE", "BASIC", "BASIC")
    p.osc(0, level=0.0, wt=0.0, on=False)
    p.noise(0.8, "WHITE", color=0.3, keytrack=False)
    p.insert(1, "DECIMATE", after=True, amount=0.2, mix=0.4)
    p.filter2("HP12", hz=150)
    p.env(1, a=0.001, d=1.5, s=0.0, r=0.8, dcurve=-0.5)
    p.env(2, a=0.001, d=1.2, s=0.0, r=0.8)
    p.filter("LP24", hz=400, res=0.2, env=0.8)
    one(p)
    p.lfo(1, "SAMPLE_HOLD", sync="1/32", mode="FREE")
    p.set("macro2", 0.45)
    p.motion("LFO1", "INS1_AMOUNT", 0.3)
    p.motion("LFO1", "CUTOFF", 0.08)
    p.tone("CUTOFF", 0.1)
    hall(p, mix=0.16)
    grit(p, mode="HARD", drive=0.35, tone=0.5, amount=0.35, base=0.15)
    p.context(unpitched=True, allow_air=True)
    p.doc("A burst of air as a seal gives, the hiss falling away over a second", "Any", "Industrial, sci-fi, film, transitions",
          "One hit on a transition", "TRANSITION", "Bright at the start: great on a cut, too much on every bar")
    out.append(p)

    return out
