"""KEYS: played instruments that have been through something: burnt, taped,
detuned, crushed. They respond to touch and sit in a chord part."""

from lunatk import Preset
from bank2._common import grit, space, velocity


def K(name, a="GLASS", b="FM_BELL"):
    return Preset(name, "KEYS", a, b)


def poly(p, voices=10, vel=0.75):
    return p.voice(voices=voices, glide=0.0, vel=vel, bend=2)


def room(p, mix=0.16, decay=0.28, amount=0.15, width=0.7):
    return space(p, mix, mode="PLATE", size=0.45, decay=decay, damp=0.55, predelay=0.04, width=width, amount=amount)


def piano_body(p, decay=1.6, release=0.35, bright=0.45):
    """A struck-string shape: instant attack, long fall, filter closing with it."""
    p.env(1, a=0.001, d=decay, s=0.0, r=release, dcurve=-0.7)
    p.env(2, a=0.001, d=decay * 0.5, s=0.0, r=release)
    p.filter("LP12", hz=900, res=0.05, keytrack=0.6, env=bright)
    p.filter2("HP12", hz=110)
    return p


def presets():
    out = []

    p = K("BURNT PIANO", "GLASS", "FM_BELL")
    p.osc(0, level=0.6, wt=0.35)
    p.osc(1, level=0.3, wt=0.2, fine=6)
    p.noise(0.05, type="BREATH", color=0.6)
    p.insert(1, "COMB", amount=0.55, freq=0.5, mix=0.35)
    p.insert(2, "DECIMATE", after=True, amount=0.2, mix=0.35)
    piano_body(p)
    poly(p)
    velocity(p, 0.8, 0.25)
    p.tone("CUTOFF", 0.2)
    p.lfo(1, "SMOOTH_RANDOM", hz=0.8, mode="FREE")
    p.set("macro2", 0.3)
    p.motion("LFO1", "PITCH", 0.0015)
    p.motion("LFO1", "INS2_AMOUNT", 0.3)
    p.motion("LFO1", "CUTOFF", 0.06)
    p.context(motion_window=(0.02, 1.2))
    room(p)
    grit(p, mode="TUBE", drive=0.35, tone=0.45, amount=0.4, base=0.15)
    p.doc("A piano after a fire: strings ringing through a comb, sample rate a little broken, tuning a little loose",
          "C2–C6", "Film score, industrial ballads, dark pop", "Sparse chords and single-note lines", "FOREGROUND",
          "The wobble is under 4 cents; MOTION 0 for a steady piano against strings")
    out.append(p)

    p = K("FELT MEMORY", "GLASS", "BASIC")
    p.osc(0, level=0.6, wt=0.2)
    p.osc(1, level=0.35, wt=0.0, octave=1)
    p.noise(0.09, type="BREATH", color=0.7)
    p.insert(1, "COMB", amount=0.4, freq=0.5, mix=0.3)
    piano_body(p, decay=1.2, release=0.3, bright=0.3)
    p.filter("LP12", hz=650, res=0.05, keytrack=0.6, env=0.3)
    poly(p)
    velocity(p, 0.8, 0.25)
    p.tone("CUTOFF", 0.22)
    p.lfo(1, "SMOOTH_RANDOM", hz=0.6, mode="FREE")
    p.set("macro2", 0.25)
    p.motion("LFO1", "PITCH", 0.001)
    p.motion("LFO1", "CUTOFF", 0.1)
    p.context(motion_window=(0.02, 1.0))
    room(p, mix=0.2, decay=0.3)
    grit(p, mode="SOFT", drive=0.3, tone=0.4, amount=0.4, base=0.1)
    p.doc("A felted, close-miked piano: soft hammers, breathy, intimate", "C2–C6",
          "Film score, ambient, singer-songwriter, lo-fi", "Soft, slow chords; the breath is the hammer", "FOREGROUND",
          "Very dark: it wants to be up front and quiet, not buried")
    out.append(p)

    p = K("PRAYER BOX", "GLASS", "FM_BELL")
    p.osc(0, level=0.6, wt=0.7)
    p.osc(1, level=0.3, wt=0.5, octave=1)
    p.insert(1, "BITCRUSH", after=True, amount=0.45, mix=0.3)
    p.insert(2, "DECIMATE", after=True, amount=0.15, mix=0.4)
    p.env(1, a=0.001, d=1.2, s=0.0, r=0.6)
    p.filter("LP12", hz=4200, res=0.05, keytrack=0.2)
    p.filter2("HP12", hz=300)
    poly(p)
    velocity(p, 0.8, 0.15)
    p.tone("CUTOFF", 0.2)
    p.lfo(1, "SINE", hz=0.5, mode="FREE")
    p.set("macro2", 0.35)
    p.motion("LFO1", "PITCH", 0.002)
    room(p, mix=0.22, decay=0.32)
    p.eq(high=-6, high_hz=7000)
    p.context(shift=12)
    p.context(decays=True)
    p.doc("A music box played off a warped cassette: tines, crush and a slow wow", "C4–C7",
          "Film score, horror, lullaby-noir, lo-fi", "Simple high melodies and broken chords", "FOREGROUND",
          "Lives above 300 Hz; the wow is on MOTION")
    out.append(p)

    p = K("DEAD ROOM RHODES", "BASIC", "BASIC")
    p.osc(0, level=0.7, wt=0.0, warp="FM", warp_amt=0.12)
    p.osc(1, level=0.002, wt=0.0, octave=3)
    p.insert(1, "SINE", after=True, amount=0.15, mix=0.6)
    p.env(1, a=0.001, d=2.0, s=0.25, r=0.4)
    p.env(3, a=0.001, d=0.3, s=0.0, r=0.2)
    p.mod("ENV3", "A_WARP", 0.25)
    p.filter("LP12", hz=4000, res=0.05, keytrack=0.3)
    p.filter2("HP12", hz=100)
    poly(p)
    velocity(p, 0.8, 0.0)
    p.mod("VELOCITY", "INS1_AMOUNT", 0.35)
    p.mod("VELOCITY", "A_WARP", 0.15)
    p.tone("INS1_AMOUNT", 0.25)
    p.lfo(1, "SINE", hz=4.5, mode="FREE")
    p.set("macro2", 0.3)
    p.motion("LFO1", "AMP", 0.12)
    p.chorus(mode="SUBTLE", mix=0.3, rate=0.35, depth=0.5, width=0.6)
    room(p, mix=0.12)
    grit(p, mode="TUBE", drive=0.4, tone=0.5, amount=0.45, base=0.15)
    p.doc("An electric piano with a tine bark that growls when you dig in", "C2–C6",
          "Industrial ballads, trip-hop, neo-soul noir, film", "Chords with dynamics; hit harder for the bark", "FOREGROUND",
          "Tremolo is on MOTION; the bark is on velocity and TONE")
    out.append(p)

    p = K("SPLINTER CLAV", "PWM", "BASIC")
    p.osc(0, level=0.7, wt=0.75)
    p.insert(1, "COMB", amount=0.4, freq=0.75, mix=0.35)
    p.env(1, a=0.001, d=0.5, s=0.0, r=0.1)
    p.env(2, a=0.001, d=0.2, s=0.0, r=0.1)
    p.filter("BP", hz=900, res=0.3, keytrack=0.5, env=0.4)
    p.filter2("HP12", hz=150)
    poly(p, voices=8)
    velocity(p, 0.8, 0.25)
    p.tone("CUTOFF", 0.07)
    p.lfo(1, "TRIANGLE", sync="1/4", mode="FREE")
    p.set("macro2", 0.3)
    p.motion("LFO1", "CUTOFF", 0.1)
    room(p, mix=0.1)
    grit(p, mode="HARD", drive=0.45, tone=0.5, amount=0.45, base=0.3)
    p.doc("A distorted clavinet-style pluck with a woody comb ring", "C2–C5",
          "Industrial funk, EBM, electro, rock", "Short, choppy chords and riffs", "RHYTHM",
          "Choppy by nature: play it tight on the grid")
    out.append(p)

    p = K("WIRE HARPSICHORD", "ANALOG", "ANALOG")
    p.osc(0, level=0.6, wt=1.0)
    p.osc(1, level=0.35, wt=1.0, octave=1, fine=4)
    p.insert(1, "COMB", amount=0.6, freq=0.5, mix=0.4)
    p.insert(2, "BITCRUSH", after=True, amount=0.5, mix=0.2)
    p.env(1, a=0.001, d=0.9, s=0.0, r=0.2)
    p.env(2, a=0.001, d=0.25, s=0.0, r=0.1)
    p.filter("LP12", hz=1800, res=0.1, keytrack=0.6, env=0.35)
    p.filter2("HP12", hz=180)
    poly(p)
    velocity(p, 0.8, 0.2)
    p.tone("CUTOFF", 0.2)
    p.lfo(1, "SINE", hz=0.3, mode="FREE")
    p.set("macro2", 0.25)
    p.motion("LFO1", "INS1_FREQ", 0.01)
    p.motion("LFO1", "INS1_AMOUNT", 0.3)
    p.context(motion_window=(0.02, 0.9))
    room(p, mix=0.14)
    grit(p, mode="SOFT", drive=0.3, tone=0.5, amount=0.4, base=0.1)
    p.doc("A harpsichord strung with wire and slightly crushed", "C2–C6",
          "Gothic, darkwave, film, baroque-noir", "Arpeggiated chords by hand, counterpoint", "FOREGROUND",
          "Bright pluck: EQ a little 3 kHz down if it sits on top of a vocal")
    out.append(p)

    p = K("HOLLOW WURLI", "BASIC", "BASIC")
    p.osc(0, level=0.7, wt=0.33)
    p.insert(1, "SINE", after=True, amount=0.2, mix=0.6)
    p.insert(2, "DECIMATE", after=True, amount=0.12, mix=0.3)
    p.env(1, a=0.001, d=1.4, s=0.2, r=0.3)
    p.filter("LP12", hz=3500, res=0.05, keytrack=0.3)
    p.filter2("HP12", hz=120)
    poly(p)
    velocity(p, 0.8, 0.0)
    p.mod("VELOCITY", "INS1_AMOUNT", 0.4)
    p.tone("INS1_AMOUNT", 0.25)
    p.lfo(1, "SINE", hz=5.5, mode="FREE")
    p.set("macro2", 0.35)
    p.motion("LFO1", "AMP", 0.15)
    room(p, mix=0.12)
    grit(p, mode="TUBE", drive=0.4, tone=0.5, amount=0.45, base=0.15)
    p.doc("A reedy electric piano that buzzes when struck hard, with tremolo", "C2–C6",
          "Industrial ballads, trip-hop, indie", "Chords and riffs with dynamics", "FOREGROUND",
          "Soft playing stays round; the buzz arrives above about velocity 90")
    out.append(p)

    p = K("TOY OF GLASS", "FM_BELL", "GLASS")
    p.osc(0, level=0.6, wt=0.3)
    p.osc(1, level=0.3, wt=0.6, octave=1)
    p.insert(1, "RING", after=True, amount=0.4, freq=0.683, mix=0.15)
    p.insert(2, "DECIMATE", after=True, amount=0.18, mix=0.3)
    p.env(1, a=0.001, d=0.8, s=0.0, r=0.3)
    p.filter("LP12", hz=6000, res=0.05, keytrack=0.3)
    p.filter2("HP12", hz=300)
    poly(p)
    velocity(p, 0.8, 0.15)
    p.tone("CUTOFF", 0.2)
    p.lfo(1, "SINE", hz=0.4, mode="FREE")
    p.set("macro2", 0.25)
    p.motion("LFO1", "PITCH", 0.0015)
    room(p, mix=0.16)
    p.eq(high=-2, high_hz=9000)
    p.context(shift=12)
    p.doc("A toy piano with a faint inharmonic clang, a little out of tune", "C4–C7",
          "Film score, horror, indie, lullaby-noir", "Simple, high melodies", "FOREGROUND",
          "Childlike and wrong: great doubling a real piano an octave up")
    out.append(p)

    p = K("SCORCHED EP", "BASIC", "ANALOG")
    p.osc(0, level=0.65, wt=0.0, warp="FM", warp_amt=0.15)
    p.osc(1, level=0.002, wt=0.0, octave=2)
    p.insert(1, "SINE", after=True, amount=0.3, mix=0.5)
    p.env(1, a=0.001, d=1.8, s=0.3, r=0.35)
    p.env(3, a=0.001, d=0.35, s=0.0, r=0.2)
    p.mod("ENV3", "A_WARP", 0.2)
    p.filter("LP12", hz=2600, res=0.1, keytrack=0.4, drive=0.35)
    p.filter2("HP12", hz=110)
    poly(p)
    velocity(p, 0.8, 0.2)
    p.tone("CUTOFF", 0.2)
    p.lfo(1, "SMOOTH_RANDOM", hz=1.0, mode="FREE")
    p.set("macro2", 0.3)
    p.motion("LFO1", "PITCH", 0.0015)
    p.motion("LFO1", "CUTOFF", 0.05)
    p.chorus(mode="WIDE", mix=0.3, rate=0.3, depth=0.45, width=0.6)
    room(p, mix=0.12)
    grit(p, mode="TUBE", drive=0.55, tone=0.4, amount=0.4, base=0.4)
    p.doc("An electric piano pushed through a failing amp, on warped tape", "C2–C6",
          "Industrial rock, trip-hop, lo-fi, film", "Chords and simple riffs", "FOREGROUND",
          "Distortion is 40% by default: GRIT down for verses, up for choruses")
    out.append(p)

    p = K("NIGHT CELESTE", "GLASS", "GLASS")
    p.osc(0, level=0.6, wt=0.85)
    p.osc(1, level=0.3, wt=0.5, octave=1)
    p.insert(1, "SHIFT", after=True, amount=1.0, freq=0.515, mix=0.2)
    p.insert(2, "DECIMATE", after=True, amount=0.12, mix=0.25)
    p.env(1, a=0.001, d=1.5, s=0.0, r=0.8)
    p.filter("LP12", hz=1500, res=0.05, keytrack=1.0)
    p.filter2("HP12", hz=300)
    poly(p)
    velocity(p, 0.8, 0.15)
    p.tone("EQ_HIGH", 0.25)
    p.lfo(1, "SINE", sync="2 BAR", mode="FREE")
    p.set("macro2", 0.3)
    p.motion("LFO1", "INS1_FREQ", 0.02)
    room(p, mix=0.24, decay=0.33)
    p.eq(high=-6, high_hz=7000)
    p.context(shift=12)
    p.doc("Celeste bells with a faint shifted shimmer and a little crush", "C4–C7",
          "Film score, ambient, winter-noir", "High chords and arpeggios by hand", "TEXTURE",
          "Sparkles above 300 Hz: pair with a warm pad below")
    out.append(p)

    p = K("CRACKED UPRIGHT", "GLASS", "GLASS")
    p.osc(0, level=0.55, wt=0.4)
    p.osc(1, level=0.45, wt=0.4, fine=14)
    p.noise(0.07, type="CRACKLE", color=0.5, keytrack=False)
    p.insert(1, "COMB", amount=0.5, freq=0.5, mix=0.3)
    piano_body(p, decay=1.4, release=0.3, bright=0.45)
    poly(p)
    velocity(p, 0.8, 0.25)
    p.tone("CUTOFF", 0.2)
    p.lfo(1, "SAMPLE_HOLD", sync="1/4", mode="FREE")
    p.set("macro2", 0.25)
    p.motion("LFO1", "NOISE_LEVEL", 0.06)
    p.motion("LFO1", "CUTOFF", 0.08)
    p.context(motion_window=(0.02, 1.0))
    room(p, mix=0.14)
    grit(p, mode="SOFT", drive=0.3, tone=0.45, amount=0.4, base=0.15)
    p.doc("An out-of-tune bar-room upright on a crackling record", "C2–C6",
          "Film, lo-fi, blues-noir, industrial ballads", "Chords and melodies; the detune is honky-tonk", "FOREGROUND",
          "The 14-cent detune is the character; don't layer it with a tuned piano")
    out.append(p)

    p = K("ORGAN RUST", "ORGAN", "BASIC")
    p.osc(0, level=0.65, wt=0.4)
    p.insert(1, "RECTIFY", after=True, amount=0.4, mix=0.4)
    p.env(1, a=0.002, d=0.9, s=0.6, r=0.15)
    p.env(3, a=0.001, d=0.25, s=0.0, r=0.1)
    p.mod("ENV3", "A_WTPOS", 0.3)
    p.filter("LP12", hz=3500, res=0.05, keytrack=0.3, drive=0.35)
    p.filter2("HP12", hz=120)
    poly(p)
    velocity(p, 0.8, 0.2)
    p.tone("CUTOFF", 0.2)
    p.lfo(1, "SINE", hz=6.5, mode="FREE")
    p.set("macro2", 0.35)
    p.motion("LFO1", "PAN", 0.25)
    p.motion("LFO1", "AMP", 0.1)
    room(p, mix=0.12)
    grit(p, mode="TUBE", drive=0.45, tone=0.5, amount=0.4, base=0.3)
    p.doc("A percussive organ with a rusty rectified edge, spinning", "C2–C6",
          "Industrial, garage-noir, gothic", "Stabs and short chords", "RHYTHM",
          "The percussive click is on each note; play it staccato")
    out.append(p)

    p = K("BELL TOWER DUST", "FM_BELL", "FM_BELL")
    p.osc(0, level=0.6, wt=0.5)
    p.osc(1, level=0.3, wt=0.8, octave=-1, fine=-5)
    p.insert(1, "DECIMATE", after=True, amount=0.2, mix=0.3)
    p.env(1, a=0.001, d=2.2, s=0.0, r=0.8)
    p.filter("LP12", hz=4000, res=0.05, keytrack=0.3)
    p.filter2("HP12", hz=140)
    poly(p)
    velocity(p, 0.8, 0.15)
    p.tone("A_WTPOS", 0.2)
    p.lfo(1, "SINE", sync="2 BAR", mode="FREE")
    p.set("macro2", 0.3)
    p.motion("LFO1", "A_WTPOS", 0.15)
    room(p, mix=0.2, decay=0.32)
    grit(p, mode="SOFT", drive=0.3, tone=0.5, amount=0.35, base=0.15)
    p.doc("Low FM bells, slightly detuned against each other, dusty", "C2–C5",
          "Film score, gothic, ambient, horror", "Slow chords; let them ring", "FOREGROUND",
          "Long rings: leave space, or shorten with fewer notes")
    out.append(p)

    p = K("SHORTWAVE KEYS", "ANALOG", "GLASS")
    p.osc(0, level=0.6, wt=0.6)
    p.osc(1, level=0.3, wt=0.4, octave=1)
    p.noise(0.08, type="DIGITAL", color=0.5, keytrack=False)
    p.insert(1, "DECIMATE", after=True, amount=0.35, mix=0.5)
    p.env(1, a=0.001, d=1.2, s=0.3, r=0.3)
    p.filter("BP", hz=1500, res=0.25, keytrack=0.3)
    p.filter2("HP12", hz=300)
    poly(p)
    velocity(p, 0.8, 0.15)
    p.tone("CUTOFF", 0.08)
    p.lfo(1, "SMOOTH_RANDOM", hz=0.5, mode="FREE")
    p.set("macro2", 0.35)
    p.motion("LFO1", "CUTOFF", 0.08)
    p.motion("LFO1", "NOISE_LEVEL", 0.06)
    room(p, mix=0.1)
    grit(p, mode="DOWNSAMPLE", drive=0.3, tone=0.5, amount=0.4, base=0.15)
    p.doc("Keys heard on a shortwave radio that won't stay tuned", "C3–C6",
          "Trip-hop, hip-hop, film, industrial", "Chords and loops", "TEXTURE",
          "Band-passed: it never fights the bass or the air; sample it into a loop")
    out.append(p)

    p = K("BENT REED", "PWM", "FORMANT")
    p.osc(0, level=0.6, wt=0.5)
    p.osc(1, level=0.35, wt=0.6)
    p.noise(0.05, type="BREATH", color=0.5)
    p.env(1, a=0.02, d=1.2, s=0.7, r=0.3)
    p.filter("FORMANT", cut=0.45, res=0.25, keytrack=0.3)
    p.filter2("HP12", hz=150)
    poly(p)
    velocity(p, 0.8, 0.2)
    p.tone("CUTOFF", 0.12)
    p.lfo(1, "SMOOTH_RANDOM", hz=0.7, mode="FREE")
    p.set("macro2", 0.3)
    p.motion("LFO1", "PITCH", 0.002)
    room(p, mix=0.14)
    grit(p, mode="TUBE", drive=0.35, tone=0.5, amount=0.4, base=0.2)
    p.doc("A reed organ with a failing bellows: breathy, vowel-coloured, wavering", "C2–C6",
          "Gothic, folk-noir, film", "Held chords and hymns", "FOREGROUND",
          "Wavers a couple of cents; MOTION 0 to steady it")
    out.append(p)

    p = K("STEEL KEYS", "SPECTRAL_COMB", "BASIC")
    p.osc(0, level=0.6, wt=0.5)
    p.osc(1, level=0.3, wt=0.0, octave=1)
    p.insert(1, "RING", after=True, amount=0.3, freq=0.625, mix=0.3)
    p.insert(2, "COMB", after=True, amount=0.5, freq=0.75, mix=0.3)
    p.env(1, a=0.001, d=1.3, s=0.0, r=0.4)
    p.filter("LP12", hz=4500, res=0.05, keytrack=0.3)
    p.filter2("HP12", hz=150)
    poly(p)
    velocity(p, 0.8, 0.2)
    p.tone("A_WTPOS", 0.2)
    p.lfo(1, "TRIANGLE", sync="1 BAR", mode="FREE")
    p.set("macro2", 0.3)
    p.motion("LFO1", "A_WTPOS", 0.15)
    p.mod("MACRO2", "INS1_AMOUNT", 0.35)
    room(p, mix=0.14)
    grit(p, mode="SOFT", drive=0.3, tone=0.5, amount=0.35, base=0.1)
    p.context(decays=True)
    p.doc("Metallic keys: steel partials with a ring and a comb an octave up", "C2–C6",
          "Industrial, sci-fi, film", "Chords and ostinatos", "FOREGROUND",
          "Everything rings at octaves, so it stays in key")
    out.append(p)

    return out
