"""LEAD: voices that cut, tear and sing. Every one is mono or narrow, sits in
tune, and has its damage in the default sound."""

from lunatk import Preset
from bank2._common import accents, echo, grit, seq, space, velocity, vibrato


def L(name, a="ANALOG", b="BASIC"):
    return Preset(name, "LEAD", a, b)


def mono(p, glide=0.04, legato=True, bend=2, vel=0.4):
    return p.voice(voices=1, glide=glide, legato=legato, glide_always=False, vel=vel, bend=bend)


def presets():
    out = []

    p = L("SCREAMING WIRE", "ANALOG", "ANALOG")
    p.osc(0, level=0.7, wt=1.0)
    p.osc(1, level=0.35, wt=1.0, fine=8)
    p.insert(1, "FOLD", amount=0.25, mix=0.6)
    p.filter("LP24", hz=1400, res=0.45, keytrack=0.6, env=0.3)
    p.filter2("HP12", hz=180)
    p.feedback(amount=0.4, drive=0.8, tone=0.75)
    p.env(1, a=0.004, d=0.5, s=0.9, r=0.2)
    p.env(2, a=0.02, d=0.6, s=0.4, r=0.2)
    mono(p)
    velocity(p, 0.5, 0.15)
    vibrato(p)
    p.tone("CUTOFF", 0.2)
    p.lfo(1, "TRIANGLE", sync="1 BAR", mode="FREE")
    p.set("macro2", 0.45)
    p.motion("LFO1", "FEEDBACK", 0.25)
    p.motion("LFO1", "CUTOFF", 0.12)
    echo(p, time="3/16", mix=0.14, feedback=0.3, amount=0.14)
    space(p, 0.12, mode="PLATE", decay=0.3)
    grit(p, mode="TUBE", drive=0.5, tone=0.5, amount=0.45, base=0.3)
    p.doc("Saw lead through a resonant filter feeding back on itself: it screams as it opens", "C3–C5",
          "Industrial rock, noise, trailer, cyberpunk", "Held notes and slow melodies; mod wheel for vibrato", "FOREGROUND",
          "The scream lives at 2–4 kHz. Cut there on the guitars, not on this")
    out.append(p)

    p = L("TORN SIREN", "SYNC_SWEEP", "BASIC")
    p.osc(0, level=0.75, wt=0.3)
    p.insert(1, "RING", after=True, amount=0.5, freq=0.625, mix=0.35)
    p.filter("LP24", hz=4200, res=0.15, keytrack=0.4)
    p.filter2("HP12", hz=200)
    p.env(1, a=0.003, d=0.5, s=0.85, r=0.15)
    p.env(3, a=0.001, d=0.6, s=0.2, r=0.2)
    p.mod("ENV3", "A_WTPOS", 0.45)
    mono(p, glide=0.06)
    velocity(p, 0.5, 0.12)
    vibrato(p)
    p.tone("A_WTPOS", 0.2)
    p.lfo(1, "SINE", hz=0.35, mode="TRIG")
    p.set("macro2", 0.4)
    p.motion("LFO1", "A_WTPOS", 0.2)
    echo(p, time="1/8", mix=0.12, feedback=0.3, amount=0.12, pingpong=True)
    grit(p, mode="HARD", drive=0.45, tone=0.5, amount=0.4, base=0.3)
    p.doc("Hard-sync lead that rips on the attack, with a metal ring an octave up", "C3–C5",
          "Industrial, synthwave, electro, game", "Short phrases; every note rips", "FOREGROUND",
          "The rip is loud for a moment; a fast compressor on the lead evens it out")
    out.append(p)

    p = L("GLASS NERVE", "BASIC", "BASIC")
    p.osc(0, level=0.75, wt=0.0)
    p.insert(1, "RECTIFY", after=True, amount=0.55, mix=0.5)
    p.insert(2, "SHIFT", after=True, amount=1.0, freq=0.53, mix=0.25)
    p.filter("LP12", hz=6000, res=0.05, keytrack=0.3)
    p.filter2("HP12", hz=220)
    p.env(1, a=0.01, d=0.6, s=0.85, r=0.4)
    mono(p, glide=0.08)
    velocity(p, 0.8, 0.0)
    p.mod("VELOCITY", "INS1_AMOUNT", 0.3)
    vibrato(p, depth=0.008)
    p.tone("INS1_AMOUNT", 0.25)
    p.lfo(1, "SINE", sync="2 BAR", mode="FREE")
    p.set("macro2", 0.4)
    p.motion("LFO1", "INS2_FREQ", 0.03)
    p.motion("LFO1", "INS1_AMOUNT", 0.25)
    echo(p, time="3/16", mix=0.2, feedback=0.4, amount=0.15, pingpong=True)
    space(p, 0.2, mode="HALL", size=0.6, decay=0.3)
    p.doc("A pure sine that frays: a rectified octave edge and a copy shifted a few hertz off, beating slowly",
          "C4–C6", "Film score, ambient, trip-hop, industrial ballads", "Slow melodies with space between notes", "FOREGROUND",
          "Uneasy on purpose. MOTION 0 stops the drift; SPACE up for the score version")
    out.append(p)

    p = L("RUST HORN", "PWM", "FORMANT")
    p.osc(0, level=0.6, wt=0.3)
    p.osc(1, level=0.4, wt=0.5)
    p.noise(0.06, type="BREATH", color=0.5)
    p.filter("FORMANT", cut=0.45, res=0.3, keytrack=0.3, env=0.15, drive=0.3)
    p.filter2("HP12", hz=200)
    p.feedback(amount=0.2, drive=0.5, tone=0.6)
    p.env(1, a=0.03, d=0.5, s=0.85, r=0.2)
    p.env(2, a=0.06, d=0.5, s=0.4, r=0.2)
    mono(p)
    velocity(p, 0.8, 0.3)
    vibrato(p)
    p.tone("CUTOFF", 0.2)
    p.lfo(1, "TRIANGLE", hz=0.6, mode="TRIG", delay=0.2, rise=0.5)
    p.set("macro2", 0.4)
    p.motion("LFO1", "CUTOFF", 0.12)
    echo(p, time="1/4", mix=0.1, feedback=0.25, amount=0.12)
    space(p, 0.14, mode="HALL", decay=0.3)
    grit(p, mode="TUBE", drive=0.45, tone=0.5, amount=0.45, base=0.25)
    p.doc("A breathy, rusted brass voice that opens into a vowel as it holds", "C3–C5",
          "Industrial, darkwave, cinematic, doom", "Slow swells and held melodies", "FOREGROUND",
          "The vowel sits where a singer does: use it instead of a vocal line, or duck it under one")
    out.append(p)

    p = L("DEAD FREQUENCY", "ANALOG", "BASIC")
    p.osc(0, level=0.7, wt=0.8)
    p.noise(0.1, type="CRACKLE", color=0.4, keytrack=False)
    p.insert(1, "DECIMATE", amount=0.35, mix=0.6)
    p.filter("BP", hz=1600, res=0.35, keytrack=0.3)
    p.filter2("HP12", hz=300)
    p.env(1, a=0.005, d=0.5, s=0.85, r=0.2)
    mono(p)
    velocity(p, 0.5, 0.12)
    vibrato(p)
    p.tone("CUTOFF", 0.08)
    p.lfo(1, "SAMPLE_HOLD", sync="1/8", mode="FREE")
    p.set("macro2", 0.4)
    p.motion("LFO1", "CUTOFF", 0.1)
    p.motion("LFO1", "NOISE_LEVEL", 0.08)
    echo(p, time="3/16", mix=0.14, feedback=0.35, amount=0.12)
    grit(p, mode="DOWNSAMPLE", drive=0.35, tone=0.5, amount=0.45, base=0.15)
    p.doc("A lead through a broken radio: band-passed, crushed, with static that jumps in time", "C3–C5",
          "Industrial, trip-hop, hip-hop, horror", "Short melodic hooks", "FOREGROUND",
          "Band-passed, so it never clouds the lows; push it louder than you think")
    out.append(p)

    p = L("HOLLOW CRY", "FM_BELL", "GLASS")
    p.osc(0, level=0.7, wt=0.3)
    p.osc(1, level=0.25, wt=0.3, octave=1)
    p.noise(0.05, type="BREATH", color=0.5)
    p.insert(1, "COMB", after=True, amount=0.55, freq=0.5, mix=0.5)
    p.filter("LP12", hz=5000, res=0.05, keytrack=0.3)
    p.filter2("HP12", hz=220)
    p.env(1, a=0.02, d=0.8, s=0.7, r=0.5)
    mono(p, glide=0.12, bend=12)
    velocity(p, 0.5, 0.1)
    vibrato(p, depth=0.01, delay=0.5)
    p.tone("A_WTPOS", 0.2)
    p.lfo(1, "SINE", hz=0.25, mode="TRIG")
    p.set("macro2", 0.4)
    p.motion("LFO1", "A_WTPOS", 0.2)
    p.motion("LFO1", "INS1_AMOUNT", 0.15)
    echo(p, time="1/4", mix=0.16, feedback=0.3, amount=0.12, pingpong=True)
    space(p, 0.18, mode="HALL", size=0.6, decay=0.27)
    p.doc("A mournful FM voice with a tuned comb ringing inside it; long glides", "C4–C6",
          "Film score, dark ambient, ballads", "Slow legato lines; bend is an octave", "FOREGROUND",
          "Long echoes: shorten SPACE when the melody gets busy")
    out.append(p)

    p = L("MACHINE WHINE", "BASIC", "BASIC")
    p.osc(0, level=0.75, wt=1.0)
    p.insert(1, "RING", after=True, amount=0.55, freq=0.573, mix=0.3)
    p.filter("LP24", hz=2800, res=0.25, keytrack=0.5, env=0.2)
    p.filter2("HP12", hz=220)
    p.env(1, a=0.004, d=0.5, s=0.9, r=0.15)
    p.env(2, a=0.001, d=0.3, s=0.4, r=0.1)
    mono(p)
    velocity(p, 0.5, 0.15)
    vibrato(p)
    p.tone("CUTOFF", 0.2)
    p.lfo(1, "TRIANGLE", sync="1/2", mode="FREE")
    p.set("macro2", 0.4)
    p.motion("LFO1", "INS1_AMOUNT", 0.5)
    echo(p, time="1/8", mix=0.1, feedback=0.3, amount=0.12)
    grit(p, mode="HARD", drive=0.45, tone=0.5, amount=0.45, base=0.3)
    p.doc("Square lead ring-modulated a fifth up: a whine with a ghost an octave below", "C3–C5",
          "Industrial, EBM, electro", "Riffs and hooks", "FOREGROUND",
          "The ring's low ghost can clash with the bass on long notes; keep it above C3")
    out.append(p)

    p = L("OVERLOAD", "ANALOG", "ANALOG")
    p.osc(0, level=0.65, wt=1.0, unison=5, detune=0.18, width=0.25)
    p.osc(1, level=0.35, wt=0.9, octave=-1)
    p.filter("LP24", hz=2200, res=0.2, keytrack=0.5, env=0.2, drive=0.45)
    p.filter2("HP12", hz=180)
    p.feedback(amount=0.15, drive=0.6, tone=0.6)
    p.env(1, a=0.004, d=0.5, s=0.9, r=0.15)
    mono(p)
    velocity(p, 0.5, 0.12)
    vibrato(p)
    p.tone("CUTOFF", 0.2)
    p.lfo(1, "SINE", sync="1 BAR", mode="FREE")
    p.set("macro2", 0.35)
    p.motion("LFO1", "CUTOFF", 0.12)
    p.motion("LFO1", "A_DETUNE", 0.15)
    echo(p, time="3/16", mix=0.12, feedback=0.3, amount=0.12)
    grit(p, mode="TUBE", drive=0.55, tone=0.5, amount=0.4, base=0.45)
    p.doc("A wall of driven saws with the octave below: a lead that behaves like a guitar", "C3–C5",
          "Industrial rock, metal, trailer", "Power-chord style riffs, one note at a time", "FOREGROUND",
          "Pan it opposite a guitar; its narrow width keeps it solid in mono")
    out.append(p)

    p = L("DEAD CHANNEL", "BASIC", "BASIC")
    p.osc(0, level=0.25, wt=0.0)
    p.noise(0.6, type="WHITE", color=0.3)
    p.insert(1, "COMB", amount=0.97, freq=0.5, mix=1.0)
    p.filter("BP", hz=2000, res=0.1, keytrack=0.4)
    p.feedback(amount=0.25, drive=0.4, tone=0.8)
    p.env(1, a=0.02, d=0.6, s=0.85, r=0.3)
    mono(p, glide=0.05)
    velocity(p, 0.5, 0.1)
    vibrato(p)
    p.tone("CUTOFF", 0.1)
    p.lfo(1, "SMOOTH_RANDOM", hz=1.5, mode="TRIG")
    p.set("macro2", 0.4)
    p.motion("LFO1", "NOISE_COLOR", 0.2)
    p.motion("LFO1", "CUTOFF", 0.08)
    echo(p, time="3/16", mix=0.18, feedback=0.4, amount=0.14, pingpong=True)
    space(p, 0.18, mode="HALL", decay=0.3)
    p.context(allow_air=True)
    p.doc("A whistle made of noise: a comb tuned to the note, singing through static", "C4–C6",
          "Dark ambient, film, industrial, experimental", "Slow melodies", "FOREGROUND",
          "Airy by nature; a low-pass at 9 kHz keeps it off the hats")
    out.append(p)

    p = L("SPLIT LIP", "BASIC", "ANALOG")
    p.osc(0, level=0.6, wt=0.66)
    p.osc(1, level=0.4, wt=1.0, fine=6)
    p.insert(1, "FOLD", amount=0.3, mix=0.8)
    p.filter("LP24", hz=2600, res=0.2, keytrack=0.5)
    p.filter2("HP12", hz=200)
    p.env(1, a=0.003, d=0.5, s=0.9, r=0.12)
    mono(p)
    velocity(p, 0.5, 0.12)
    vibrato(p)
    p.tone("INS1_AMOUNT", 0.25)
    p.performer(1, {0: accents("X--x--X--x--X-x-", "DECAY"), 1: accents("X-x-X-x-X-x-XxXx", "DECAY")}, rate="1/16")
    p.set("macro2", 0.5)
    p.motion("PERF1", "INS1_AMOUNT", 0.5)
    echo(p, time="1/8", mix=0.1, feedback=0.3, amount=0.12)
    grit(p, mode="HARD", drive=0.45, tone=0.5, amount=0.4, base=0.25)
    p.doc("A folded lead whose snarl pulses in a dotted rhythm on the bar", "C3–C5",
          "Industrial, EBM, cyberpunk", "Held notes; the rhythm is built in", "RHYTHM",
          "Pattern B is straight sixteenths; MOTION 0 is a steady fold")
    out.append(p)

    p = L("SCAR TISSUE", "BASIC", "BASIC")
    p.osc(0, level=0.8, wt=0.0)
    p.insert(1, "SINE", amount=0.6, mix=1.0)
    p.insert(2, "BITCRUSH", after=True, amount=0.4, mix=0.3)
    p.filter("LP12", hz=5000, res=0.05, keytrack=0.3)
    p.filter2("HP12", hz=200)
    p.env(1, a=0.003, d=0.7, s=0.8, r=0.3)
    p.env(3, a=0.001, d=0.4, s=0.2, r=0.2)
    p.mod("ENV3", "INS1_AMOUNT", 0.35)
    mono(p)
    velocity(p, 0.5, 0.0)
    p.mod("VELOCITY", "INS1_AMOUNT", 0.25)
    vibrato(p)
    p.tone("INS1_AMOUNT", 0.25)
    p.lfo(1, "SINE", hz=0.3, mode="TRIG")
    p.set("macro2", 0.35)
    p.motion("LFO1", "INS1_AMOUNT", 0.2)
    echo(p, time="3/16", mix=0.14, feedback=0.35, amount=0.12)
    space(p, 0.14, mode="PLATE", decay=0.3)
    p.doc("A sine driven through a wavefolding sine shaper: bright bell-like attack, purer tail, a little crushed",
          "C3–C5", "Industrial pop, film, electro", "Melodies with space; velocity sets the brightness", "FOREGROUND",
          "Plays softer than it looks: hit harder for the edge")
    out.append(p)

    p = L("CATHODE", "DIGITAL", "ANALOG")
    p.osc(0, level=0.65, wt=0.45)
    p.osc(1, level=0.3, wt=1.0, octave=1)
    p.insert(1, "BITCRUSH", after=True, amount=0.55, mix=0.5)
    p.filter("LP24", hz=3500, res=0.2, keytrack=0.4, env=0.2)
    p.filter2("HP12", hz=220)
    p.env(1, a=0.003, d=0.4, s=0.85, r=0.15)
    p.env(2, a=0.001, d=0.3, s=0.3, r=0.1)
    mono(p)
    velocity(p, 0.5, 0.15)
    vibrato(p)
    p.tone("CUTOFF", 0.2)
    p.lfo(1, "TRIANGLE", sync="1 BAR", mode="FREE")
    p.set("macro2", 0.4)
    p.motion("LFO1", "A_WTPOS", 0.3)
    p.motion("LFO1", "CUTOFF", 0.18)
    p.motion("LFO1", "INS1_AMOUNT", 0.2)
    echo(p, time="1/8", mix=0.14, feedback=0.35, amount=0.12, pingpong=True)
    grit(p, mode="BITCRUSH", drive=0.35, tone=0.5, amount=0.45, base=0.2)
    p.doc("A digital lead with stepped, crushed edges that sweep across the bar", "C3–C5",
          "Industrial, chiptune-noir, EBM, game", "Riffs and arps played by hand", "FOREGROUND",
          "The crush makes 5–8 kHz grain; a shelf down there tames it on headphones")
    out.append(p)

    p = L("BLEED", "SYNC_SWEEP", "ANALOG")
    p.osc(0, level=0.7, wt=0.5)
    p.filter("LP24", hz=2200, res=0.35, keytrack=0.5, env=0.2)
    p.filter2("HP12", hz=200)
    p.feedback(amount=0.12, drive=0.6, tone=0.7)
    p.env(1, a=0.004, d=0.5, s=0.9, r=0.15)
    p.voice(voices=1, glide=0.1, legato=True, glide_always=True, vel=0.4, bend=7)
    velocity(p, 0.5, 0.12)
    p.mod("MODWHEEL", "FEEDBACK", 0.5)
    p.tone("A_WTPOS", 0.2)
    p.lfo(1, "SINE", hz=0.4, mode="TRIG")
    p.set("macro2", 0.4)
    p.motion("LFO1", "A_WTPOS", 0.2)
    echo(p, time="3/16", mix=0.12, feedback=0.3, amount=0.12)
    grit(p, mode="TUBE", drive=0.5, tone=0.5, amount=0.45, base=0.3)
    p.doc("A sliding sync lead; the mod wheel pushes its filter into feedback", "C3–C5",
          "Industrial, synthwave, film", "Legato lines; wheel up for the climax", "FOREGROUND",
          "Wheel all the way is harsh on purpose: ride it, don't park it there")
    out.append(p)

    p = L("FILAMENT", "PWM", "BASIC")
    p.osc(0, level=0.75, wt=0.75)
    p.filter("PHASER", cut=0.55, res=0.4, keytrack=0.4)
    p.filter2("HP12", hz=350)
    p.feedback(amount=0.2, drive=0.4, tone=0.85)
    p.env(1, a=0.004, d=0.5, s=0.85, r=0.2)
    mono(p)
    velocity(p, 0.5, 0.12)
    vibrato(p)
    p.tone("CUTOFF", 0.2)
    p.lfo(1, "SINE", sync="2 BAR", mode="FREE")
    p.set("macro2", 0.45)
    p.motion("LFO1", "CUTOFF", 0.18)
    echo(p, time="3/16", mix=0.12, feedback=0.3, amount=0.12, pingpong=True)
    grit(p, mode="SOFT", drive=0.4, tone=0.55, amount=0.4, base=0.15)
    p.doc("A thin, nasal pulse lead phasing through a feedback filter", "C4–C6",
          "Industrial, post-punk, darkwave", "Counter-melodies over a busy track", "SUPPORT",
          "Thin on purpose: it sits above everything without taking space")
    out.append(p)

    p = L("SHATTERED GLIDE", "ANALOG", "BASIC")
    p.osc(0, level=0.75, wt=0.9)
    p.insert(1, "SHIFT", after=True, amount=1.0, freq=0.515, mix=0.35)
    p.insert(2, "DECIMATE", after=True, amount=0.25, mix=0.35)
    p.filter("LP24", hz=2600, res=0.2, keytrack=0.5, env=0.2)
    p.filter2("HP12", hz=200)
    p.env(1, a=0.005, d=0.5, s=0.9, r=0.2)
    p.voice(voices=1, glide=0.15, legato=True, glide_always=False, vel=0.4, bend=12)
    velocity(p, 0.5, 0.12)
    vibrato(p)
    p.tone("CUTOFF", 0.2)
    p.lfo(1, "SMOOTH_RANDOM", hz=0.8, mode="TRIG")
    p.set("macro2", 0.4)
    p.motion("LFO1", "INS1_FREQ", 0.015)
    p.motion("LFO1", "INS2_AMOUNT", 0.2)
    echo(p, time="1/4", mix=0.14, feedback=0.26, amount=0.12)
    space(p, 0.14, mode="HALL", decay=0.3)
    grit(p, mode="SOFT", drive=0.4, tone=0.5, amount=0.4, base=0.15)
    p.doc("A saw lead whose shimmering, shifted double drifts in and out of tune with it", "C3–C5",
          "Film, industrial ballads, ambient", "Slow legato phrases with long glides", "FOREGROUND",
          "The drift is a couple of hertz; MOTION 0 holds the double still")
    out.append(p)

    p = L("TENSION CABLE", "GLASS", "ANALOG")
    p.osc(0, level=0.6, wt=0.5)
    p.osc(1, level=0.35, wt=1.0, fine=-7)
    p.noise(0.05, type="METAL", color=0.3)
    p.insert(1, "COMB", after=True, amount=0.6, freq=0.75, mix=0.4)
    p.filter("LP24", hz=3000, res=0.15, keytrack=0.4, env=0.2)
    p.filter2("HP12", hz=250)
    p.env(1, a=0.35, d=1.0, s=0.9, r=0.5)
    p.env(2, a=0.5, d=1.0, s=0.5, r=0.4)
    mono(p, glide=0.08)
    velocity(p, 0.45, 0.1)
    vibrato(p, delay=0.8)
    p.tone("CUTOFF", 0.2)
    p.lfo(1, "SINE", sync="1 BAR", mode="FREE")
    p.set("macro2", 0.4)
    p.motion("LFO1", "INS1_AMOUNT", 0.35)
    p.motion("LFO1", "CUTOFF", 0.12)
    echo(p, time="1/4", mix=0.14, feedback=0.3, amount=0.12)
    space(p, 0.16, mode="HALL", size=0.6, decay=0.27)
    p.doc("A slow, bowed metal voice that swells in with a ringing comb an octave up", "C3–C5",
          "Film score, horror, ambient", "Long notes that swell; let each one bloom", "FOREGROUND",
          "Slow attack: play early, or it lands late")
    out.append(p)

    p = L("ALARM ROOM", "PWM", "BASIC")
    p.osc(0, level=0.75, wt=0.1)
    p.insert(1, "RING", after=True, amount=0.4, freq=0.5625, mix=0.25)
    p.filter("BP", hz=1800, res=0.3, keytrack=0.4)
    p.filter2("HP12", hz=250)
    p.env(1, a=0.003, d=0.4, s=0.85, r=0.12)
    mono(p)
    velocity(p, 0.5, 0.12)
    vibrato(p)
    p.tone("CUTOFF", 0.08)
    p.lfo(1, "SQUARE", sync="1/8", mode="FREE")
    p.set("macro2", 0.35)
    p.motion("LFO1", "INS1_AMOUNT", 0.25)
    echo(p, time="3/16", mix=0.14, feedback=0.35, amount=0.12, pingpong=True)
    grit(p, mode="HARD", drive=0.45, tone=0.5, amount=0.4, base=0.25)
    p.doc("A square alarm whose tritone ring switches on and off in eighths", "C4–C6",
          "Industrial, horror, techno", "Short, repeated figures", "FOREGROUND",
          "Dissonant by design: keep it to stabs and hooks, not the main melody")
    out.append(p)

    p = L("SPINE CRAWL", "GROWL", "ANALOG")
    p.osc(0, level=0.7, wt=0.35)
    p.osc(1, level=0.3, wt=1.0, octave=-1)
    p.filter("LP24", hz=1800, res=0.3, keytrack=0.5, env=0.2, drive=0.35)
    p.filter2("HP12", hz=200)
    p.env(1, a=0.004, d=0.5, s=0.9, r=0.15)
    mono(p)
    velocity(p, 0.5, 0.12)
    vibrato(p)
    p.tone("CUTOFF", 0.2)
    p.performer(1, {0: seq("aabbccddaabbccdd", {"a": (-0.6, "GLIDE"), "b": (0.2, "GLIDE"), "c": (0.8, "GLIDE"), "d": (0.0, "GLIDE")})},
                rate="1/16")
    p.set("macro2", 0.5)
    p.motion("PERF1", "A_WTPOS", 0.4)
    p.motion("PERF1", "CUTOFF", 0.15)
    echo(p, time="1/8", mix=0.1, feedback=0.3, amount=0.12)
    grit(p, mode="TUBE", drive=0.5, tone=0.5, amount=0.4, base=0.3)
    p.doc("A growling lead whose throat crawls through four shapes every half bar", "C3–C5",
          "Industrial, bass music, EBM", "Held notes; the growl moves in time", "FOREGROUND",
          "Mid-heavy growl: give it the space between vocal phrases")
    out.append(p)

    return out
