"""PAD: beds that are never still and never clean: drifting, degraded,
beautiful with damage. Lows stay clear so they sit over a bass."""

from lunatk import Preset
from bank2._common import grit, seq, space, velocity


def P(name, a="ANALOG", b="ANALOG"):
    return Preset(name, "PAD", a, b)


def bed(p, voices=8, vel=0.3):
    return p.voice(voices=voices, glide=0.0, vel=vel, bend=2)


def hall(p, mix=0.24, decay=0.36, size=0.65, amount=0.18, width=0.9):
    return space(p, mix, mode="HALL", size=size, decay=decay, damp=0.55, predelay=0.12, width=width, amount=amount)


def presets():
    out = []

    p = P("ASH CATHEDRAL", "CHOIR", "ANALOG")
    p.osc(0, level=0.65, wt=0.4, unison=3, detune=0.12, width=0.6)
    p.osc(1, level=0.35, wt=0.8, octave=-1)
    p.insert(1, "SHIFT", after=True, amount=1.0, freq=0.515, mix=0.3)
    p.filter("LP24", hz=2600, res=0.1, keytrack=0.3)
    p.filter2("HP24", hz=190)
    p.env(1, a=0.6, d=1.5, s=0.9, r=1.2)
    bed(p)
    velocity(p, 0.3, 0.05)
    p.tone("CUTOFF", 0.18)
    p.lfo(1, "SINE", sync="4 BAR", mode="FREE")
    p.set("macro2", 0.45)
    p.motion("LFO1", "INS1_FREQ", 0.02)
    p.motion("LFO1", "A_WTPOS", 0.25)
    p.chorus(mode="DEEP", mix=0.4, rate=0.3, depth=0.5, width=0.45)
    hall(p)
    grit(p, mode="SOFT", drive=0.3, tone=0.5, amount=0.35, base=0.15)
    p.doc("A choir with a shifted ghost of itself drifting in and out of tune, in a large hall", "C3–C5",
          "Film score, dark ambient, industrial ballads", "Slow chords, two bars or more", "TEXTURE",
          "The ghost beats slowly against the choir; MOTION 0 holds it still if a vocal needs a steady bed")
    out.append(p)

    p = P("NERVE FIELD", "ANALOG", "ANALOG")
    p.osc(0, level=0.6, wt=1.0, unison=7, detune=0.2, width=0.8)
    p.osc(1, level=0.3, wt=0.9, octave=1, unison=3, detune=0.15, width=0.6)
    p.insert(1, "BITCRUSH", after=True, amount=0.55, mix=0.22)
    p.filter("LP24", hz=1800, res=0.2, keytrack=0.3, drive=0.3)
    p.filter2("HP12", hz=170)
    p.feedback(amount=0.15, drive=0.5, tone=0.6)
    p.env(1, a=0.4, d=1.2, s=0.9, r=1.0)
    bed(p)
    velocity(p, 0.3, 0.05)
    p.tone("CUTOFF", 0.2)
    p.performer(1, {0: seq("aaaaaaaabbbbbbbb", {"a": (-0.6, "GLIDE"), "b": (0.7, "GLIDE")})}, rate="1/8")
    p.set("macro2", 0.5)
    p.motion("PERF1", "CUTOFF", 0.45)
    hall(p, mix=0.2)
    grit(p, mode="TUBE", drive=0.4, tone=0.5, amount=0.4, base=0.2)
    p.doc("A wide supersaw bed, lightly crushed, opening and closing over two bars on the grid", "C3–C5",
          "Industrial rock, trailer, synthwave, darkwave", "Sustained chords under a band", "SUPPORT",
          "The crush is 22%: it adds grain, not noise. Start chords on the bar so the sweep lines up")
    out.append(p)

    p = P("RUSTED HYMN", "ORGAN", "ORGAN")
    p.osc(0, level=0.65, wt=0.5)
    p.osc(1, level=0.3, wt=0.8, octave=1, fine=5)
    p.insert(1, "DECIMATE", after=True, amount=0.3, mix=0.4)
    p.filter("LP12", hz=3200, res=0.05, keytrack=0.3)
    p.filter2("HP12", hz=170)
    p.env(1, a=0.15, d=1.0, s=0.9, r=0.8)
    bed(p)
    velocity(p, 0.3, 0.05)
    p.tone("CUTOFF", 0.18)
    p.lfo(1, "SMOOTH_RANDOM", hz=0.7, mode="TRIG")
    p.lfo(2, "SINE", hz=5.5, mode="FREE")
    p.set("macro2", 0.4)
    p.motion("LFO1", "A_FINE", 0.08)
    p.motion("LFO1", "B_FINE", 0.08)
    p.motion("LFO2", "AMP", 0.12)
    p.chorus(mode="WIDE", mix=0.35, rate=0.35, depth=0.5, width=0.8)
    hall(p, mix=0.22, decay=0.33)
    grit(p, mode="TUBE", drive=0.4, tone=0.5, amount=0.4, base=0.2)
    p.doc("An organ played back from a damaged tape: crushed, wavering and trembling", "C3–C5",
          "Film score, lo-fi, industrial ballads, horror", "Hymn-like chords", "SUPPORT",
          "The wow is a few cents; pull MOTION down against pianos and guitars")
    out.append(p)

    p = P("SICK LIGHT", "GLASS", "BASIC")
    p.osc(0, level=0.6, wt=0.4, unison=3, detune=0.1, width=0.6)
    p.osc(1, level=0.35, wt=0.0, octave=-1)
    p.insert(1, "RING", after=True, amount=0.5, freq=0.573, mix=0.2)
    p.insert(2, "SHIFT", after=True, amount=1.0, freq=0.52, mix=0.25)
    p.filter("LP12", hz=4000, res=0.05, keytrack=0.3)
    p.filter2("HP12", hz=200)
    p.env(1, a=0.8, d=1.5, s=0.9, r=1.2)
    bed(p)
    velocity(p, 0.3, 0.05)
    p.tone("CUTOFF", 0.18)
    p.lfo(1, "SINE", sync="2 BAR", mode="FREE")
    p.set("macro2", 0.45)
    p.motion("LFO1", "INS1_AMOUNT", 0.3)
    p.motion("LFO1", "INS2_FREQ", 0.02)
    hall(p, mix=0.26)
    grit(p, mode="SOFT", drive=0.3, tone=0.5, amount=0.35, base=0.1)
    p.doc("Glass with a faint ring a fifth up and a drifting shifted copy: pretty, and slightly wrong", "C3–C5",
          "Film score, horror, ambient", "Slow chords; long releases", "TEXTURE",
          "Unsettling in a minor key, sweet in a major one; MOTION rides the wrongness")
    out.append(p)

    p = P("PRESSURE FRONT", "ANALOG", "PWM")
    p.osc(0, level=0.6, wt=0.95, unison=5, detune=0.15, width=0.7)
    p.osc(1, level=0.35, wt=0.3, unison=3, detune=0.12, width=0.6)
    p.filter("LP24", hz=900, res=0.22, keytrack=0.3, env=0.35, drive=0.4)
    p.filter2("HP12", hz=170)
    p.feedback(amount=0.14, drive=0.5, tone=0.6)
    p.env(1, a=0.5, d=1.5, s=0.9, r=1.0)
    p.env(2, a=2.5, d=2.0, s=0.6, r=1.0)
    bed(p)
    velocity(p, 0.3, 0.08)
    p.tone("CUTOFF", 0.2)
    p.lfo(1, "TRIANGLE", sync="4 BAR", mode="FREE")
    p.set("macro2", 0.45)
    p.motion("LFO1", "FB_TONE", 0.25)
    p.motion("LFO1", "CUTOFF", 0.12)
    hall(p, mix=0.2)
    grit(p, mode="TUBE", drive=0.45, tone=0.5, amount=0.4, base=0.2)
    p.doc("A swelling analog bed with a resonant filter feeding back as it opens", "C3–C5",
          "Trailer, industrial, dark techno breakdowns", "Chords held for bars; the swell takes 3 seconds", "SUPPORT",
          "The feedback peak moves over four bars; if it whistles in your key, pull TONE down")
    out.append(p)

    p = P("BURIED CHOIR", "CHOIR", "FORMANT")
    p.osc(0, level=0.6, wt=0.6, unison=3, detune=0.1, width=0.6)
    p.osc(1, level=0.35, wt=0.3, unison=2, detune=0.08, width=0.5)
    p.noise(0.06, type="BREATH", color=0.6)
    p.insert(1, "COMB", after=True, amount=0.45, freq=0.25, mix=0.3)
    p.filter("FORMANT", cut=0.4, res=0.25, keytrack=0.2)
    p.filter2("LP12", hz=2400)
    p.env(1, a=0.7, d=1.5, s=0.9, r=1.2)
    bed(p)
    velocity(p, 0.3, 0.05)
    p.tone("CUTOFF", 0.2)
    p.lfo(1, "TRIANGLE", sync="4 BAR", mode="FREE")
    p.set("macro2", 0.45)
    p.motion("LFO1", "CUTOFF", 0.35)
    p.motion("LFO1", "A_WTPOS", 0.25)
    hall(p, mix=0.26)
    grit(p, mode="SOFT", drive=0.3, tone=0.5, amount=0.35, base=0.1)
    p.doc("Voices under the floor: breathy, vowel-shaped, with a hollow comb an octave down", "C3–C5",
          "Horror, dark ambient, film score, doom", "Slow minor chords", "TEXTURE",
          "Muffled on purpose; TONE up to bring it out of the ground")
    out.append(p)

    p = P("GHOST STATIC", "ANALOG", "GLASS")
    p.osc(0, level=0.55, wt=0.6, unison=3, detune=0.12, width=0.6)
    p.osc(1, level=0.35, wt=0.4, octave=1)
    p.noise(0.12, type="VINYL", color=0.5, keytrack=False)
    p.insert(1, "BITCRUSH", after=True, amount=0.6, mix=0.25)
    p.filter("LP12", hz=3000, res=0.1, keytrack=0.3)
    p.filter2("HP12", hz=200)
    p.env(1, a=0.5, d=1.5, s=0.9, r=1.0)
    bed(p)
    velocity(p, 0.3, 0.05)
    p.tone("CUTOFF", 0.2)
    p.lfo(1, "SAMPLE_HOLD", sync="1/4", mode="FREE")
    p.lfo(2, "SINE", sync="2 BAR", mode="FREE")
    p.set("macro2", 0.4)
    p.motion("LFO1", "NOISE_LEVEL", 0.08)
    p.motion("LFO2", "CUTOFF", 0.15)
    hall(p, mix=0.2)
    grit(p, mode="SOFT", drive=0.3, tone=0.5, amount=0.35, base=0.1)
    p.doc("A soft pad heard through a worn record: crackle, crush and a slow filter", "C3–C5",
          "Lo-fi, trip-hop, film, industrial ballads", "Chords under vocals", "SUPPORT",
          "The crackle is on its own layer; MOTION makes it breathe on the beat")
    out.append(p)

    p = P("FALSE DAWN", "HARMONIC_SWEEP", "ANALOG")
    p.osc(0, level=0.6, wt=0.5, unison=5, detune=0.14, width=0.3)
    p.osc(1, level=0.3, wt=0.8, octave=-1)
    p.insert(1, "SINE", after=True, amount=0.2, mix=0.5)
    p.filter("LP24", hz=3000, res=0.1, keytrack=0.3)
    p.filter2("HP24", hz=190)
    p.env(1, a=1.0, d=2.0, s=0.9, r=1.2)
    bed(p)
    velocity(p, 0.3, 0.05)
    p.tone("A_WTPOS", 0.2)
    p.performer(1, {0: [(-1.0 + 2.0 * i / 15, "GLIDE") for i in range(16)]},
                rate="1/4")
    p.set("macro2", 0.5)
    p.motion("PERF1", "A_WTPOS", 0.6)
    p.motion("PERF1", "CUTOFF", 0.15)
    p.chorus(mode="WIDE", mix=0.3, rate=0.3, depth=0.1, width=0.45)
    p.mod("MACRO2", "CHORUS_DEPTH", 0.6)
    hall(p, mix=0.24, width=0.45)
    grit(p, mode="SOFT", drive=0.3, tone=0.5, amount=0.35, base=0.15)
    p.doc("Harmonics climbing for four bars, then falling back: a sunrise that never quite arrives", "C3–C5",
          "Film score, post-rock, ambient, trailer builds", "Chords held through four-bar phrases, starting on the bar", "TEXTURE",
          "The climb resets every four bars on the song grid; MOTION 0 freezes the colour")
    out.append(p)

    p = P("COLD ENGINE", "PWM", "PWM")
    p.osc(0, level=0.6, wt=0.4, unison=3, detune=0.12, width=0.6)
    p.osc(1, level=0.35, wt=0.7, fine=-8)
    p.filter("PHASER", cut=0.5, res=0.5, keytrack=0.3)
    p.filter2("HP24", hz=190)
    p.feedback(amount=0.25, drive=0.5, tone=0.7)
    p.env(1, a=0.3, d=1.2, s=0.9, r=0.8)
    bed(p)
    velocity(p, 0.3, 0.05)
    p.tone("CUTOFF", 0.2)
    p.lfo(1, "TRIANGLE", sync="2 BAR", mode="FREE")
    p.set("macro2", 0.5)
    p.motion("LFO1", "CUTOFF", 0.25)
    hall(p, mix=0.18)
    grit(p, mode="HARD", drive=0.35, tone=0.5, amount=0.4, base=0.15)
    p.doc("A mechanical pulse-wave bed phasing through a feedback filter", "C3–C5",
          "Industrial, EBM, darkwave, sci-fi", "Held chords; the phasing is the motion", "SUPPORT",
          "Busy in the mids; leave the snare room around 2 kHz")
    out.append(p)

    p = P("WET CONCRETE", "ANALOG", "BASIC")
    p.osc(0, level=0.65, wt=0.85, unison=5, detune=0.12, width=0.3)
    p.osc(1, level=0.35, wt=0.66, octave=-1)
    p.filter("LP12", hz=900, res=0.15, keytrack=0.4, drive=0.4)
    p.filter2("HP24", hz=190)
    p.env(1, a=0.4, d=1.5, s=0.9, r=1.2)
    bed(p)
    velocity(p, 0.3, 0.05)
    p.tone("CUTOFF", 0.22)
    p.lfo(1, "SINE", sync="4 BAR", mode="FREE")
    p.set("macro2", 0.45)
    p.motion("LFO1", "CUTOFF", 0.18)
    hall(p, mix=0.28, decay=0.4, width=0.45)
    grit(p, mode="TUBE", drive=0.5, tone=0.4, amount=0.4, base=0.3)
    p.doc("Dark, heavy and saturated, in a big wet room", "C3–C5", "Doom, trailer, industrial, drone",
          "Slow chords in the low-mids", "SUPPORT",
          "Lots of 200–500 Hz: high-pass the guitars, or this, at 150")
    out.append(p)

    p = P("THIN ICE", "GLASS", "GLASS")
    p.osc(0, level=0.55, wt=0.7, unison=5, detune=0.1, width=0.8)
    p.osc(1, level=0.3, wt=0.4, octave=1)
    p.insert(1, "SHIFT", after=True, amount=1.0, freq=0.54, mix=0.2)
    p.insert(2, "DECIMATE", after=True, amount=0.15, mix=0.3)
    p.filter("LP12", hz=7000, res=0.05, keytrack=0.2)
    p.filter2("HP12", hz=350)
    p.env(1, a=0.8, d=1.5, s=0.9, r=1.4)
    bed(p)
    velocity(p, 0.3, 0.03)
    p.tone("CUTOFF", 0.15)
    p.lfo(1, "SINE", sync="2 BAR", mode="FREE")
    p.set("macro2", 0.4)
    p.motion("LFO1", "INS1_FREQ", 0.03)
    p.motion("LFO1", "A_WTPOS", 0.2)
    hall(p, mix=0.26)
    p.eq(high=-2, high_hz=9000)
    grit(p, mode="SOFT", drive=0.3, tone=0.6, amount=0.3, base=0.1)
    p.doc("High glass shimmer with a shifted copy sliding under it", "C4–C6", "Film, ambient, post-rock",
          "Chords high up, over everything else", "TEXTURE",
          "Sits above 350 Hz; pair it with a dark pad for the body")
    out.append(p)

    p = P("BROKEN HALO", "CHOIR", "GLASS")
    p.osc(0, level=0.6, wt=0.3, unison=5, detune=0.12, width=0.7)
    p.osc(1, level=0.3, wt=0.5, octave=1)
    p.insert(1, "SHIFT", after=True, amount=1.0, freq=0.525, mix=0.45)
    p.filter("LP12", hz=4500, res=0.05, keytrack=0.3)
    p.filter2("HP12", hz=180)
    p.env(1, a=0.9, d=1.5, s=0.9, r=1.4)
    bed(p)
    velocity(p, 0.3, 0.03)
    p.tone("CUTOFF", 0.18)
    p.lfo(1, "SMOOTH_RANDOM", hz=0.2, mode="TRIG")
    p.set("macro2", 0.45)
    p.motion("LFO1", "INS1_FREQ", 0.04)
    p.chorus(mode="WIDE", mix=0.35, rate=0.35, depth=0.5, width=0.8)
    hall(p, mix=0.24)
    grit(p, mode="SOFT", drive=0.3, tone=0.5, amount=0.3, base=0.15)
    p.doc("An angelic choir half-shifted out of tune: halo and wound in the same sound", "C3–C5",
          "Film score, industrial ballads, ambient", "Slow chords", "TEXTURE",
          "The shifted half is 45%: turn MIX-heavy tracks' vocals up, not this down")
    out.append(p)

    p = P("SLOW BLEED", "ANALOG", "ANALOG")
    p.osc(0, level=0.6, wt=1.0, unison=5, detune=0.16, width=0.7)
    p.osc(1, level=0.35, wt=0.9, fine=-12, unison=3, detune=0.1, width=0.6)
    p.insert(1, "FOLD", after=True, amount=0.2, mix=0.35)
    p.filter("LP24", hz=1600, res=0.15, keytrack=0.3)
    p.filter2("HP12", hz=170)
    p.env(1, a=0.7, d=1.5, s=0.9, r=1.2)
    bed(p)
    velocity(p, 0.3, 0.05)
    p.tone("CUTOFF", 0.2)
    p.lfo(1, "SMOOTH_RANDOM", hz=0.3, mode="TRIG")
    p.lfo(2, "TRIANGLE", sync="4 BAR", mode="FREE")
    p.set("macro2", 0.45)
    p.motion("LFO1", "A_FINE", 0.1)
    p.motion("LFO2", "INS1_AMOUNT", 0.25)
    hall(p, mix=0.22)
    grit(p, mode="TUBE", drive=0.4, tone=0.5, amount=0.35, base=0.2)
    p.doc("Detuned saws that drift apart and fold at the edges, over four bars", "C3–C5",
          "Industrial ballads, synthwave, film", "Long chords", "SUPPORT",
          "The drift is slow and small; MOTION 0 locks the tuning for piano parts")
    out.append(p)

    p = P("INTERFERENCE", "ANALOG", "PWM")
    p.osc(0, level=0.6, wt=0.9, unison=3, detune=0.12, width=0.6)
    p.osc(1, level=0.35, wt=0.4, octave=1)
    p.insert(1, "DECIMATE", after=True, amount=0.5, mix=0.6)
    p.filter("LP24", hz=2400, res=0.15, keytrack=0.3)
    p.filter2("HP12", hz=180)
    p.env(1, a=0.3, d=1.2, s=0.9, r=1.0)
    bed(p)
    velocity(p, 0.3, 0.05)
    p.tone("CUTOFF", 0.2)
    p.performer(1, {0: seq("x--x-x--x--xx-x-", {"x": (0.8, "DECAY")}),
                    1: seq("x-x-x-x-x-x-x-x-", {"x": (0.8, "DECAY")})}, rate="1/16")
    p.set("macro2", 0.5)
    p.motion("PERF1", "INS1_AMOUNT", 0.45)
    hall(p, mix=0.2)
    grit(p, mode="SOFT", drive=0.35, tone=0.5, amount=0.35, base=0.15)
    p.doc("A pad that glitches in rhythm: the crush spikes on a syncopated sixteenth grid", "C3–C5",
          "Industrial, glitch, IDM, trailer", "Held chords; the glitch is the groove", "RHYTHM",
          "Pattern B is straight; MOTION 0 leaves a steady, lightly crushed pad")
    out.append(p)

    p = P("MOTHER TONGUE", "FORMANT", "CHOIR")
    p.osc(0, level=0.6, wt=0.3, unison=3, detune=0.1, width=0.6)
    p.osc(1, level=0.35, wt=0.6, unison=2, detune=0.08, width=0.5)
    p.noise(0.05, type="BREATH", color=0.5)
    p.filter("FORMANT", cut=0.4, res=0.3, keytrack=0.2, drive=0.3)
    p.filter2("HP12", hz=180)
    p.env(1, a=0.6, d=1.5, s=0.9, r=1.2)
    bed(p)
    velocity(p, 0.3, 0.05)
    p.tone("CUTOFF", 0.18)
    p.performer(1, {0: seq("aaaabbbbccccdddd", {"a": (-0.8, "GLIDE"), "b": (0.4, "GLIDE"), "c": (-0.2, "GLIDE"), "d": (0.9, "GLIDE")})},
                rate="1/4")
    p.set("macro2", 0.5)
    p.motion("PERF1", "CUTOFF", 0.5)
    p.motion("PERF1", "A_WTPOS", 0.35)
    hall(p, mix=0.24)
    grit(p, mode="SOFT", drive=0.3, tone=0.5, amount=0.35, base=0.1)
    p.doc("Voices that speak four vowels over four bars", "C3–C5", "Film, darkwave, trip-hop, ambient",
          "Chords that last whole phrases", "TEXTURE",
          "Vowels move on the bar; TONE shifts which ones, MOTION 0 holds one")
    out.append(p)

    p = P("SCAR FIELD", "BASIC", "ANALOG")
    p.osc(0, level=0.6, wt=0.5, unison=5, detune=0.14, width=0.7)
    p.osc(1, level=0.35, wt=0.85, octave=-1)
    p.insert(1, "SINE", after=True, amount=0.35, mix=0.6)
    p.filter("LP24", hz=2000, res=0.1, keytrack=0.3)
    p.filter2("HP24", hz=190)
    p.env(1, a=0.4, d=1.5, s=0.9, r=1.0)
    bed(p)
    velocity(p, 0.3, 0.05)
    p.tone("INS1_AMOUNT", 0.25)
    p.lfo(1, "TRIANGLE", sync="2 BAR", mode="FREE")
    p.set("macro2", 0.45)
    p.motion("LFO1", "INS1_AMOUNT", 0.3)
    p.chorus(mode="SUBTLE", mix=0.35, rate=0.3, depth=0.5, width=0.45)
    hall(p, mix=0.2)
    grit(p, mode="TUBE", drive=0.35, tone=0.5, amount=0.35, base=0.15)
    p.doc("A warm bed whose sine shaper wrinkles and smooths over two bars", "C3–C5",
          "Industrial ballads, film, synth-pop", "Chords under vocals", "SUPPORT",
          "Warm in the low-mids: works as the main pad in a sparse mix")
    out.append(p)

    p = P("FERRIC", "SPECTRAL_COMB", "BASIC")
    p.osc(0, level=0.6, wt=0.4, unison=3, detune=0.1, width=0.6)
    p.osc(1, level=0.3, wt=0.0, octave=-1)
    p.insert(1, "COMB", after=True, amount=0.7, freq=0.75, mix=0.45)
    p.filter("LP24", hz=3000, res=0.15, keytrack=0.3)
    p.filter2("HP12", hz=200)
    p.feedback(amount=0.18, drive=0.5, tone=0.7)
    p.env(1, a=0.5, d=1.5, s=0.9, r=1.0)
    bed(p)
    velocity(p, 0.3, 0.05)
    p.tone("CUTOFF", 0.2)
    p.lfo(1, "SINE", sync="4 BAR", mode="FREE")
    p.set("macro2", 0.45)
    p.motion("LFO1", "A_WTPOS", 0.3)
    p.motion("LFO1", "INS1_AMOUNT", 0.15)
    hall(p, mix=0.22)
    grit(p, mode="SOFT", drive=0.3, tone=0.5, amount=0.35, base=0.1)
    p.doc("A metallic bed with combs ringing an octave up, like struck iron that won't stop", "C3–C5",
          "Industrial, horror, sci-fi, film", "Slow chords; the ring is part of the sound", "TEXTURE",
          "Rings at the octave, so it stays in key; shorten notes if they smear together")
    out.append(p)

    p = P("SUBMERSION", "ANALOG", "BASIC")
    p.osc(0, level=0.6, wt=0.7, unison=5, detune=0.12, width=0.6)
    p.osc(1, level=0.35, wt=0.3, octave=-1)
    p.noise(0.08, type="BROWN", color=0.7, keytrack=False)
    p.filter("LP12", hz=700, res=0.25, keytrack=0.3, drive=0.3)
    p.filter2("HP24", hz=190)
    p.env(1, a=0.8, d=1.5, s=0.9, r=1.2)
    bed(p)
    velocity(p, 0.3, 0.05)
    p.tone("CUTOFF", 0.25)
    p.lfo(1, "SINE", hz=0.15, mode="TRIG")
    p.set("macro2", 0.45)
    p.motion("LFO1", "CUTOFF", 0.2)
    p.chorus(mode="DEEP", mix=0.35, rate=0.25, depth=0.55, width=0.45)
    hall(p, mix=0.24)
    grit(p, mode="SOFT", drive=0.3, tone=0.4, amount=0.35, base=0.1)
    p.doc("A pad heard from under water: dark, swaying, with a low hiss", "C3–C5",
          "Dark ambient, film, trip-hop", "Slow chords under a sparse arrangement", "TEXTURE",
          "Very dark: TONE up if it vanishes under other parts")
    out.append(p)

    p = P("NAKED WIRE", "BASIC", "ANALOG")
    p.osc(0, level=0.6, wt=0.0, unison=3, detune=0.1, width=0.6)
    p.osc(1, level=0.3, wt=0.9, octave=1)
    p.insert(1, "RECTIFY", after=True, amount=0.7, mix=0.5)
    p.filter("LP12", hz=5000, res=0.05, keytrack=0.3)
    p.filter2("HP12", hz=200)
    p.env(1, a=0.3, d=1.2, s=0.9, r=1.0)
    bed(p)
    velocity(p, 0.3, 0.05)
    p.tone("INS1_AMOUNT", 0.25)
    p.lfo(1, "SINE", sync="2 BAR", mode="FREE")
    p.set("macro2", 0.45)
    p.motion("LFO1", "INS1_AMOUNT", 0.3)
    p.motion("LFO1", "B_LEVEL", 0.12)
    hall(p, mix=0.22)
    grit(p, mode="HARD", drive=0.35, tone=0.5, amount=0.35, base=0.15)
    p.doc("Sines rectified into a buzzing octave edge that comes and goes", "C3–C5",
          "Industrial, minimal, film", "Chords with space around them", "SUPPORT",
          "Edgy in the upper mids; a de-esser-style cut at 3 kHz softens it")
    out.append(p)

    p = P("SIGNAL DECAY", "ANALOG", "GLASS")
    p.osc(0, level=0.6, wt=0.8, unison=3, detune=0.12, width=0.6)
    p.osc(1, level=0.3, wt=0.5, octave=1)
    p.insert(1, "BITCRUSH", after=True, amount=0.3, mix=0.5)
    p.filter("LP24", hz=2800, res=0.1, keytrack=0.3)
    p.filter2("HP12", hz=180)
    p.env(1, a=0.3, d=1.2, s=0.9, r=1.0)
    p.env(4, a=2.5, d=1.0, s=1.0, r=1.0)
    p.mod("ENV4", "INS1_AMOUNT", 0.35)
    bed(p)
    velocity(p, 0.3, 0.05)
    p.tracker(1, "NOTE", [-0.4, -0.35, -0.3, -0.25, -0.2, -0.1, 0.0, 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9])
    p.mod("TRACK1", "INS1_AMOUNT", 0.25)
    p.tone("CUTOFF", 0.2)
    p.lfo(1, "SINE", sync="2 BAR", mode="FREE")
    p.set("macro2", 0.45)
    p.motion("LFO1", "CUTOFF", 0.15)
    hall(p, mix=0.2)
    grit(p, mode="TUBE", drive=0.35, tone=0.5, amount=0.35, base=0.2)
    p.doc("Each chord starts clean and crumbles as it holds; higher notes crumble more", "C3–C5",
          "Film score, lo-fi, industrial ballads", "Long chords: the decay takes about three seconds", "TEXTURE",
          "Short chords stay clean; hold them to hear it fall apart")
    out.append(p)

    p = P("MIDNIGHT ORGAN", "ORGAN", "ANALOG")
    p.osc(0, level=0.65, wt=0.7)
    p.osc(1, level=0.25, wt=0.9, octave=1, fine=4)
    p.filter("LP12", hz=3500, res=0.05, keytrack=0.3, drive=0.35)
    p.filter2("HP12", hz=160)
    p.env(1, a=0.05, d=1.0, s=0.95, r=0.6)
    bed(p)
    velocity(p, 0.3, 0.05)
    p.tone("CUTOFF", 0.2)
    p.lfo(1, "SINE", hz=6.0, mode="FREE")
    p.lfo(2, "SINE", sync="4 BAR", mode="FREE")
    p.set("macro2", 0.45)
    p.motion("LFO1", "AMP", 0.15)
    p.motion("LFO1", "PAN", 0.2)
    p.motion("LFO2", "A_WTPOS", 0.2)
    p.chorus(mode="DEEP", mix=0.4, rate=0.4, depth=0.55, width=0.85)
    hall(p, mix=0.2, decay=0.33)
    grit(p, mode="TUBE", drive=0.45, tone=0.45, amount=0.4, base=0.3)
    p.doc("An overdriven organ through a deep chorus, spinning like a rotating speaker", "C3–C5",
          "Industrial ballads, blues-noir, film", "Chords and held voicings", "SUPPORT",
          "The spin is on MOTION; 0 is a still, driven organ")
    out.append(p)

    p = P("HOLLOW EARTH", "ANALOG", "BASIC")
    p.osc(0, level=0.6, wt=0.8, unison=3, detune=0.1, width=0.3)
    p.osc(1, level=0.4, wt=0.0)
    p.insert(1, "COMB", after=True, amount=0.5, freq=0.5, mix=0.3)
    p.filter("LP12", hz=1100, res=0.15, keytrack=0.3, drive=0.35)
    p.filter2("HP24", hz=190)
    p.env(1, a=0.6, d=1.5, s=0.9, r=1.2)
    bed(p)
    velocity(p, 0.3, 0.05)
    p.tone("CUTOFF", 0.22)
    p.lfo(1, "TRIANGLE", sync="4 BAR", mode="FREE")
    p.set("macro2", 0.45)
    p.motion("LFO1", "CUTOFF", 0.18)
    p.motion("LFO1", "INS1_AMOUNT", 0.15)
    hall(p, mix=0.24, width=0.45)
    grit(p, mode="TUBE", drive=0.35, tone=0.45, amount=0.35, base=0.15)
    p.context(shift=-12)
    p.doc("A low, hollow bed resonating like a cave: the chord played an octave down", "C2–C4",
          "Doom, trailer, dark ambient", "Chords played low", "SUPPORT",
          "Lives low: high-pass the bass above 100 Hz, or drop this when the bass plays")
    out.append(p)

    return out
