"""PLUCK: short, struck and snapped. Each attack has an edge (fold, comb,
ring, crush) and the tail is shaped so fast patterns stay clear."""

from lunatk import Preset
from bank2._common import accents, echo, grit, space, velocity


def K(name, a="ANALOG", b="BASIC"):
    return Preset(name, "PLUCK", a, b)


def poly(p, voices=8, vel=0.7):
    return p.voice(voices=voices, glide=0.0, vel=vel, bend=2)


def plate(p, mix=0.12, decay=0.26, amount=0.14):
    return space(p, mix, mode="PLATE", size=0.4, decay=decay, damp=0.55, predelay=0.03, width=0.7, amount=amount)


def pluck_env(p, decay=0.35, release=0.2, fdecay=0.18, env=0.45):
    p.env(1, a=0.001, d=decay, s=0.0, r=release)
    p.env(2, a=0.001, d=fdecay, s=0.0, r=release)
    return p


def presets():
    out = []

    p = K("RAZOR PLUCK", "ANALOG", "ANALOG")
    p.osc(0, level=0.7, wt=1.0)
    p.osc(1, level=0.3, wt=1.0, fine=7)
    p.insert(1, "FOLD", amount=0.2, mix=0.8)
    pluck_env(p)
    p.env(3, a=0.001, d=0.12, s=0.0, r=0.1)
    p.mod("ENV3", "INS1_AMOUNT", 0.45)
    p.filter("LP24", hz=900, res=0.25, keytrack=0.5, env=0.5)
    p.filter2("HP12", hz=200)
    poly(p)
    velocity(p, 0.75, 0.25)
    p.tone("CUTOFF", 0.18)
    p.lfo(1, "TRIANGLE", sync="1 BAR", mode="FREE")
    p.set("macro2", 0.35)
    p.motion("LFO1", "INS1_AMOUNT", 0.25)
    echo(p, time="3/16", mix=0.12, feedback=0.3, amount=0.12, pingpong=True)
    grit(p, mode="HARD", drive=0.4, tone=0.5, amount=0.4, base=0.2)
    p.doc("A saw pluck with a folded snap on the attack", "C3–C6", "Industrial, EBM, cyberpunk, techno",
          "Sixteenth patterns and riffs", "RHYTHM", "The snap is 120 ms long; it cuts through without adding level")
    out.append(p)

    p = K("METAL SNAP", "BASIC", "BASIC")
    p.osc(0, level=0.7, wt=0.66)
    p.insert(1, "COMB", amount=0.8, freq=0.5, mix=0.6)
    p.insert(2, "RING", after=True, amount=0.5, freq=0.625, mix=0.25)
    pluck_env(p, decay=0.4)
    p.filter("LP12", hz=3000, res=0.05, keytrack=0.4, env=0.3)
    p.filter2("HP12", hz=220)
    poly(p)
    velocity(p, 0.75, 0.2)
    p.tone("CUTOFF", 0.18)
    p.lfo(1, "TRIANGLE", sync="1/4", mode="FREE")
    p.set("macro2", 0.35)
    p.motion("LFO1", "INS2_AMOUNT", 0.4)
    p.motion("LFO1", "CUTOFF", 0.15)
    echo(p, time="1/8", mix=0.1, feedback=0.3, amount=0.12)
    plate(p)
    p.doc("A tuned metal string snapped: comb body with a ring on top", "C3–C6", "Industrial, film, sci-fi, IDM",
          "Arpeggios and ostinatos", "RHYTHM", "Rings at octaves; stays in key under any chord")
    out.append(p)

    p = K("GLASS SHARD", "GLASS", "GLASS")
    p.osc(0, level=0.65, wt=0.6)
    p.osc(1, level=0.3, wt=0.3, octave=1)
    p.insert(1, "BITCRUSH", after=True, amount=0.45, mix=0.3)
    p.insert(2, "COMB", after=True, amount=0.5, freq=0.75, mix=0.25)
    pluck_env(p, decay=0.5, release=0.3)
    p.filter("LP12", hz=3500, res=0.05, keytrack=0.3, env=0.25)
    p.filter2("HP12", hz=250)
    poly(p)
    velocity(p, 0.75, 0.2)
    p.tone("CUTOFF", 0.15)
    p.lfo(1, "SINE", sync="1 BAR", mode="FREE")
    p.set("macro2", 0.35)
    p.motion("LFO1", "A_WTPOS", 0.2)
    echo(p, time="3/16", mix=0.16, feedback=0.35, amount=0.14, pingpong=True)
    plate(p, mix=0.14)
    p.eq(high=-3, high_hz=8000)
    p.doc("A glass pluck, lightly crushed, bouncing in a ping-pong echo", "C4–C6", "Film, ambient, trip-hop, pop-noir",
          "Arpeggios and sparse figures", "RHYTHM", "Echo is 3/16: it plays a counter-rhythm; SPACE down to tighten")
    out.append(p)

    p = K("CORRODED HARP", "ANALOG", "GLASS")
    p.osc(0, level=0.6, wt=0.5)
    p.osc(1, level=0.3, wt=0.5, octave=1)
    p.insert(1, "COMB", amount=0.75, freq=0.5, mix=0.5)
    p.insert(2, "DECIMATE", after=True, amount=0.3, mix=0.35)
    pluck_env(p, decay=0.7, release=0.4)
    p.filter("LP12", hz=2500, res=0.05, keytrack=0.5, env=0.3)
    p.filter2("HP12", hz=200)
    poly(p)
    velocity(p, 0.75, 0.2)
    p.tone("CUTOFF", 0.18)
    p.lfo(1, "SMOOTH_RANDOM", hz=0.7, mode="FREE")
    p.set("macro2", 0.35)
    p.motion("LFO1", "INS2_AMOUNT", 0.3)
    echo(p, time="1/4", mix=0.12, feedback=0.3, amount=0.12)
    plate(p, mix=0.14)
    p.doc("A harp whose strings have rusted: resonant, crushed at the edges", "C3–C6", "Film score, gothic, ambient, horror",
          "Broken chords and slow arpeggios", "FOREGROUND", "Let notes ring; it wants space around it")
    out.append(p)

    p = K("RUST DROP", "BASIC", "BASIC")
    p.osc(0, level=0.7, wt=0.0, warp="FM", warp_amt=0.3)
    p.osc(1, level=0.002, wt=0.0, octave=1)
    pluck_env(p, decay=0.3)
    p.env(3, a=0.001, d=0.06, s=0.0, r=0.05)
    p.mod("ENV3", "PITCH", 0.08)
    p.mod("ENV3", "A_WARP", 0.3)
    p.filter("LP12", hz=3000, res=0.05, keytrack=0.4, env=0.3)
    p.filter2("HP12", hz=200)
    poly(p)
    velocity(p, 0.75, 0.2)
    p.tone("A_WARP", 0.2)
    p.lfo(1, "TRIANGLE", sync="1/2", mode="FREE")
    p.set("macro2", 0.35)
    p.motion("LFO1", "A_WARP", 0.15)
    echo(p, time="1/8", mix=0.1, feedback=0.3, amount=0.12)
    grit(p, mode="HARD", drive=0.45, tone=0.5, amount=0.4, base=0.25)
    p.doc("An FM drop that falls into its note, clipped and metallic", "C3–C6", "Industrial, glitch, electro, game",
          "Fast patterns; every note drops in", "RHYTHM", "The drop is 60 ms; it reads as attack, not as a pitch bend")
    out.append(p)

    p = K("NERVE TICK", "BASIC", "BASIC")
    p.osc(0, level=0.5, wt=0.33)
    p.noise(0.3, type="WHITE", color=0.3)
    p.insert(1, "COMB", amount=0.85, freq=0.5, mix=0.7)
    pluck_env(p, decay=0.15, release=0.1)
    p.filter("BP", hz=2400, res=0.2, keytrack=0.5, env=0.2)
    p.filter2("HP12", hz=300)
    poly(p)
    velocity(p, 0.75, 0.2)
    p.tone("CUTOFF", 0.1)
    p.performer(1, {0: accents("X-x-x-X-x-x-X-x-", "HOLD")}, rate="1/16")
    p.set("macro2", 0.4)
    p.motion("PERF1", "NOISE_LEVEL", 0.2)
    p.motion("PERF1", "CUTOFF", 0.1)
    echo(p, time="1/16", mix=0.1, feedback=0.25, amount=0.1)
    p.context(allow_air=True, unpitched=True)
    p.doc("A tiny tuned tick: a burst of noise ringing a comb at the note", "C4–C6", "IDM, industrial, glitch, minimal",
          "Fast sixteenths; it is almost percussion", "RHYTHM", "Tiny on its own; double a bassline with it for articulation")
    out.append(p)

    p = K("BONE PLUCK", "BASIC", "BASIC")
    p.osc(0, level=0.7, wt=0.0)
    p.insert(1, "SINE", amount=0.35, mix=0.8)
    p.insert(2, "COMB", after=True, amount=0.5, freq=0.75, mix=0.3)
    pluck_env(p, decay=0.3)
    p.env(3, a=0.001, d=0.08, s=0.0, r=0.05)
    p.mod("ENV3", "INS1_AMOUNT", 0.4)
    p.filter("LP12", hz=3500, res=0.05, keytrack=0.3)
    p.filter2("HP12", hz=180)
    poly(p)
    velocity(p, 0.75, 0.0)
    p.mod("VELOCITY", "INS1_AMOUNT", 0.3)
    p.tone("INS1_AMOUNT", 0.2)
    p.lfo(1, "TRIANGLE", sync="1/4", mode="FREE")
    p.set("macro2", 0.35)
    p.motion("LFO1", "INS2_AMOUNT", 0.4)
    p.motion("LFO1", "INS1_AMOUNT", 0.2)
    echo(p, time="3/16", mix=0.1, feedback=0.3, amount=0.12)
    plate(p)
    p.doc("A hollow wooden mallet: a sine shaped into overtones, knocking a comb", "C3–C6",
          "Film, ethno-industrial, minimal, IDM", "Ostinatos and melodies", "RHYTHM",
          "Marimba-like but darker; velocity sets the knock")
    out.append(p)

    p = K("STATIC PLUCK", "BASIC", "BASIC")
    p.osc(0, level=0.3, wt=0.66)
    p.noise(0.45, type="DIGITAL", color=0.4)
    p.insert(1, "COMB", amount=0.9, freq=0.5, mix=0.8)
    p.insert(2, "DECIMATE", after=True, amount=0.3, mix=0.4)
    pluck_env(p, decay=0.35)
    p.filter("LP12", hz=3000, res=0.05, keytrack=0.4, env=0.25)
    p.filter2("HP12", hz=250)
    poly(p)
    velocity(p, 0.75, 0.2)
    p.tone("CUTOFF", 0.15)
    p.lfo(1, "SAMPLE_HOLD", sync="1/16", mode="FREE")
    p.set("macro2", 0.35)
    p.motion("LFO1", "INS2_AMOUNT", 0.3)
    echo(p, time="1/8", mix=0.12, feedback=0.3, amount=0.12)
    p.doc("Digital static plucked into a tuned string", "C3–C6", "Glitch, IDM, industrial, hip-hop",
          "Arpeggios; each note is a little different", "RHYTHM", "The grain changes every sixteenth on MOTION")
    out.append(p)

    p = K("BENT KALIMBA", "FM_BELL", "BASIC")
    p.osc(0, level=0.7, wt=0.35)
    p.insert(1, "SHIFT", after=True, amount=1.0, freq=0.52, mix=0.2)
    p.insert(2, "COMB", after=True, amount=0.4, freq=0.5, mix=0.25)
    pluck_env(p, decay=0.6, release=0.3)
    p.filter("LP12", hz=3500, res=0.05, keytrack=0.3)
    p.filter2("HP12", hz=200)
    poly(p)
    velocity(p, 0.75, 0.2)
    p.tone("A_WTPOS", 0.2)
    p.lfo(1, "SMOOTH_RANDOM", hz=0.5, mode="FREE")
    p.set("macro2", 0.35)
    p.motion("LFO1", "INS1_FREQ", 0.02)
    p.motion("LFO1", "PITCH", 0.001)
    echo(p, time="3/16", mix=0.14, feedback=0.35, amount=0.12)
    plate(p)
    p.doc("A thumb piano with bent tines: a faint shifted shimmer and a little wobble", "C3–C6",
          "Film, trip-hop, folk-noir, lullaby-noir", "Simple repeating figures", "FOREGROUND",
          "Slightly off on purpose; pull MOTION down to steady it")
    out.append(p)

    p = K("SPARK GAP", "SYNC_SWEEP", "BASIC")
    p.osc(0, level=0.7, wt=0.2)
    p.insert(1, "RING", after=True, amount=0.4, freq=0.75, mix=0.2)
    pluck_env(p, decay=0.25)
    p.env(3, a=0.001, d=0.2, s=0.0, r=0.1)
    p.mod("ENV3", "A_WTPOS", 0.6)
    p.filter("LP24", hz=3500, res=0.15, keytrack=0.4)
    p.filter2("HP12", hz=220)
    poly(p)
    velocity(p, 0.75, 0.2)
    p.tone("A_WTPOS", 0.2)
    p.lfo(1, "TRIANGLE", sync="1/4", mode="FREE")
    p.set("macro2", 0.35)
    p.motion("LFO1", "INS1_AMOUNT", 0.4)
    p.motion("LFO1", "CUTOFF", 0.12)
    echo(p, time="1/8", mix=0.1, feedback=0.3, amount=0.12, pingpong=True)
    grit(p, mode="HARD", drive=0.4, tone=0.5, amount=0.4, base=0.2)
    p.doc("A sync pluck that sparks on every note, with a ring two octaves up", "C3–C6", "Electro, industrial, synthwave",
          "Fast arpeggios", "RHYTHM", "Bright attack: pair with a darker pad")
    out.append(p)

    p = K("DUSTED MALLET", "BASIC", "BASIC")
    p.osc(0, level=0.7, wt=0.33)
    p.noise(0.08, type="VINYL", color=0.5, keytrack=False)
    p.insert(1, "COMB", after=True, amount=0.5, freq=0.5, mix=0.3)
    pluck_env(p, decay=0.4)
    p.filter("LP12", hz=2200, res=0.05, keytrack=0.4, env=0.3)
    p.filter2("HP12", hz=180)
    poly(p)
    velocity(p, 0.75, 0.2)
    p.tone("CUTOFF", 0.18)
    p.lfo(1, "SINE", hz=0.5, mode="FREE")
    p.set("macro2", 0.35)
    p.motion("LFO1", "PITCH", 0.0015)
    p.motion("LFO1", "CUTOFF", 0.08)
    echo(p, time="3/16", mix=0.1, feedback=0.3, amount=0.12)
    plate(p)
    grit(p, mode="SOFT", drive=0.3, tone=0.45, amount=0.35, base=0.1)
    p.doc("A soft mallet on a dusty record", "C3–C6", "Lo-fi, trip-hop, film, ambient", "Melodies and loops", "FOREGROUND",
          "The dust sits on its own layer, filtered with the note")
    out.append(p)

    p = K("CUT WIRE", "BASIC", "BASIC")
    p.osc(0, level=0.7, wt=0.2)
    p.insert(1, "RECTIFY", after=True, amount=0.8, mix=0.6)
    pluck_env(p, decay=0.25)
    p.filter("LP12", hz=4000, res=0.05, keytrack=0.3, env=0.2)
    p.filter2("HP12", hz=350)
    poly(p)
    velocity(p, 0.75, 0.2)
    p.tone("INS1_AMOUNT", 0.25)
    p.lfo(1, "SQUARE", sync="1/4", mode="FREE")
    p.set("macro2", 0.35)
    p.motion("LFO1", "INS1_AMOUNT", 0.3)
    echo(p, time="1/8", mix=0.1, feedback=0.3, amount=0.12)
    grit(p, mode="HARD", drive=0.4, tone=0.5, amount=0.4, base=0.2)
    p.doc("A thin, rectified pluck with a buzzing octave edge", "C3–C6", "Industrial, post-punk, EBM",
          "Riffs and arpeggios", "RHYTHM", "High-passed at 350 Hz: it layers over anything")
    out.append(p)

    p = K("SCAR PLUCK", "BASIC", "BASIC")
    p.osc(0, level=0.7, wt=0.0)
    p.insert(1, "SINE", amount=0.5, mix=1.0)
    p.insert(2, "BITCRUSH", after=True, amount=0.4, mix=0.25)
    pluck_env(p, decay=0.35)
    p.env(3, a=0.001, d=0.15, s=0.0, r=0.1)
    p.mod("ENV3", "INS1_AMOUNT", 0.4)
    p.filter("LP12", hz=4000, res=0.05, keytrack=0.3)
    p.filter2("HP12", hz=200)
    poly(p)
    velocity(p, 0.75, 0.0)
    p.mod("VELOCITY", "INS1_AMOUNT", 0.3)
    p.tone("INS1_AMOUNT", 0.2)
    p.lfo(1, "TRIANGLE", sync="1/4", mode="FREE")
    p.set("macro2", 0.35)
    p.motion("LFO1", "INS2_AMOUNT", 0.3)
    p.motion("LFO1", "INS1_AMOUNT", 0.3)
    echo(p, time="3/16", mix=0.1, feedback=0.3, amount=0.12, pingpong=True)
    p.doc("A sine pluck that flares into bell harmonics as you hit harder", "C3–C6", "Industrial pop, film, electro",
          "Melodic patterns with dynamics", "FOREGROUND", "Velocity is the timbre knob here")
    out.append(p)

    p = K("ICICLE", "GLASS", "GLASS")
    p.osc(0, level=0.6, wt=0.9)
    p.osc(1, level=0.3, wt=0.6, octave=1)
    p.insert(1, "DECIMATE", after=True, amount=0.15, mix=0.3)
    p.insert(2, "SHIFT", after=True, amount=1.0, freq=0.53, mix=0.15)
    pluck_env(p, decay=0.4, release=0.3)
    p.filter("LP12", hz=1800, res=0.05, keytrack=0.4)
    p.filter2("HP12", hz=350)
    poly(p)
    velocity(p, 0.75, 0.15)
    p.tone("EQ_HIGH", 0.25)
    p.eq(high=-4, high_hz=7000)
    p.lfo(1, "SINE", sync="1/4", mode="FREE")
    p.set("macro2", 0.35)
    p.motion("LFO1", "INS1_AMOUNT", 0.25)
    p.motion("LFO1", "INS2_FREQ", 0.02)
    echo(p, time="3/16", mix=0.14, feedback=0.35, amount=0.12, pingpong=True)
    plate(p, mix=0.14)
    p.context(shift=12)
    p.doc("A high, brittle glass pluck with a faint shimmer", "C5–C7", "Film, ambient, winter-noir",
          "Sparse high figures", "TEXTURE", "Lives up high; it never gets in the way")
    out.append(p)

    p = K("TWITCH", "ANALOG", "BASIC")
    p.osc(0, level=0.7, wt=0.95)
    p.insert(1, "FOLD", amount=0.15, mix=0.6)
    pluck_env(p, decay=0.3)
    p.filter("LP24", hz=700, res=0.35, keytrack=0.5, env=0.35, drive=0.3)
    p.filter2("HP12", hz=200)
    poly(p)
    velocity(p, 0.75, 0.2)
    p.tone("CUTOFF", 0.16)
    p.performer(1, {0: accents("X--x-x--X-x--xX-", "DECAY"), 1: accents("X-x-X-x-X-x-X-x-", "DECAY")}, rate="1/16")
    p.set("macro2", 0.5)
    p.motion("PERF1", "CUTOFF", 0.35)
    p.motion("PERF1", "INS1_AMOUNT", 0.3)
    echo(p, time="1/8", mix=0.1, feedback=0.3, amount=0.12)
    grit(p, mode="DIODE", drive=0.4, tone=0.5, amount=0.4, base=0.2)
    p.doc("A resonant pluck whose accents follow a syncopated pattern locked to the bar", "C3–C6",
          "Industrial techno, EBM, acid", "Straight sixteenth notes; the accents make the groove", "RHYTHM",
          "Pattern B is on the eighths; MOTION 0 plays every note the same")
    out.append(p)

    p = K("PIANO WIRE", "ANALOG", "ANALOG")
    p.osc(0, level=0.6, wt=1.0)
    p.osc(1, level=0.35, wt=1.0, octave=1, fine=5)
    p.insert(1, "COMB", amount=0.65, freq=0.5, mix=0.45)
    p.insert(2, "BITCRUSH", after=True, amount=0.5, mix=0.2)
    pluck_env(p, decay=0.45)
    p.filter("LP12", hz=1800, res=0.1, keytrack=0.6, env=0.35)
    p.filter2("HP12", hz=200)
    poly(p)
    velocity(p, 0.75, 0.2)
    p.tone("CUTOFF", 0.18)
    p.lfo(1, "TRIANGLE", sync="1 BAR", mode="FREE")
    p.set("macro2", 0.35)
    p.motion("LFO1", "INS1_AMOUNT", 0.25)
    echo(p, time="3/16", mix=0.1, feedback=0.3, amount=0.12)
    plate(p)
    grit(p, mode="SOFT", drive=0.3, tone=0.5, amount=0.35, base=0.1)
    p.doc("A plucked piano wire: bright, ringing, a little crushed", "C3–C6", "Gothic, film, industrial",
          "Arpeggios and counterpoint", "FOREGROUND", "Rings for half a second; keep patterns open")
    out.append(p)

    return out
