"""SHOWCASE BASSES: the sub is a separate, unfiltered, centred sine or
triangle (filter.routeSub off), so everything violent happens to the
oscillators above it: inserts, filter saturation, feedback and drive.
Velocity changes tone before it changes level. Dry: SPACE is a high-passed
delay that stays off until you ask for it."""

from lunatk import Preset
from bank2._common import grit, velocity
from bank2._showcase import drift, fsat, ladder, punch, vintage


def B(name, a="ANALOG", b="BASIC"):
    return Preset(name, "BASS", a, b)


def mono(p, glide=0.015, legato=True, vel=0.4):
    return p.voice(voices=1, glide=glide, legato=legato, glide_always=False, vel=vel, bend=2)


def foundation(p, level=0.5, shape="SINE"):
    """The clean centred sub, kept out of the filter and its saturation."""
    return p.sub(level, shape, octave=1, pan=0.0, filtered=False)


def dry_space(p, amount=0.18, time="1/8"):
    p.delay(time=time, mix=0.0, feedback=0.25, lowcut=0.8, highcut=0.45, width=0.2)
    return p.space(reverb=0, delay=amount)


def presets():
    out = []

    # 01 IRON LUNG
    p = B("IRON LUNG", "ANALOG", "NS GRINDSTONE")
    p.osc(0, level=0.7, wt=1.0)
    p.osc(1, level=0.32, wt=0.35, fine=6)
    foundation(p, 0.55)
    p.insert(1, "FOLD", amount=0.4, mix=0.7)
    p.filter("LP24", hz=520, res=0.3, keytrack=0.4, env=0.4)
    fsat(p, "HARD", drive=0.45)
    p.env(1, a=0.001, d=0.4, s=0.85, r=0.07)
    p.env(2, a=0.001, d=0.14, s=0.25, r=0.08)
    punch(p, 0.5)
    mono(p)
    velocity(p, 0.4, 0.18)
    p.mod("VELOCITY", "INS1_AMOUNT", 0.2)
    p.tone("CUTOFF", 0.16)
    p.set("macro2", 0.3)
    drift(p, 1, 0.9, [("B_WTPOS", 0.25), ("CUTOFF", 0.04)])
    dry_space(p)
    grit(p, mode="TUBE", drive=0.5, tone=0.45, amount=0.45, base=0.3)
    p.set("b.wtpos", 0.3)
    p.mod("VELOCITY", "B_WTPOS", 0.3)
    p.doc("A dead-solid sine under a folded, snarling growl that shifts shape note to note; the attack lands hard",
          "E0–E2", "Industrial, EBM, dark pop choruses", "Roots, eighths, held notes", "FOREGROUND",
          "The sub never sees the distortion's filter; if it fights a guitar, cut 900 Hz, not GRIT")
    out.append(p)

    # 02 BLACK MOTOR
    p = B("BLACK MOTOR", "NS SCAR PULSE", "ANALOG")
    p.osc(0, level=0.7, wt=0.4)
    p.osc(1, level=0.3, wt=0.9, octave=1, fine=-5)
    foundation(p, 0.5)
    p.insert(1, "RING", amount=0.4, freq=0.5, mix=0.2)
    p.filter("LADDER", hz=600, res=0.35, keytrack=0.4, env=0.3)
    ladder(p, two_pole=True)
    p.env(1, a=0.002, d=0.5, s=0.85, r=0.08)
    p.env(2, a=0.001, d=0.25, s=0.3, r=0.1)
    mono(p)
    velocity(p, 0.4, 0.16)
    p.lfo(1, "TRIANGLE", hz=5.3, mode="TRIG")
    p.lfo(2, "SQUARE", hz=2.65, mode="TRIG", smooth=True)
    p.set("macro2", 0.4)
    p.motion("LFO1", "A_WARP", 0.2)
    p.set("a.warpmode", 5)
    p.motion("LFO2", "INS1_AMOUNT", 0.25)
    p.motion("LFO1", "CUTOFF", 0.05)
    p.tone("CUTOFF", 0.16)
    dry_space(p)
    grit(p, mode="SOFT", drive=0.4, tone=0.45, amount=0.45, base=0.2)
    p.set("a.wtpos", 0.2)
    p.motion("LFO1", "A_WTPOS", 0.2)
    p.doc("A machine idling inside every held note: pulse-width churn and a ring flicker turning over at two geared rates",
          "E0–E2", "Industrial, dark techno, electro", "Held notes and your own rhythm; the motion restarts with each note",
          "FOREGROUND", "The churn is in the mids; the sub under it is still. MOTION 0 turns the engine off")
    out.append(p)

    # 03 TEETH
    p = B("TEETH", "NS SERPENT", "ANALOG")
    p.osc(0, level=0.62, wt=0.6)
    p.osc(1, level=0.4, wt=1.0)
    foundation(p, 0.5)
    p.insert(1, "FOLD", amount=0.35, mix=0.6)
    p.filter("LP24", hz=700, res=0.28, keytrack=0.4, env=0.5)
    fsat(p, "DIODE", drive=0.5)
    p.env(1, a=0.001, d=0.28, s=0.55, r=0.06)
    p.env(2, a=0.001, d=0.06, s=0.2, r=0.05)
    p.env(3, a=0.001, d=0.035, s=0.0, r=0.03)
    p.mod("ENV3", "A_WTPOS", 0.35)
    p.mod("ENV3", "A_PITCH", 0.03)
    punch(p, 0.7)
    mono(p, glide=0.0, legato=False)
    velocity(p, 0.45, 0.2)
    p.tone("CUTOFF", 0.16)
    p.set("macro2", 0.25)
    drift(p, 1, 1.3, [("INS1_AMOUNT", 0.15)])
    dry_space(p)
    grit(p, mode="HARD", drive=0.5, tone=0.45, amount=0.4, base=0.25)
    p.set("a.wtpos", 0.2)
    p.doc("A short bite: a 35 ms sync-and-pitch snap, then a thick diode-driven body. Tonal, not a kick",
          "E0–E2", "Industrial, electro-rock, EBM", "Staccato eighths and sixteenths", "FOREGROUND",
          "The bite sits at 1–3 kHz; it cuts through distorted drums without more level")
    out.append(p)

    # 04 LOW VIOLENCE
    p = B("LOW VIOLENCE", "ANALOG", "NS TENDON")
    p.osc(0, level=0.65, wt=0.6)
    p.osc(1, level=0.0, wt=0.5)
    foundation(p, 0.6)
    p.insert(1, "SINE", amount=0.0, mix=0.8)
    p.filter("LP24", hz=320, res=0.25, keytrack=0.4, env=0.2)
    fsat(p, "SOFT", drive=0.3)
    p.env(1, a=0.002, d=0.5, s=0.9, r=0.08)
    p.env(2, a=0.001, d=0.25, s=0.3, r=0.08)
    mono(p)
    p.set("velSens", 0.2)
    p.mod("VELOCITY", "B_LEVEL", 0.45, curve=0.5)
    p.mod("VELOCITY", "INS1_AMOUNT", 0.45, curve=0.5)
    p.mod("VELOCITY", "CUTOFF", 0.3, curve=0.4)
    p.mod("VELOCITY", "DIST_MIX", 0.35, curve=0.5)
    p.tone("CUTOFF", 0.16)
    p.set("macro2", 0.25)
    drift(p, 1, 0.7, [("B_WTPOS", 0.2)])
    dry_space(p)
    grit(p, mode="TUBE", drive=0.5, tone=0.45, amount=0.35, base=0.0)
    p.set("b.wtpos", 0.1)
    p.mod("VELOCITY", "B_WTPOS", 0.55, curve=0.5)
    p.doc("Played softly it is a deep, polite round bass; hit it and a growl and a wavefold tear open, with little more level",
          "E0–E2", "Dark pop, alt-electronic, trailers", "Velocity is the whole performance", "FOREGROUND",
          "Velocity curves are bent so only the top third of the range bares its teeth")
    out.append(p)

    # 05 CONCRETE
    p = B("CONCRETE", "ANALOG", "ANALOG")
    p.osc(0, level=0.7, wt=0.9)
    p.osc(1, level=0.4, wt=0.5, octave=-1)
    foundation(p, 0.6, "TRI")
    p.filter("LP24", hz=380, res=0.18, keytrack=0.4, env=0.2, drive=0.35)
    fsat(p, "LIGHT", drive=0.4)
    p.env(1, a=0.002, d=0.6, s=0.9, r=0.07)
    p.env(2, a=0.001, d=0.2, s=0.4, r=0.08)
    punch(p, 0.3)
    mono(p)
    velocity(p, 0.4, 0.12)
    p.eq(low=0, mid=2.0, mid_hz=240, q=0.4)
    p.tone("CUTOFF", 0.16)
    p.set("macro2", 0.2)
    drift(p, 1, 0.5, [("CUTOFF", 0.03)])
    grit(p, mode="SOFT", drive=0.4, tone=0.35, amount=0.3, base=0.15)
    p.set("priority", 1)
    p.fxfilter(type="HP", cut=0.04, res=0.0, mix=1.0)
    p.doc("Heavy, not fuzzy: a triangle foundation, a dense saw body with 240 Hz weight, saturated flat and dry",
          "E0–E2", "Industrial rock, metal-electronic, EBM", "Riffs and roots", "FOREGROUND",
          "No ambience at all by design; it takes a room from the mix bus better than from itself")
    out.append(p)

    # 06 FAULT LINE
    p = B("FAULT LINE", "ANALOG", "NS FRACTURE")
    p.osc(0, level=0.62, wt=0.8)
    p.osc(1, level=0.3, wt=0.2, octave=1)
    foundation(p, 0.6)
    p.insert(1, "DECIMATE", after=True, amount=0.0, mix=0.5)
    p.filter("LP24", hz=600, res=0.25, keytrack=0.4)
    p.filter2("HP12", hz=110)
    p.env(1, a=0.003, d=0.6, s=0.9, r=0.08)
    p.env(3, a=2.5, d=0.1, s=1.0, r=0.1, acurve=0.4)
    p.mod("ENV3", "INS1_AMOUNT", 0.4)
    p.mod("ENV3", "B_WTPOS", 0.5)
    p.mod("ENV3", "B_FINE", -0.08)
    mono(p)
    velocity(p, 0.4, 0.15)
    p.tone("CUTOFF", 0.16)
    p.set("macro2", 0.35)
    drift(p, 1, 0.37, [("B_WTPOS", 0.2), ("INS1_AMOUNT", 0.1)])
    dry_space(p)
    grit(p, mode="TUBE", drive=0.45, tone=0.45, amount=0.4, base=0.2)
    p.set("b.wtpos", 0.0)
    p.motion("LFO1", "CUTOFF", 0.12)
    p.doc("Hold a note and the ground cracks above it: the upper layer folds, sags and crumbles over three seconds while the sub stays put",
          "E0–E2", "Industrial, film, dark ambient bass", "Long notes and slow lines", "SUPPORT",
          "The high-pass on the upper layer keeps the destruction away from the sub entirely")
    out.append(p)

    # 07 NIGHT DRIVER
    p = B("NIGHT DRIVER", "ANALOG", "PWM")
    p.osc(0, level=0.66, wt=0.95)
    p.osc(1, level=0.28, wt=0.3, fine=-7)
    foundation(p, 0.45)
    p.insert(1, "SINE", amount=0.2, mix=0.3)
    p.filter("LADDER", hz=750, res=0.3, keytrack=0.5, env=0.35)
    p.env(1, a=0.002, d=0.35, s=0.75, r=0.08)
    p.env(2, a=0.001, d=0.2, s=0.3, r=0.1)
    mono(p, glide=0.03)
    velocity(p, 0.4, 0.18)
    p.tone("CUTOFF", 0.16)
    p.set("macro2", 0.25)
    drift(p, 1, 0.6, [("CUTOFF", 0.04), ("A_FINE", 0.02)])
    p.chorus(mode="SUBTLE", mix=0.15, rate=0.3, depth=0.3, width=0.3)
    dry_space(p)
    grit(p, mode="TUBE", drive=0.45, tone=0.5, amount=0.4, base=0.2)
    p.set("b.warpmode", 5)
    p.set("b.warp", 0.2)
    p.motion("LFO1", "B_WARP", 0.2)
    p.doc("A melodic bass that speaks straight away: a warm ladder saw with a pulse shadow, a short glide and a sine-shaped edge for small speakers",
          "E1–E3", "Dark pop, alt-electronic, nocturnal house", "Real bass lines, legato slides", "FOREGROUND",
          "Enough upper harmonics to read on a phone; the chorus is only above 150 Hz in effect")
    out.append(p)

    # 08 BURN CIRCUIT
    p = B("BURN CIRCUIT", "ANALOG", "ANALOG")
    p.osc(0, level=0.62, wt=1.0, unison=2, detune=0.05, width=0.1)
    p.osc(1, level=0.34, wt=0.6, fine=4)
    foundation(p, 0.5)
    p.filter("LADDER", hz=900, res=0.3, keytrack=0.4, env=0.35)
    fsat(p, "DIODE", drive=0.55)
    p.feedback(amount=0.18, drive=0.6, tone=0.4)
    p.env(1, a=0.002, d=0.5, s=0.85, r=0.08)
    p.env(2, a=0.001, d=0.3, s=0.35, r=0.1)
    mono(p)
    velocity(p, 0.4, 0.18)
    p.mod("VELOCITY", "FSAT_DRIVE", 0.25)
    p.tone("CUTOFF", 0.16)
    p.set("macro2", 0.3)
    drift(p, 1, 0.45, [("FB_TONE", 0.15), ("CUTOFF", 0.04)])
    p.eq(mid=1.5, mid_hz=700, high=-2, high_hz=5000)
    dry_space(p)
    grit(p, mode="DIODE", drive=0.5, tone=0.4, amount=0.45, base=0.3)
    p.doc("A fat analog ladder saw driven through a diode stage and its own filter loop: rich first, then burning",
          "E0–E2", "Industrial rock, electro, dark pop", "Riffs and held notes", "FOREGROUND",
          "Pitch stays clear because the drive sits after the filter; the sub is untouched")
    out.append(p)

    # 09 PREDATOR
    p = B("PREDATOR", "ANALOG", "NS GRINDSTONE")
    p.osc(0, level=0.65, wt=0.85)
    p.osc(1, level=0.0, wt=0.6, octave=1)
    foundation(p, 0.55)
    p.insert(1, "FOLD", amount=0.0, mix=0.7)
    p.filter("LP24", hz=380, res=0.2, keytrack=0.4, env=0.2)
    p.feedback(amount=0.0, drive=0.6, tone=0.45)
    p.env(1, a=0.002, d=0.5, s=0.85, r=0.08)
    p.env(2, a=0.001, d=0.25, s=0.3, r=0.1)
    mono(p)
    velocity(p, 0.5, 0.28)
    p.mod("MODWHEEL", "CUTOFF", 0.35)
    p.mod("MODWHEEL", "RES", 0.3)
    p.mod("MODWHEEL", "B_LEVEL", 0.4)
    p.mod("MODWHEEL", "INS1_AMOUNT", 0.55)
    p.mod("MODWHEEL", "FEEDBACK", 0.3)
    p.mod("MODWHEEL", "DIST_MIX", 0.4)
    p.mod("MODWHEEL", "MASTER", -0.15)
    p.tone("CUTOFF", 0.16)
    p.set("macro2", 0.3)
    p.lfo(1, "TRIANGLE", hz=0.6, mode="TRIG")
    p.motion("LFO1", "A_WTPOS", 0.3)
    p.motion("LFO1", "CUTOFF", 0.08)
    dry_space(p)
    grit(p, mode="TUBE", drive=0.5, tone=0.45, amount=0.35, base=0.1)
    p.set("b.wtpos", 0.0)
    p.mod("MODWHEEL", "B_WTPOS", 0.7)
    p.set("dist.mix", 0.16)
    p.doc("A restrained verse bass that the mod wheel turns into a chorus monster: resonance, a growl layer, a fold and a feedback loop",
          "E0–E2", "Dark pop, industrial, trailers", "Ride the mod wheel between sections", "FOREGROUND",
          "Level is compensated as the wheel rises, so the change is character, not volume")
    out.append(p)

    # 10 DEAD CURRENT
    p = B("DEAD CURRENT", "NS FRACTURE", "ANALOG")
    p.osc(0, level=0.6, wt=0.5)
    p.osc(1, level=0.36, wt=0.95)
    foundation(p, 0.6)
    p.insert(1, "RING", after=True, amount=0.45, freq=0.9, mix=0.18)
    p.insert(2, "BITCRUSH", after=True, amount=0.5, mix=0.15)
    p.filter("LP24", hz=800, res=0.28, keytrack=0.5, env=0.3)
    p.env(1, a=0.002, d=0.5, s=0.85, r=0.08)
    p.env(2, a=0.001, d=0.25, s=0.3, r=0.1)
    mono(p)
    velocity(p, 0.4, 0.16)
    p.lfo(1, "SAMPLE_HOLD", hz=11.0, mode="FREE", smooth=True)
    p.lfo(2, "SMOOTH_RANDOM", hz=0.6, mode="FREE")
    p.set("macro2", 0.35)
    p.mod("LFO1", "INS1_FREQ", 0.03, aux="LFO2")
    p.motion("LFO1", "INS2_AMOUNT", 0.2)
    p.tone("CUTOFF", 0.16)
    dry_space(p)
    grit(p, mode="DIODE", drive=0.45, tone=0.45, amount=0.4, base=0.2)
    p.set("a.wtpos", 0.25)
    p.motion("LFO2", "A_WTPOS", 0.2)
    p.motion("LFO1", "CUTOFF", 0.12)
    p.doc("Electricity arcing in the upper harmonics, a ring and a crush that spit and settle, over a sub that never flinches",
          "E0–E2", "Industrial, dark techno, cyberpunk scores", "Held notes and slow riffs", "FOREGROUND",
          "The arcing is gated by a slow random so it comes in bursts; MOTION 0 grounds it")
    out.append(p)

    # 11 CRUSH DEPTH
    p = B("CRUSH DEPTH", "NS RADIANT", "BASIC")
    p.osc(0, level=0.66, wt=0.3)
    p.osc(1, level=0.0, wt=0.0)
    foundation(p, 0.42)
    p.insert(1, "RECTIFY", amount=0.4, mix=0.35)
    p.filter("LP24", hz=900, res=0.15, keytrack=0.5, env=0.2)
    fsat(p, "SOFT", drive=0.4)
    p.env(1, a=0.002, d=0.5, s=0.88, r=0.08)
    p.env(2, a=0.001, d=0.2, s=0.4, r=0.1)
    mono(p)
    velocity(p, 0.4, 0.16)
    p.comp(mode="MULTIBAND", threshold=0.45, ratio=0.5, attack=0.3, release=0.35, gain=0.1, depth=0.6, mix=1.0)
    p.eq(low=-1.5, low_hz=45, mid=2.0, mid_hz=180, q=0.5)
    p.tone("A_WTPOS", 0.2)
    p.set("macro2", 0.3)
    drift(p, 1, 0.5, [("A_WTPOS", 0.12)])
    dry_space(p)
    grit(p, mode="TUBE", drive=0.45, tone=0.4, amount=0.4, base=0.18)
    p.set("a.wtpos", 0.35)
    p.doc("Depth made of harmonics: a rectified octave and a dense 180 Hz body, multiband-compressed, with the real sub held back",
          "E0–E2", "Dark pop, trap-leaning alt, industrial", "Long 808-style notes and roots", "FOREGROUND",
          "Reads as huge on a laptop because the size lives at 90–400 Hz; the sine under it is modest on purpose")
    out.append(p)

    # 12 BODY BAG
    p = B("BODY BAG", "NS OBSIDIAN", "ANALOG")
    p.osc(0, level=0.62, wt=0.45)
    p.osc(1, level=0.3, wt=1.0, semi=12, fine=-9)
    foundation(p, 0.5)
    p.insert(1, "FOLD", amount=0.3, mix=0.5)
    p.filter("LP24", hz=950, res=0.2, keytrack=0.5, env=0.3, drive=0.4)
    p.env(1, a=0.002, d=0.5, s=0.85, r=0.07)
    p.env(2, a=0.001, d=0.18, s=0.35, r=0.08)
    punch(p, 0.3)
    mono(p)
    velocity(p, 0.4, 0.16)
    p.tone("CUTOFF", 0.16)
    p.set("macro2", 0.3)
    drift(p, 1, 0.8, [("A_WTPOS", 0.15)])
    dry_space(p)
    grit(p, mode="HARD", drive=0.45, tone=0.4, amount=0.4, base=0.3)
    p.set("a.wtpos", 0.55)
    p.fxfilter(type="HP", cut=0.04, res=0.0, mix=1.0)
    p.doc("Blunt and ugly in the right way: a growl table and a sour octave saw, crushed together by the filter drive",
          "E0–E3", "Alt-electronic, noise pop, industrial", "Melodic riffs", "FOREGROUND",
          "The octave saw is 9 cents flat on purpose; it is the abrasion. Pitch still reads clearly")
    out.append(p)

    # 13 SERVO
    p = B("SERVO", "PWM", "BASIC")
    p.osc(0, level=0.66, wt=0.25)
    p.osc(1, level=0.2, wt=0.0, octave=1)
    foundation(p, 0.5)
    p.insert(1, "SHIFT", after=True, amount=1.0, freq=0.54, mix=0.12)
    p.filter("LADDER", hz=650, res=0.32, keytrack=0.5, env=0.45)
    ladder(p, two_pole=False, bass_loss=0.0)
    p.env(1, a=0.001, d=0.25, s=0.6, r=0.05)
    p.env(2, a=0.001, d=0.12, s=0.2, r=0.06)
    p.env(3, a=0.001, d=0.18, s=0.0, r=0.05)
    p.mod("ENV3", "A_WARP", 0.25)
    p.set("a.warpmode", 5)
    punch(p, 0.5)
    mono(p, glide=0.0, legato=False)
    velocity(p, 0.45, 0.18)
    p.lfo(1, "TRIANGLE", hz=7.1, mode="TRIG")
    p.set("macro2", 0.3)
    p.motion("LFO1", "INS1_FREQ", 0.006)
    p.motion("LFO1", "CUTOFF", 0.03)
    p.tone("CUTOFF", 0.16)
    dry_space(p)
    grit(p, mode="DIODE", drive=0.4, tone=0.5, amount=0.4, base=0.18)
    p.set("b.warpmode", 8)
    p.set("b.warp", 0.3)
    p.set("b.level", 0.2)
    p.doc("Tight and articulate: every note has a servo whine in the pulse width and a faint motor shimmer",
          "E0–E2", "EBM, electro, industrial pop", "Precise sixteenths", "RHYTHM",
          "Short envelopes and no legato: fast lines stay separated")
    out.append(p)

    # 14 BRUTE ANGEL
    p = B("BRUTE ANGEL", "BASIC", "NS TENDON")
    p.osc(0, level=0.62, wt=0.0)
    p.osc(1, level=0.34, wt=0.7, octave=1)
    foundation(p, 0.35)
    p.insert(2, "FOLD", after=True, amount=0.55, mix=0.9)
    p.filter("LP24", hz=900, res=0.2, keytrack=0.5, env=0.2)
    p.route_filter(a=False, b=True)
    fsat(p, "HARD", drive=0.5)
    p.env(1, a=0.002, d=0.5, s=0.88, r=0.08)
    p.env(2, a=0.001, d=0.25, s=0.4, r=0.1)
    mono(p)
    velocity(p, 0.4, 0.1)
    p.mod("VELOCITY", "B_LEVEL", 0.2)
    p.tone("CUTOFF", 0.16)
    p.set("macro2", 0.3)
    drift(p, 1, 0.7, [("B_WTPOS", 0.2)])
    p.eq(mid=-2, mid_hz=400, q=0.5)
    dry_space(p)
    grit(p, mode="HARD", drive=0.5, tone=0.4, amount=0.4, base=0.2)
    p.set("b.wtpos", 0.6)
    p.mod("MODWHEEL", "B_WTPOS", 0.35)
    p.eq(mid=-2, mid_hz=400, q=0.5, high=-8, high_hz=5000)
    p.doc("Two basses at once: a perfectly round sine and, an octave up, a folded growl with nothing polite about it",
          "E0–E2", "Industrial pop, dark pop, trailers", "Roots and slow riffs", "FOREGROUND",
          "The sine bypasses the filter; the scoop at 400 Hz keeps the two layers from blurring")
    out.append(p)

    # 15 GRAVITY WELL
    p = B("GRAVITY WELL", "ANALOG", "HARMONIC_SWEEP")
    p.osc(0, level=0.55, wt=0.8)
    p.osc(1, level=0.34, wt=0.15, octave=1)
    foundation(p, 0.4)
    p.insert(1, "SINE", amount=0.3, mix=0.5)
    p.filter("LP24", hz=520, res=0.2, keytrack=0.45, env=0.2)
    fsat(p, "SOFT", drive=0.4)
    p.env(1, a=0.003, d=0.6, s=0.9, r=0.1)
    p.env(2, a=0.001, d=0.3, s=0.4, r=0.1)
    mono(p)
    velocity(p, 0.4, 0.14)
    p.eq(low=-2, low_hz=40, mid=1.5, mid_hz=130, q=0.5)
    p.tone("CUTOFF", 0.16)
    p.set("macro2", 0.25)
    drift(p, 1, 0.3, [("B_WTPOS", 0.15)])
    dry_space(p)
    grit(p, mode="TUBE", drive=0.4, tone=0.4, amount=0.35, base=0.15)
    p.set("a.warpmode", 9)
    p.set("a.warp", 0.15)
    p.motion("LFO1", "CUTOFF", 0.12)
    p.fxfilter(type="HP", cut=0.04, res=0.0, mix=1.0)
    p.doc("Enormous weight implied by the 2nd and 3rd harmonics, with the true sub trimmed so it never swamps the mix",
          "E0–E2", "Dark pop, film, trap-adjacent", "Held roots", "FOREGROUND",
          "Sounds bigger than it measures: the low shelf is already cut at 40 Hz")
    out.append(p)

    # 16 CORRUPTED DNA
    p = B("CORRUPTED DNA", "NS DUST ORACLE", "ANALOG")
    p.osc(0, level=0.6, wt=0.3)
    p.osc(1, level=0.32, wt=0.9, octave=1)
    foundation(p, 0.55)
    p.insert(1, "SHIFT", after=True, amount=1.0, freq=0.525, mix=0.12)
    p.filter("LP24", hz=750, res=0.24, keytrack=0.45)
    p.env(1, a=0.003, d=0.6, s=0.88, r=0.08)
    mono(p)
    velocity(p, 0.4, 0.16)
    p.lfo(1, "SMOOTH_RANDOM", hz=0.47, mode="TRIG")
    p.lfo(2, "SMOOTH_RANDOM", hz=0.83, mode="TRIG")
    p.lfo(3, "SMOOTH_RANDOM", hz=0.29, mode="FREE")
    p.set("macro2", 0.4)
    p.motion("LFO1", "A_WTPOS", 0.35)
    p.motion("LFO2", "B_WTPOS", 0.3)
    p.motion("LFO3", "INS1_FREQ", 0.015)
    p.motion("LFO2", "CUTOFF", 0.04)
    p.tone("CUTOFF", 0.16)
    dry_space(p)
    grit(p, mode="TUBE", drive=0.45, tone=0.45, amount=0.4, base=0.2)
    p.set("a.wtpos", 0.3)
    p.doc("A bass whose timbre mutates while you hold it: three smooth randoms reshuffle the harmonics; pitch never wavers",
          "E0–E2", "Industrial, experimental pop, film", "Long notes and slow lines", "FOREGROUND",
          "Each note takes a different path; the shifted shimmer stays under -18 dB")
    out.append(p)

    # 17 BLACKOUT
    p = B("BLACKOUT", "ANALOG", "BASIC")
    p.osc(0, level=0.66, wt=0.9)
    p.osc(1, level=0.0)
    foundation(p, 0.58)
    p.filter("LP24", hz=600, res=0.15, keytrack=0.4, env=0.3, drive=0.35)
    fsat(p, "LIGHT", drive=0.45)
    p.env(1, a=0.001, d=0.45, s=0.8, r=0.06)
    p.env(2, a=0.001, d=0.12, s=0.3, r=0.06)
    punch(p, 0.6)
    mono(p)
    velocity(p, 0.45, 0.16)
    p.tone("CUTOFF", 0.16)
    p.set("macro2", 0.15)
    drift(p, 1, 0.3, [("CUTOFF", 0.02)])
    dry_space(p)
    grit(p, mode="TUBE", drive=0.45, tone=0.45, amount=0.4, base=0.22)
    p.set("env1.slope", -0.3)
    p.doc("Nothing wasted: a punched transient, a sine, one saw through a lightly driven filter, and tube saturation",
          "E0–E2", "Dark pop, minimal electronic, alt-R&B", "Anything; it gets out of the way", "FOREGROUND",
          "The one bass that behaves itself; use it when the song is carrying the attitude")
    out.append(p)

    # 18 BLOOD CIRCUIT
    p = B("BLOOD CIRCUIT", "ANALOG", "NS THROAT")
    p.osc(0, level=0.62, wt=0.95)
    p.osc(1, level=0.3, wt=0.4)
    foundation(p, 0.5)
    p.filter("FORMANT", hz=600, res=0.35, keytrack=0.3, mix=0.4)
    p.filter2("LP24", hz=1400, res=0.15, drive=0.35)
    p.env(1, a=0.003, d=0.5, s=0.85, r=0.08)
    p.env(2, a=0.001, d=0.2, s=0.3, r=0.1)
    mono(p)
    velocity(p, 0.4, 0.0)
    p.mod("VELOCITY", "F2_CUTOFF", 0.2)
    p.lfo(1, "SMOOTH_RANDOM", hz=1.1, mode="TRIG")
    p.lfo(2, "TRIANGLE", hz=0.35, mode="FREE")
    p.set("macro2", 0.4)
    p.motion("LFO1", "CUTOFF", 0.12)
    p.motion("LFO2", "B_WTPOS", 0.3)
    p.tone("F2_CUTOFF", 0.18)
    dry_space(p)
    grit(p, mode="SOFT", drive=0.5, tone=0.45, amount=0.45, base=0.25)
    p.set("b.wtpos", 0.4)
    p.motion("LFO2", "B_WTPOS", 0.2)
    p.fxfilter(type="HP", cut=0.04, res=0.0, mix=1.0)
    p.doc("A muscular, warm bass whose midrange flexes like it is breathing: a vowel filter wandering inside the saw",
          "E0–E2", "Alt-electronic, dark pop, electro-rock", "Riffs and held notes", "FOREGROUND",
          "The vowel lives at 400–900 Hz; carve the guitar there instead of cutting the bass")
    out.append(p)

    # 19 IMPACT DAMAGE
    p = B("IMPACT DAMAGE", "ANALOG", "DIGITAL")
    p.osc(0, level=0.66, wt=1.0)
    p.osc(1, level=0.2, wt=0.7)
    foundation(p, 0.5)
    p.insert(1, "BITCRUSH", after=True, amount=0.5, mix=0.2)
    p.filter("LP24", hz=520, res=0.28, keytrack=0.4, env=0.55)
    fsat(p, "HARD", drive=0.5)
    p.env(1, a=0.001, d=0.22, s=0.35, r=0.05)
    p.env(2, a=0.001, d=0.08, s=0.1, r=0.05)
    punch(p, 0.75)
    mono(p, glide=0.0, legato=False)
    velocity(p, 0.5, 0.2)
    p.tone("CUTOFF", 0.16)
    p.set("macro2", 0.25)
    drift(p, 1, 2.0, [("INS1_AMOUNT", 0.15)])
    dry_space(p)
    grit(p, mode="HARD", drive=0.5, tone=0.45, amount=0.4, base=0.28)
    p.set("a.warpmode", 11)
    p.set("a.warp", 0.2)
    p.mod("ENV2", "A_WARP", 0.3)
    p.motion("LFO1", "CUTOFF", 0.12)
    p.doc("Built for hard sequences: a fast punched spike, a short driven body and a crushed tail on every note",
          "E0–E2", "EBM, industrial, electro", "Sixteenth-note sequences", "RHYTHM",
          "Envelopes are short enough for 140 BPM sixteenths without smearing")
    out.append(p)

    # 20 BELOW ZERO
    p = B("BELOW ZERO", "ANALOG", "NS CATHEDRAL METAL")
    p.osc(0, level=0.62, wt=0.7)
    p.osc(1, level=0.22, wt=0.7, octave=2)
    foundation(p, 0.62)
    p.insert(2, "RING", after=True, amount=0.35, freq=0.75, mix=0.15)
    p.filter("LP24", hz=700, res=0.2, keytrack=0.5, env=0.25)
    p.filter2("HP12", hz=90)
    p.env(1, a=0.002, d=0.5, s=0.88, r=0.08)
    p.env(2, a=0.001, d=0.2, s=0.3, r=0.1)
    p.env(3, a=0.001, d=0.4, s=0.2, r=0.1)
    p.mod("ENV3", "B_LEVEL", 0.15)
    mono(p)
    velocity(p, 0.4, 0.14)
    p.mod("VELOCITY", "B_LEVEL", 0.12)
    p.tone("B_WTPOS", 0.2)
    p.set("macro2", 0.25)
    drift(p, 1, 0.4, [("B_WTPOS", 0.2)])
    dry_space(p)
    grit(p, mode="SOFT", drive=0.4, tone=0.5, amount=0.35, base=0.15)
    p.set("b.wtpos", 0.5)
    p.motion("LFO1", "CUTOFF", 0.12)
    p.doc("A huge centred low end with frost on top: glass partials two octaves up, ringing briefly on each note",
          "E0–E2", "Dark pop, electronica, film", "Roots and melodic lines", "FOREGROUND",
          "The ice is a separate layer; TONE changes its colour without touching the weight")
    out.append(p)

    # 21 HEAVY WATER
    p = B("HEAVY WATER", "ANALOG", "NS SERPENT")
    p.osc(0, level=0.6, wt=0.85)
    p.osc(1, level=0.3, wt=0.4)
    foundation(p, 0.58)
    p.filter("LP24", hz=520, res=0.28, keytrack=0.45, drive=0.0)
    p.env(1, a=0.004, d=0.6, s=0.9, r=0.1)
    mono(p, glide=0.09)
    p.set("glideAlways", 0)
    velocity(p, 0.4, 0.14)
    p.lfo(1, "SINE", hz=0.23, mode="FREE")
    p.lfo(2, "SMOOTH_RANDOM", hz=0.4, mode="FREE")
    p.set("macro2", 0.4)
    p.motion("LFO1", "CUTOFF", 0.08)
    p.motion("LFO2", "B_WTPOS", 0.35)
    p.tone("CUTOFF", 0.16)
    p.chorus(mode="SUBTLE", mix=0.12, rate=0.2, depth=0.3, width=0.2)
    dry_space(p)
    grit(p, mode="SOFT", drive=0.4, tone=0.4, amount=0.4, base=0.15)
    p.set("b.wtpos", 0.2)
    fsat(p, "SOFT", drive=0.32)
    p.fxfilter(type="HP", cut=0.04, res=0.0, mix=1.0)
    p.doc("A deep, liquid bass: slow tides in the harmonics over a still sub, and a long, smooth legato glide",
          "E0–E2", "Trip-hop, dark R&B, film", "Legato lines; overlap notes for the glide", "FOREGROUND",
          "The glide is 90 ms and only on overlapping notes, so detached lines stay clean")
    out.append(p)

    # 22 WAR MACHINE
    p = B("WAR MACHINE", "NS GRINDSTONE", "ANALOG")
    p.osc(0, level=0.6, wt=0.8)
    p.osc(1, level=0.38, wt=1.0, octave=1, unison=2, detune=0.06, width=0.15)
    foundation(p, 0.55)
    p.insert(1, "FOLD", amount=0.45, mix=0.6)
    p.filter("LP24", hz=1100, res=0.25, keytrack=0.45, env=0.3, drive=0.45)
    p.feedback(amount=0.15, drive=0.7, tone=0.4)
    p.env(1, a=0.002, d=0.5, s=0.9, r=0.07)
    p.env(2, a=0.001, d=0.2, s=0.4, r=0.08)
    punch(p, 0.3)
    mono(p)
    velocity(p, 0.4, 0.16)
    p.tone("CUTOFF", 0.16)
    p.set("macro2", 0.3)
    drift(p, 1, 0.9, [("A_WTPOS", 0.15), ("INS1_AMOUNT", 0.1)])
    grit(p, mode="HARD", drive=0.55, tone=0.45, amount=0.35, base=0.35)
    p.set("a.wtpos", 0.6)
    p.mod("VELOCITY", "A_WTPOS", 0.2)
    p.fxfilter(type="HP", cut=0.04, res=0.0, mix=1.0)
    p.doc("An industrial chorus bass: folded growl, octave saws, a driven filter loop and saturation, with no room at all",
          "E0–E2", "Industrial rock, metal-electronic, trailers", "Chorus riffs", "FOREGROUND",
          "Dense from 100 Hz to 3 kHz; give the guitars 1.5–2 kHz and it still reads")
    out.append(p)

    # 23 ROTTEN VELVET
    p = B("ROTTEN VELVET", "ANALOG", "NS FRACTURE")
    p.osc(0, level=0.64, wt=0.75)
    p.osc(1, level=0.0, wt=0.8)
    foundation(p, 0.55)
    p.insert(1, "DECIMATE", after=True, amount=0.55, mix=0.0)
    p.insert(2, "BITCRUSH", after=True, amount=0.6, mix=0.0)
    p.filter("LP24", hz=520, res=0.15, keytrack=0.4, env=0.2)
    p.env(1, a=0.003, d=0.5, s=0.88, r=0.08)
    p.env(2, a=0.001, d=0.25, s=0.35, r=0.1)
    mono(p)
    p.set("velSens", 0.25)
    p.mod("VELOCITY", "B_LEVEL", 0.35, curve=0.4)
    p.set("ins1.mix", 0.12)
    p.set("ins2.mix", 0.1)
    p.mod("VELOCITY", "INS1_AMOUNT", 0.3, curve=0.4)
    p.mod("MODWHEEL", "INS2_AMOUNT", 0.35)
    p.mod("MODWHEEL", "B_LEVEL", 0.25)
    p.mod("VELOCITY", "CUTOFF", 0.2)
    p.tone("CUTOFF", 0.16)
    p.set("macro2", 0.25)
    drift(p, 1, 0.5, [("B_WTPOS", 0.2)])
    dry_space(p)
    grit(p, mode="SOFT", drive=0.4, tone=0.4, amount=0.4, base=0.1)
    p.set("b.wtpos", 0.5)
    p.mod("MODWHEEL", "B_WTPOS", 0.4)
    p.set("dist.mix", 0.16)
    p.motion("LFO1", "CUTOFF", 0.12)
    p.doc("Smooth and expensive on top, rotten underneath: a digital, decimated layer that velocity and the mod wheel pull into view",
          "E0–E2", "Dark R&B, dark pop, alt-electronic", "Soft verses, hard choruses", "FOREGROUND",
          "At low velocity it could pass for a clean analog bass; that is the point")
    out.append(p)

    # 24 PANIC ENGINE
    p = B("PANIC ENGINE", "ANALOG", "SYNC_SWEEP")
    p.osc(0, level=0.62, wt=0.9)
    p.osc(1, level=0.3, wt=0.5)
    foundation(p, 0.55)
    p.insert(1, "RING", after=True, amount=0.3, freq=0.62, mix=0.0)
    p.filter("LP24", hz=650, res=0.25, keytrack=0.45, env=0.3)
    p.feedback(amount=0.05, drive=0.6, tone=0.5)
    p.env(1, a=0.002, d=0.5, s=0.85, r=0.08)
    p.env(2, a=0.001, d=0.2, s=0.3, r=0.1)
    mono(p)
    velocity(p, 0.4, 0.16)
    p.lfo(1, "SAMPLE_HOLD", sync="1/16", mode="FREE", smooth=True)
    p.lfo(2, "TRIANGLE", hz=6.5, mode="TRIG")
    p.set("macro2", 0.3)
    p.mod("MODWHEEL", "B_WTPOS", 0.4)
    p.mod("LFO1", "B_WTPOS", 0.35, aux="MODWHEEL")
    p.mod("LFO1", "CUTOFF", 0.15, aux="MODWHEEL")
    p.mod("LFO2", "PITCH", 0.004, aux="MODWHEEL")
    p.mod("MODWHEEL", "FEEDBACK", 0.3)
    p.mod("MODWHEEL", "INS1_AMOUNT", 0.3)
    p.set("ins1.mix", 0.25)
    p.motion("LFO2", "B_WARP", 0.1)
    p.tone("CUTOFF", 0.16)
    dry_space(p)
    grit(p, mode="DIODE", drive=0.5, tone=0.45, amount=0.4, base=0.2)
    p.performer(1, {0: [(0.0, "HOLD"), (0.6, "DECAY"), (0.0, "HOLD"), (0.9, "PULSE"), (0.0, "HOLD"), (0.0, "HOLD"), (0.5, "DECAY"), (1.0, "PULSE"), (0.0, "HOLD"), (0.7, "DECAY"), (0.0, "HOLD"), (0.0, "HOLD"), (0.8, "PULSE"), (0.0, "HOLD"), (0.4, "DECAY"), (1.0, "PULSE")]}, mode="SONG", rate="1/16")
    p.mod("PERF1", "INS1_AMOUNT", 0.5, aux="MODWHEEL")
    p.motion("LFO1", "CUTOFF", 0.1)
    p.set("b.warpmode", 1)
    p.doc("Useful as it stands; the mod wheel wakes the panic: sixteenth-note sync spasms, a ring, feedback and a pitch shiver",
          "E0–E2", "Industrial, breakbeat, cyberpunk", "Ride the wheel into drops and fills", "FOREGROUND",
          "Everything chaotic is scaled by the wheel, so at 0 it is a clean, driven sync bass")
    out.append(p)

    # 25 GOD BELOW: the flagship bass.
    p = B("GOD BELOW", "ANALOG", "NS TENDON")
    p.osc(0, level=0.6, wt=1.0, unison=2, detune=0.04, width=0.08)
    p.osc(1, level=0.3, wt=0.3, octave=1, fine=-4)
    foundation(p, 0.6)
    p.noise(0.04, type="BROWN", color=0.3, keytrack=False)
    p.insert(1, "FOLD", amount=0.3, mix=0.55)
    p.insert(2, "SINE", after=True, amount=0.25, mix=0.25)
    p.filter("LADDER", hz=620, res=0.3, keytrack=0.45, env=0.4)
    fsat(p, "DIODE", drive=0.45)
    p.feedback(amount=0.12, drive=0.6, tone=0.4)
    p.env(1, a=0.001, d=0.6, s=0.88, r=0.08)
    p.env(2, a=0.001, d=0.3, s=0.35, r=0.1)
    p.env(3, a=0.001, d=0.05, s=0.0, r=0.03)
    p.mod("ENV3", "A_PITCH", 0.02)
    punch(p, 0.3)
    mono(p)
    velocity(p, 0.4, 0.2)
    p.mod("VELOCITY", "INS1_AMOUNT", 0.2)
    p.mod("MODWHEEL", "RES", 0.25)
    p.mod("MODWHEEL", "B_WTPOS", 0.5)
    p.mod("MODWHEEL", "FEEDBACK", 0.2)
    p.mod("PRESSURE", "CUTOFF", 0.15)
    p.tone("CUTOFF", 0.16)
    p.set("macro2", 0.3)
    drift(p, 1, 0.45, [("B_WTPOS", 0.18), ("INS2_AMOUNT", 0.1)])
    dry_space(p)
    grit(p, mode="TUBE", drive=0.55, tone=0.45, amount=0.35, base=0.3)
    p.set("b.wtpos", 0.25)
    p.mod("TIMBRE", "B_WTPOS", 0.4)
    p.fxfilter(type="HP", cut=0.04, res=0.0, mix=1.0)
    p.doc("The flagship bass: a punched, pitch-kicked attack, an unshakeable sine, a ladder saw pair folded and diode-driven, a growl layer the wheel opens",
          "E0–E2", "Industrial, dark pop, trailers, anything that needs a floor", "One note is enough; the wheel and pressure make it perform",
          "FOREGROUND", "Below 100 Hz it is one clean centred sine; everything dangerous is above that")
    out.append(p)

    return out
