from lunatk import Preset
from bank._common import echo, grit, space, velocity


def A(name, a="ANALOG", b="ANALOG"):
    return Preset(name, "ARP", a, b)


def bed(p, voices=8, vel=0.5):
    return p.voice(voices=voices, glide=0.0, vel=vel, bend=2)


def hall(p, mix=0.14, decay=0.3, amount=0.18):
    return space(p, mix, mode="HALL", size=0.5, decay=decay, damp=0.55, predelay=0.1, width=0.8, amount=amount)


def plate(p, mix=0.12, decay=0.3, amount=0.15):
    return space(p, mix, mode="PLATE", size=0.4, decay=decay, damp=0.5, predelay=0.08, width=0.75, amount=amount)


def presets():
    """Arpeggiated sounds. Hold a chord and the arpeggiator plays it in time
    with the song. Turning ARP off leaves a playable pluck or stab. The
    arpeggiator starts on the first key, so start chords on the beat.

    Every LFO here runs FREE: each arp step starts a new voice, so a TRIG
    LFO would restart on every step and never get past its first moment."""
    out = []

    p = A("RUST LADDER", "ANALOG", "ANALOG")
    p.osc(0, level=0.6, wt=0.95, unison=2, detune=0.07, width=0.3)
    p.osc(1, level=0.3, wt=0.5, octave=-1)
    p.filter("LP24", hz=700, res=0.28, keytrack=0.5, env=0.38)
    p.filter2("HP12", hz=150)
    p.env(1, a=0.001, d=0.22, s=0.15, r=0.1)
    p.env(2, a=0.001, d=0.14, s=0.0, r=0.1)
    p.arp("UP", rate="1/16", octaves=2, gate=0.5)
    bed(p)
    velocity(p, 0.5, 0.12)
    p.tone("CUTOFF", 0.18)
    p.lfo(1, "TRIANGLE", sync="2 BAR", mode="FREE")
    p.set("macro2", 0.45)
    p.motion("LFO1", "CUTOFF", 0.14)
    echo(p, time="3/16", mix=0.1, feedback=0.25, amount=0.12)
    plate(p)
    grit(p, mode="TUBE", drive=0.45, tone=0.5, amount=0.45)
    p.master(0.6)
    p.doc("Rising 1/16 saw arpeggio over two octaves with a squelchy filter", "C3–C5", "Techno, industrial, EBM, synthwave",
          "Hold three- or four-note chords, a bar each", "RHYTHM",
          "The filter climbs over two bars at default MOTION; pull MOTION to 0 for a steady line under a vocal")
    out.append(p)

    p = A("SIGNAL DESCENT", "PWM", "ANALOG")
    p.osc(0, level=0.6, wt=0.35)
    p.osc(1, level=0.25, wt=0.9, fine=0.04)
    p.filter("LP12", hz=1600, res=0.15, keytrack=0.5, env=0.25)
    p.filter2("HP12", hz=200)
    p.env(1, a=0.001, d=0.3, s=0.1, r=0.12)
    p.env(2, a=0.001, d=0.18, s=0.0, r=0.1)
    p.arp("DOWN", rate="1/16", octaves=1, gate=0.6)
    bed(p)
    velocity(p, 0.5, 0.1)
    p.tone("CUTOFF", 0.16)
    p.lfo(1, "SINE", sync="1 BAR", mode="FREE")
    p.set("macro2", 0.4)
    p.motion("LFO1", "A_WTPOS", 0.25)
    echo(p, time="1/8", mix=0.1, feedback=0.2, amount=0.1, pingpong=True)
    plate(p)
    grit(p, mode="SOFT", drive=0.35, tone=0.5, amount=0.4)
    p.master(0.6)
    p.doc("Falling pulse-wave 1/16 arpeggio, hollow and nasal", "C3–C5", "Synthwave, darkwave, electro, film",
          "Hold chords; the notes fall from the top of the chord", "RHYTHM",
          "Pulse width moves once a bar; MOTION 0 fixes it. Cut 2–3 kHz a touch if it fights a vocal")
    out.append(p)

    p = A("GLASS STAIRWELL", "GLASS", "FM_BELL")
    p.osc(0, level=0.55, wt=0.3)
    p.osc(1, level=0.25, wt=0.25, octave=1)
    p.filter("LP12", hz=6000, res=0.05, keytrack=0.3)
    p.filter2("HP12", hz=260)
    p.env(1, a=0.001, d=0.55, s=0.0, r=0.35)
    p.arp("UPDOWN", rate="1/8", octaves=3, gate=0.7)
    bed(p)
    velocity(p, 0.5, 0.05)
    p.tone("A_WTPOS", 0.18)
    p.lfo(1, "SINE", sync="4 BAR", mode="FREE")
    p.set("macro2", 0.4)
    p.motion("LFO1", "A_WTPOS", 0.2)
    p.motion("LFO1", "B_LEVEL", 0.15)
    echo(p, time="3/16", mix=0.16, feedback=0.3, amount=0.14, pingpong=True)
    hall(p, mix=0.16)
    grit(p, mode="SOFT", drive=0.3, tone=0.5, amount=0.35)
    p.eq(high=-3, high_hz=9000)
    p.master(0.6)
    p.doc("Glass bells climbing and falling across three octaves in eighths", "C3–C4 (it climbs from there)",
          "Cinematic, ambient, downtempo, game menus", "Hold small chords low; three octaves climb fast", "TEXTURE",
          "The top octave gets bright: TONE down or play lower if it pokes above the hats")
    out.append(p)

    p = A("THIRD RAIL", "ANALOG", "PWM")
    p.osc(0, level=0.6, wt=0.9, unison=2, detune=0.06, width=0.3)
    p.osc(1, level=0.25, wt=0.5, octave=1)
    p.filter("LP24", hz=1300, res=0.2, keytrack=0.5, env=0.22)
    p.filter2("HP12", hz=180)
    p.env(1, a=0.002, d=0.35, s=0.4, r=0.12)
    p.env(2, a=0.001, d=0.16, s=0.0, r=0.1)
    p.arp("UP", rate="3/16", octaves=2, gate=0.7)
    bed(p)
    velocity(p, 0.5, 0.12)
    p.tone("CUTOFF", 0.18)
    p.lfo(1, "SAW_UP", sync="1 BAR", mode="FREE", smooth=True)
    p.set("macro2", 0.4)
    p.motion("LFO1", "CUTOFF", 0.12)
    echo(p, time="1/8", mix=0.1, feedback=0.2, amount=0.1)
    plate(p)
    grit(p, mode="HARD", drive=0.3, tone=0.45, amount=0.4)
    p.master(0.6)
    p.doc("Dotted-eighth arpeggio that rolls across the bar line against a straight beat", "C3–C5",
          "Progressive house, melodic techno, synthwave", "Hold chords for a bar or two; the 3-against-4 does the work",
          "RHYTHM", "The filter opens across each bar; MOTION 0 stops it. Keep the delay short so the dots stay clear")
    out.append(p)

    p = A("CORRODED CLOCK", "DIGITAL", "BASIC")
    p.osc(0, level=0.55, wt=0.4)
    p.osc(1, level=0.25, wt=0.66, octave=-1)
    p.filter("LP12", hz=3200, res=0.12, keytrack=0.4, env=0.2)
    p.filter2("HP12", hz=220)
    p.env(1, a=0.001, d=0.18, s=0.0, r=0.1)
    p.env(2, a=0.001, d=0.1, s=0.0, r=0.1)
    p.arp("PLAYED", rate="1/16", octaves=1, gate=0.45, swing=0.2)
    bed(p)
    velocity(p, 0.55, 0.1)
    p.tone("CUTOFF", 0.16)
    p.lfo(1, "SAMPLE_HOLD", sync="1/8", mode="FREE")
    p.set("macro2", 0.35)
    p.motion("LFO1", "A_WTPOS", 0.35)
    p.motion("LFO1", "CUTOFF", 0.08)
    p.dist(mode="DOWNSAMPLE", drive=0.25, tone=0.5, mix=0.25)
    p.grit(("DIST_MIX", 0.45), ("DIST_DRIVE", 0.2))
    plate(p, mix=0.1)
    p.master(0.6)
    p.doc("Downsampled digital arpeggio with a stepped timbre per eighth", "C3–C5", "IDM, industrial, glitch, lo-fi electronica",
          "Play the chord a note at a time, in the order you want it", "RHYTHM",
          "The timbre jumps in time with the song, not at random rates; MOTION 0 holds one tone. GRIT crunches it further")
    out.append(p)

    p = A("NEON SPINE", "ANALOG", "ANALOG")
    p.osc(0, level=0.55, wt=0.95, unison=5, detune=0.14, width=0.5)
    p.osc(1, level=0.3, wt=0.9, octave=1, unison=3, detune=0.1, width=0.4)
    p.filter("LP24", hz=2400, res=0.1, keytrack=0.4, env=0.25)
    p.filter2("HP12", hz=200)
    p.env(1, a=0.001, d=0.3, s=0.3, r=0.12)
    p.env(2, a=0.001, d=0.2, s=0.0, r=0.1)
    p.arp("UP", rate="1/16", octaves=1, gate=0.6)
    bed(p)
    velocity(p, 0.45, 0.1)
    p.tone("CUTOFF", 0.16)
    p.lfo(1, "TRIANGLE", sync="2 BAR", mode="FREE")
    p.set("macro2", 0.45)
    p.motion("LFO1", "CUTOFF", 0.14)
    p.motion("LFO1", "A_DETUNE", 0.15)
    echo(p, time="3/16", mix=0.12, feedback=0.3, amount=0.12, pingpong=True)
    hall(p, mix=0.14)
    grit(p, mode="SOFT", drive=0.35, tone=0.55, amount=0.35)
    p.master(0.58)
    p.doc("Supersaw 1/16 arpeggio that opens and spreads over two bars", "C3–C5", "Trance, big-room, progressive, synthwave",
          "Hold chords on the downbeat", "RHYTHM",
          "Sidechain it to the kick for the classic pump. MOTION 0 stops the sweep; high-pass it higher under a busy top line")
    out.append(p)

    p = A("BELL DIVISION", "FM_BELL", "GLASS")
    p.osc(0, level=0.55, wt=0.4)
    p.osc(1, level=0.2, wt=0.3, octave=1)
    p.filter("LP12", hz=5000, res=0.05, keytrack=0.3)
    p.filter2("HP12", hz=250)
    p.env(1, a=0.001, d=0.45, s=0.0, r=0.3)
    p.arp("CHORD", rate="1/8", octaves=2, gate=0.5)
    bed(p)
    velocity(p, 0.5, 0.05)
    p.tone("A_WTPOS", 0.15)
    p.lfo(1, "SINE", sync="2 BAR", mode="FREE")
    p.set("macro2", 0.4)
    p.motion("LFO1", "A_WTPOS", 0.2)
    echo(p, time="3/16", mix=0.14, feedback=0.25, amount=0.12)
    hall(p, mix=0.14)
    grit(p, mode="SOFT", drive=0.3, tone=0.5, amount=0.35)
    p.eq(high=-2, high_hz=9000)
    p.master(0.58)
    p.doc("Whole-chord bell stabs in eighths, jumping an octave every other hit", "C3–C5", "Future garage, cinematic, pop, game",
          "Hold chords; each hit plays the whole chord", "RHYTHM",
          "Chords are dense: voice them in three notes. The bell tone moves over two bars; MOTION 0 fixes it")
    out.append(p)

    p = A("VOID STEPS", "VOID_FOLD", "ANALOG")
    p.osc(0, level=0.55, wt=0.3, warp="FOLD", warp_amt=0.15)
    p.osc(1, level=0.2, wt=0.6, octave=-1)
    p.filter("LP24", hz=1800, res=0.18, keytrack=0.5, env=0.2)
    p.filter2("HP12", hz=180)
    p.env(1, a=0.001, d=0.32, s=0.1, r=0.15)
    p.env(2, a=0.001, d=0.2, s=0.0, r=0.1)
    p.arp("DOWN", rate="1/8", octaves=2, gate=0.65)
    bed(p)
    velocity(p, 0.5, 0.1)
    p.tone("CUTOFF", 0.16)
    p.lfo(1, "TRIANGLE", sync="1 BAR", mode="FREE")
    p.set("macro2", 0.4)
    p.motion("LFO1", "A_WARP", 0.25)
    echo(p, time="3/16", mix=0.12, feedback=0.3, amount=0.12, pingpong=True)
    hall(p, mix=0.14)
    grit(p, mode="SINFOLD", drive=0.3, tone=0.45, amount=0.35)
    p.master(0.6)
    p.doc("Wavefolded eighth-note arpeggio walking down two octaves", "C3–C5", "Dark techno, industrial, horror scores",
          "Hold minor chords for a bar", "RHYTHM",
          "The fold grows and shrinks each bar; MOTION 0 holds it. It's mid-heavy, so carve 400 Hz if the mix clouds")
    out.append(p)

    p = A("COPPER SPARKS", "HARMONIC_SWEEP", "BASIC")
    p.osc(0, level=0.55, wt=0.45)
    p.osc(1, level=0.2, wt=0.0, octave=1)
    p.filter("LP12", hz=5000, res=0.08, keytrack=0.3, env=0.15)
    p.filter2("HP12", hz=300)
    p.env(1, a=0.001, d=0.12, s=0.0, r=0.08)
    p.env(2, a=0.001, d=0.08, s=0.0, r=0.08)
    p.arp("UP", rate="1/32", octaves=2, gate=0.35)
    bed(p)
    velocity(p, 0.5, 0.12)
    p.tone("CUTOFF", 0.16)
    p.lfo(1, "SINE", sync="1 BAR", mode="FREE")
    p.set("macro2", 0.4)
    p.motion("LFO1", "A_WTPOS", 0.2)
    plate(p, mix=0.12)
    grit(p, mode="SOFT", drive=0.3, tone=0.5, amount=0.35)
    p.eq(high=-3, high_hz=9000)
    p.master(0.56)
    p.doc("Fast 1/32 shimmer: the chord blurs into a bright metallic ripple", "C3–C5", "Trance breakdowns, cinematic, ambient pop",
          "Hold chords under a slower part; it reads as texture, not notes", "TEXTURE",
          "Sits above the hats; TONE down or high-shelf it if it crowds the cymbals")
    out.append(p)

    p = A("SLOW HALO", "CHOIR", "ANALOG")
    p.osc(0, level=0.5, wt=0.4, unison=3, detune=0.12, width=0.5)
    p.osc(1, level=0.3, wt=0.9, unison=2, detune=0.1, width=0.4)
    p.filter("LP24", hz=2600, res=0.08, keytrack=0.4)
    p.filter2("HP12", hz=180)
    p.env(1, a=0.04, d=0.8, s=0.4, r=0.6)
    p.arp("UPDOWN", rate="1/4", octaves=2, gate=0.9)
    bed(p)
    velocity(p, 0.45, 0.06)
    p.tone("CUTOFF", 0.15)
    p.lfo(1, "SINE", sync="4 BAR", mode="FREE")
    p.set("macro2", 0.45)
    p.motion("LFO1", "CUTOFF", 0.12)
    p.motion("LFO1", "A_WTPOS", 0.15)
    echo(p, time="3/8", mix=0.12, feedback=0.3, amount=0.12, pingpong=True)
    hall(p, mix=0.2, decay=0.34)
    grit(p, mode="SOFT", drive=0.3, tone=0.55, amount=0.3)
    p.master(0.58)
    p.doc("Slow quarter-note arpeggio of breathy voices, somewhere between a pad and a melody", "C3–C5",
          "Film, ambient, post-rock, slow pop", "Hold chords for a bar or more", "SUPPORT",
          "Long release overlaps the notes into a pad; shorten SPACE if it smears the downbeat")
    out.append(p)

    p = A("DUST CYCLE", "ANALOG", "PWM")
    p.osc(0, level=0.55, wt=0.6)
    p.osc(1, level=0.25, wt=0.3, fine=-0.05)
    p.noise(0.04, type="VINYL", color=0.4, keytrack=False)
    p.filter("LP12", hz=2400, res=0.1, keytrack=0.4, env=0.2)
    p.filter2("HP12", hz=220)
    p.env(1, a=0.001, d=0.3, s=0.0, r=0.15)
    p.env(2, a=0.001, d=0.15, s=0.0, r=0.1)
    p.arp("PLAYED", rate="1/16", octaves=1, gate=0.5, swing=0.3)
    bed(p)
    velocity(p, 0.55, 0.1)
    p.tone("CUTOFF", 0.16)
    p.lfo(1, "SINE", hz=0.35, mode="FREE")
    p.set("macro2", 0.35)
    p.motion("LFO1", "A_FINE", 0.04)
    p.motion("LFO1", "CUTOFF", 0.06)
    echo(p, time="1/8", mix=0.08, feedback=0.2, amount=0.1)
    plate(p, mix=0.1)
    grit(p, mode="TUBE", drive=0.35, tone=0.45, amount=0.35)
    p.master(0.6)
    p.doc("Swung, dusty 1/16 arpeggio with slight tape wobble", "C3–C5", "Lo-fi hip-hop, downtempo, UK garage, bedroom pop",
          "Play chords note by note in the order you want them", "RHYTHM",
          "The wobble is gentle and MOTION 0 removes it. Swing is 30%; set your drums to match")
    out.append(p)

    p = A("WIRE HARP", "SPECTRAL_COMB", "GLASS")
    p.osc(0, level=0.5, wt=0.35)
    p.osc(1, level=0.25, wt=0.4, octave=1)
    p.filter("LP12", hz=4500, res=0.08, keytrack=0.4, env=0.2)
    p.filter2("HP12", hz=260)
    p.env(1, a=0.001, d=0.4, s=0.0, r=0.3)
    p.env(2, a=0.001, d=0.2, s=0.0, r=0.1)
    p.arp("UP", rate="1/16", octaves=3, gate=0.7)
    bed(p)
    velocity(p, 0.5, 0.1)
    p.tone("A_WTPOS", 0.16)
    p.lfo(1, "TRIANGLE", sync="2 BAR", mode="FREE")
    p.set("macro2", 0.4)
    p.motion("LFO1", "A_WTPOS", 0.2)
    echo(p, time="3/16", mix=0.14, feedback=0.3, amount=0.12, pingpong=True)
    hall(p, mix=0.16)
    grit(p, mode="SOFT", drive=0.3, tone=0.5, amount=0.35)
    p.eq(high=-3, high_hz=9000)
    p.master(0.58)
    p.doc("Steely harp runs up three octaves in sixteenths", "C3–C4 (it climbs from there)", "Cinematic, fantasy, game, ambient",
          "Hold small chords low", "FOREGROUND",
          "A three-octave run covers a lot of range: hold two- or three-note chords and TONE down if the top gets glassy")
    out.append(p)

    p = A("STATIC ORACLE", "FORMANT", "ANALOG")
    p.osc(0, level=0.55, wt=0.4)
    p.osc(1, level=0.2, wt=0.9, octave=-1)
    p.filter("BP", hz=1400, res=0.2, keytrack=0.4)
    p.filter2("HP12", hz=220)
    p.env(1, a=0.001, d=0.25, s=0.05, r=0.12)
    p.arp("RANDOM", rate="1/16", octaves=1, gate=0.55)
    bed(p)
    velocity(p, 0.5, 0.1)
    p.tone("CUTOFF", 0.16)
    p.lfo(1, "SAMPLE_HOLD", sync="1/16", mode="FREE")
    p.set("macro2", 0.35)
    p.motion("LFO1", "A_WTPOS", 0.2)
    echo(p, time="3/16", mix=0.1, feedback=0.25, amount=0.1)
    plate(p, mix=0.1)
    grit(p, mode="DOWNSAMPLE", drive=0.25, tone=0.5, amount=0.35)
    p.master(0.6)
    p.doc("Vowel-filtered notes in a random order, each with its own mouth shape", "C3–C5",
          "Glitch, IDM, experimental pop, sci-fi", "Hold a chord; only its own notes play, in a random order", "TEXTURE",
          "The random order stays inside your chord and the vowel steps in time. MOTION 0 fixes the vowel")
    out.append(p)

    p = A("ROLLING STOCK", "ANALOG", "ANALOG")
    p.osc(0, level=0.6, wt=0.95)
    p.osc(1, level=0.25, wt=0.5, fine=0.05)
    p.sub(0.35, shape="SINE", octave=1)
    p.filter("LP24", hz=420, res=0.25, keytrack=0.4, env=0.35)
    p.env(1, a=0.001, d=0.2, s=0.3, r=0.08)
    p.env(2, a=0.001, d=0.12, s=0.0, r=0.08)
    p.arp("UP", rate="1/16", octaves=1, gate=0.55)
    p.voice(voices=4, glide=0.0, vel=0.5, bend=2)
    velocity(p, 0.5, 0.12)
    p.tone("CUTOFF", 0.15)
    p.lfo(1, "SINE", sync="1 BAR", mode="FREE")
    p.set("macro2", 0.4)
    p.motion("LFO1", "CUTOFF", 0.1)
    grit(p, mode="TUBE", drive=0.4, tone=0.45, amount=0.4)
    p.master(0.6)
    p.context(shift=-12, allow_low=True, pitch_note=48)
    p.doc("Rolling 1/16 bass arpeggio: root, third and fifth under the chord", "C2–C4, sub an octave under", "Techno, synthwave, electro, trance",
          "Hold two- or three-note shapes in the bass register", "RHYTHM",
          "Dry and mono in the lows; sidechain it to the kick, or play only the root for a plain rolling bass")
    out.append(p)

    p = A("HAZARD LIGHTS", "DIGITAL", "ANALOG")
    p.osc(0, level=0.5, wt=0.7)
    p.osc(1, level=0.3, wt=0.9, unison=2, detune=0.08, width=0.3)
    p.filter("LP24", hz=2800, res=0.15, keytrack=0.4, env=0.25)
    p.filter2("HP12", hz=240)
    p.env(1, a=0.001, d=0.15, s=0.0, r=0.08)
    p.env(2, a=0.001, d=0.1, s=0.0, r=0.08)
    p.arp("CHORD", rate="1/16", octaves=1, gate=0.3, swing=0.15)
    bed(p)
    velocity(p, 0.5, 0.12)
    p.tone("CUTOFF", 0.18)
    p.lfo(1, "SAW_DOWN", sync="1/4", mode="FREE", smooth=True)
    p.set("macro2", 0.4)
    p.motion("LFO1", "CUTOFF", 0.12)
    echo(p, time="3/16", mix=0.1, feedback=0.25, amount=0.1)
    plate(p, mix=0.1)
    grit(p, mode="HARD", drive=0.35, tone=0.45, amount=0.4)
    p.master(0.58)
    p.doc("Short chord stabs repeating in swung sixteenths", "C3–C5", "Industrial techno, breaks, electro, drum and bass",
          "Hold chords; the whole chord stutters", "RHYTHM",
          "Each beat opens the filter and lets it fall; MOTION 0 leaves flat stabs. Voice chords narrow so the stabs stay tight")
    out.append(p)

    p = A("CATHEDRAL MOTOR", "CHOIR", "ORGAN")
    p.osc(0, level=0.45, wt=0.5, unison=3, detune=0.1, width=0.45)
    p.osc(1, level=0.3, wt=0.4, octave=1)
    p.filter("LP24", hz=2200, res=0.1, keytrack=0.4, env=0.15)
    p.filter2("HP12", hz=200)
    p.env(1, a=0.005, d=0.4, s=0.35, r=0.3)
    p.env(2, a=0.001, d=0.25, s=0.0, r=0.2)
    p.arp("UPDOWN", rate="1/8", octaves=2, gate=0.75)
    bed(p)
    velocity(p, 0.45, 0.08)
    p.tone("CUTOFF", 0.16)
    p.lfo(1, "SINE", sync="2 BAR", mode="FREE")
    p.set("macro2", 0.4)
    p.motion("LFO1", "CUTOFF", 0.1)
    p.motion("LFO1", "B_LEVEL", 0.15)
    echo(p, time="3/16", mix=0.12, feedback=0.3, amount=0.12, pingpong=True)
    hall(p, mix=0.18, decay=0.32)
    grit(p, mode="TUBE", drive=0.3, tone=0.5, amount=0.35)
    p.master(0.58)
    p.doc("Organ and voices cycling in eighths, like a machine playing a hymn", "C3–C5",
          "Cinematic, darkwave, post-rock, trailer builds", "Hold chords for a bar; minor chords suit it", "FOREGROUND",
          "The organ octave swells over two bars; MOTION 0 fixes it. Trim SPACE when the arrangement gets dense")
    out.append(p)

    return out
