from lunatk import Preset
from bank._common import grit, velocity


def mono(p, glide=0.03, legato=True, vel_tone=0.08, vel=0.45):
    p.voice(voices=1, glide=glide, legato=legato, glide_always=False, vel=vel, bend=2)
    if vel_tone:
        p.mod("VELOCITY", "CUTOFF", vel_tone)
    return p


def dry_space(p, amount=0.22, time="1/8"):
    """Basses keep the low end dry: SPACE is a delay with its low cut high."""
    p.delay(time=time, mix=0.0, feedback=0.25, lowcut=0.8, highcut=0.45, width=0.2)
    return p.space(reverb=0, delay=amount)


def B(name, a="BASIC", b="BASIC"):
    return Preset(name, "BASS", a, b)


def presets():
    out = []

    # -- subs ---------------------------------------------------------------
    p = B("IRON SUB")
    p.osc(0, level=0.85, wt=0.06)
    p.filter("LP24", hz=900, res=0.05, keytrack=0.5)
    p.env(1, a=0.002, d=0.25, s=0.95, r=0.06)
    mono(p)
    p.tone("A_WTPOS", 0.25)
    p.pump(sync="1/4", depth=0.45, default=0.0)
    dry_space(p)
    grit(p, drive=0.4, tone=0.55, amount=0.75)
    p.master(0.7)
    p.doc("Clean sine sub under a mid bass or a kick-led groove", "E0–E2", "Techno, trap, cinematic, pop",
          "Mono lines and held roots; glides only between held notes", "SUPPORT",
          "Keep it mono and give the kick 50–60 Hz; MOTION adds a tempo pump if you have no sidechain")
    out.append(p)

    p = B("VELVET SUB")
    p.osc(0, level=0.8, wt=0.22)
    p.sub(0.35, "SINE")
    p.filter("LP12", hz=520, res=0.08, keytrack=0.6, env=0.05)
    p.env(1, a=0.004, d=0.4, s=0.85, r=0.12)
    p.env(2, a=0.002, d=0.3, s=0.0, r=0.1)
    mono(p, glide=0.05)
    p.tone("CUTOFF", 0.14)
    p.lfo(1, "SINE", hz=0.25)
    p.set("macro2", 0.4)
    p.motion("LFO1", "CUTOFF", 0.05)
    dry_space(p)
    grit(p, mode="SOFT", drive=0.35, tone=0.5, amount=0.8)
    p.master(0.7)
    p.doc("Round, warm sub-and-a-bit that still reads on small speakers", "C1–C3", "R&B, pop, neo-soul, lo-fi",
          "Legato lines with slides; plays well under chords", "SUPPORT",
          "The triangle overtone carries on phones; if it crowds a male vocal, pull TONE down a notch")
    out.append(p)

    p = B("BRAKE 808")
    p.osc(0, level=0.85, wt=0.0)
    p.sub(0.0, "SINE")
    p.set("sub.on", 0)
    p.filter("LP24", hz=3000, res=0.05, keytrack=0.3)
    p.env(1, a=0.001, d=1.6, s=0.0, r=0.25, dcurve=-0.4)
    p.env(4, a=0.001, d=0.07, s=0.0, r=0.05)
    p.set("macro2", 0.5)
    p.mod("ENV4", "PITCH", 1.0, aux="MACRO2")
    p.voice(voices=1, glide=0.08, legato=True, glide_always=False, vel=0.5, bend=12)
    p.mod("VELOCITY", "DIST_DRIVE", 0.2)
    p.tone("DIST_DRIVE", 0.2)
    dry_space(p)
    p.dist(mode="SOFT", drive=0.25, tone=0.6, mix=0.35)
    p.grit(("DIST_MIX", 0.5), ("DIST_DRIVE", 0.35))
    p.master(0.7)
    p.context(motion_window=(0.0, 0.6))
    p.doc("Long-decay 808 with a click of pitch at the front; slides into held notes", "C1–G2", "Trap, drill, hip-hop, phonk",
          "One note per hit; overlap notes to slide (mono legato)", "FOREGROUND",
          "Tune it to the key and keep kick and 808 from hitting together, or shorten with a release cut")
    out.append(p)

    # -- percussive / sequence ------------------------------------------------
    p = B("PISTON", "ANALOG", "BASIC")
    p.osc(0, level=0.75, wt=0.9)
    p.osc(1, level=0.4, wt=0.0, octave=-1)
    p.filter("LP24", hz=260, res=0.28, env=0.34, keytrack=0.4, drive=0.2)
    p.filter2("HP12", hz=25, res=0.0)
    p.env(1, a=0.001, d=0.22, s=0.4, r=0.05)
    p.env(2, a=0.001, d=0.16, s=0.0, r=0.05, dcurve=-0.6)
    mono(p, glide=0.0, legato=False, vel_tone=0.14)
    p.tone("CUTOFF", 0.16)
    p.lfo(1, "SAW_DOWN", sync="1/16", mode="FREE")
    p.set("macro2", 0.0)
    p.mod("LFO1", "CUTOFF", 0.1, aux="MACRO2")
    dry_space(p, time="3/16")
    grit(p, mode="HARD", drive=0.35, tone=0.55, amount=0.6)
    p.master(0.65)
    p.doc("Tight, punchy saw bass for 8th and 16th sequences", "E1–E2", "Techno, EBM, industrial, synthwave",
          "Staccato 16ths; accent with velocity", "RHYTHM",
          "Sidechain lightly to the kick; TONE up for a busier arrangement, down under a vocal")
    out.append(p)

    p = B("RUST PULSE", "PWM", "BASIC")
    p.osc(0, level=0.75, wt=0.35)
    p.osc(1, level=0.45, wt=0.0, octave=-1)
    p.filter("LADDER", hz=420, res=0.3, env=0.25, keytrack=0.4, drive=0.3)
    p.filter2("HP12", hz=25, res=0.0)
    p.env(1, a=0.001, d=0.3, s=0.55, r=0.07)
    p.env(2, a=0.001, d=0.2, s=0.1, r=0.06)
    mono(p, glide=0.02, vel_tone=0.1)
    p.tone("CUTOFF", 0.15)
    p.lfo(1, "TRIANGLE", hz=0.6)
    p.motion("LFO1", "A_WTPOS", 0.18)
    dry_space(p)
    grit(p, mode="DIODE", drive=0.35, tone=0.5, amount=0.65)
    p.master(0.65)
    p.doc("Nasal pulse-width bass with a slowly breathing width", "E1–A2", "EBM, darkwave, industrial pop",
          "Driving 8ths and syncopated lines", "RHYTHM",
          "Its body sits at 200–500 Hz: leave that room in pads or scoop them there")
    out.append(p)

    p = B("CORROSION ACID", "ANALOG", "BASIC")
    p.osc(0, level=0.8, wt=0.95)
    p.filter("LADDER", hz=330, res=0.62, env=0.36, keytrack=0.3, drive=0.35)
    p.env(1, a=0.001, d=0.3, s=0.6, r=0.05)
    p.env(2, a=0.001, d=0.2, s=0.0, r=0.05, dcurve=-0.5)
    p.voice(voices=1, glide=0.07, legato=True, glide_always=False, vel=0.3, bend=2)
    p.mod("VELOCITY", "CUTOFF", 0.1)
    p.mod("VELOCITY", "RES", 0.08)
    p.tone("CUTOFF", 0.22)
    p.lfo(1, "SINE", sync="2 BAR", mode="FREE")
    p.set("macro2", 0.3)
    p.motion("LFO1", "CUTOFF", 0.05)
    dry_space(p, time="3/16")
    grit(p, mode="DIODE", drive=0.45, tone=0.5, amount=0.6)
    p.master(0.6)
    p.doc("Squelching resonant line; TONE is the cutoff knob you ride", "C1–C3", "Acid, techno, electro, breaks",
          "16ths with overlapping notes to slide; accent with velocity", "FOREGROUND",
          "Automate TONE across the drop; keep the snare's 1–3 kHz clear or tame RES with a high cut")
    out.append(p)

    p = B("WIRE FUNK", "ANALOG", "PWM")
    p.osc(0, level=0.7, wt=0.75)
    p.osc(1, level=0.35, wt=0.2)
    p.sub(0.35, "SINE")
    p.filter("LP24", hz=300, res=0.35, env=0.4, keytrack=0.5)
    p.env(1, a=0.001, d=0.35, s=0.5, r=0.06)
    p.env(2, a=0.001, d=0.12, s=0.05, r=0.06, dcurve=-0.5)
    mono(p, glide=0.0, legato=False, vel_tone=0.2)
    p.tone("CUTOFF", 0.15)
    p.lfo(1, "SINE", hz=0.4)
    p.set("macro2", 0.2)
    p.motion("LFO1", "B_WTPOS", 0.1)
    dry_space(p)
    grit(p, mode="TUBE", drive=0.3, tone=0.6, amount=0.7)
    p.master(0.65)
    p.doc("Envelope-filter funk bass that barks harder the harder you play", "E1–E3", "Funk, disco, pop, boogie",
          "Syncopated 16ths, ghost notes at low velocity", "RHYTHM",
          "Velocity is the tone control: play it rather than EQ it")
    out.append(p)

    p = B("TAPE BASS", "BASIC", "BASIC")
    p.osc(0, level=0.75, wt=0.3)
    p.osc(1, level=0.3, wt=0.0, fine=4)
    p.filter("LP12", hz=380, res=0.1, env=0.18, keytrack=0.5)
    p.env(1, a=0.003, d=0.9, s=0.15, r=0.1)
    p.env(2, a=0.001, d=0.25, s=0.0, r=0.1)
    mono(p, glide=0.0, legato=False, vel_tone=0.08)
    p.tone("CUTOFF", 0.14)
    p.lfo(1, "SMOOTH_RANDOM", hz=0.8, mode="TRIG")
    p.set("macro2", 0.35)
    p.motion("LFO1", "PITCH", 0.0025)
    p.motion("LFO1", "CUTOFF", 0.04)
    p.motion("LFO1", "AMP", 0.08)
    dry_space(p)
    grit(p, mode="SOFT", drive=0.35, tone=0.4, amount=0.8)
    p.master(0.7)
    p.doc("Muted, round, slightly unsteady bass like a dampened old synth", "E1–E3", "Indie, lo-fi, bedroom pop, soul",
          "Quarter and 8th notes; lets rests breathe", "SUPPORT",
          "It is soft on purpose: add GRIT before adding EQ if it vanishes in a dense mix")
    out.append(p)

    # -- reese / wide -----------------------------------------------------------
    p = B("CORRODED REESE", "ANALOG", "ANALOG")
    p.osc(0, level=0.7, wt=0.85, unison=4, detune=0.12, width=0.1, unimode="LINEAR")
    p.osc(1, level=0.5, wt=0.7, unison=3, detune=0.1, fine=-7, width=0.08)
    p.sub(0.55, "SINE")
    p.filter("LP24", hz=650, res=0.18, drive=0.25, env=0.12, keytrack=0.3)
    p.env(1, a=0.003, d=0.3, s=0.9, r=0.08)
    p.env(2, a=0.002, d=0.35, s=0.2, r=0.1)
    mono(p, glide=0.04)
    p.tone("CUTOFF", 0.18)
    p.mod("MACRO2", "A_DETUNE", 0.4)
    p.mod("MACRO2", "B_DETUNE", 0.3)
    p.lfo(1, "SINE", hz=0.35)
    p.motion("LFO1", "CUTOFF", 0.05)
    dry_space(p)
    grit(p, mode="DIODE", drive=0.35, tone=0.5, amount=0.7)
    p.master(0.6)
    p.doc("Slow-phasing detuned reese for drops and dark verses", "E1–E2", "DnB, dubstep, dark techno, trailer",
          "Long held notes and slides; let the phasing breathe over bars", "FOREGROUND",
          "The sub is clean and centered; MOTION sets how much it phases, so pull it down under busy drums")
    out.append(p)

    p = B("SLAB", "ANALOG", "BASIC")
    p.osc(0, level=0.55, wt=0.9, octave=1, unison=6, detune=0.3, width=0.7, unimode="SUPER")
    p.sub(0.7, "SINE")
    p.filter("LP24", hz=1400, res=0.12, env=0.2, keytrack=0.4)
    p.filter2("HP12", hz=170, res=0.05)
    p.env(1, a=0.002, d=0.4, s=0.8, r=0.1)
    p.env(2, a=0.001, d=0.3, s=0.3, r=0.1)
    mono(p, glide=0.0, legato=False, vel_tone=0.08)
    p.tone("CUTOFF", 0.16)
    p.pump(sync="1/4", depth=0.5, default=0.0)
    dry_space(p)
    grit(p, mode="SOFT", drive=0.4, tone=0.6, amount=0.6)
    p.master(0.6)
    p.doc("Wide supersaw top over a mono sine sub, for big drops", "E1–A2", "EDM, future bass, big room, pop drops",
          "Stabs and held roots on the downbeat", "FOREGROUND",
          "The width lives an octave up, the sub stays mono; MOTION adds a 1/4 pump if the track has no sidechain")
    out.append(p)

    p = B("DRIFT MONO", "ANALOG", "ANALOG")
    p.osc(0, level=0.7, wt=0.8)
    p.osc(1, level=0.55, wt=0.8, fine=-9)
    p.sub(0.35, "SQUARE")
    p.filter("LP24", hz=480, res=0.2, env=0.22, keytrack=0.5)
    p.env(1, a=0.003, d=0.4, s=0.75, r=0.1)
    p.env(2, a=0.002, d=0.3, s=0.2, r=0.1)
    mono(p, glide=0.06, vel_tone=0.08)
    p.tone("CUTOFF", 0.16)
    p.lfo(1, "SMOOTH_RANDOM", hz=0.5, mode="TRIG")
    p.set("macro2", 0.4)
    p.motion("LFO1", "B_FINE", 0.12)
    p.lfo(2, "TRIANGLE", hz=0.3, mode="TRIG")
    p.motion("LFO2", "CUTOFF", 0.09)
    dry_space(p, time="3/16")
    grit(p, mode="TUBE", drive=0.35, tone=0.6, amount=0.7)
    p.master(0.62)
    p.doc("Two drifting saws in a mono voice: warm, analog-feeling lead-bass", "E1–E3", "Synthwave, retro pop, soundtrack",
          "Legato lines with glide", "FOREGROUND",
          "Sits naturally; if it clashes with a pad's low mids, lower TONE rather than EQ")
    out.append(p)

    # -- metallic / industrial -------------------------------------------------
    p = B("GRINDER", "BASIC", "BASIC")
    p.osc(0, level=0.75, wt=0.67, warp="RM", warp_amt=0.35)
    p.osc(1, level=0.002, wt=0.0, octave=1, semi=7)
    p.sub(0.6, "SINE")
    p.filter("LP24", hz=900, res=0.22, env=0.2, keytrack=0.4, drive=0.3)
    p.env(1, a=0.002, d=0.35, s=0.8, r=0.08)
    p.env(2, a=0.001, d=0.25, s=0.3, r=0.08)
    mono(p, glide=0.02)
    p.tone("CUTOFF", 0.15)
    p.lfo(1, "TRIANGLE", sync="1/2")
    p.motion("LFO1", "A_WARP", 0.15)
    dry_space(p)
    grit(p, mode="HARD", drive=0.35, tone=0.5, amount=0.6)
    p.master(0.62)
    p.doc("Ring-modulated metal over a clean sub: machinery with a floor", "E1–D2", "Industrial, EBM, dark techno, trailer",
          "Held notes and slow 8ths", "FOREGROUND",
          "The metal is in 300 Hz–2 kHz: keep guitars or pads out of that band while it plays")
    out.append(p)

    p = B("FOLDBACK", "VOID_FOLD", "BASIC")
    p.osc(0, level=0.7, wt=0.25)
    p.sub(0.55, "SINE")
    p.filter("LP24", hz=1100, res=0.15, keytrack=0.4)
    p.env(1, a=0.002, d=0.3, s=0.8, r=0.08)
    p.env(4, a=0.001, d=0.25, s=0.0, r=0.1)
    p.mod("ENV4", "A_WTPOS", 0.25)
    p.mod("VELOCITY", "A_WTPOS", 0.15)
    mono(p, glide=0.02, vel_tone=0.05)
    p.tone("A_WTPOS", 0.2)
    p.lfo(1, "SINE", sync="1/4")
    p.set("macro2", 0.25)
    p.motion("LFO1", "A_WTPOS", 0.08)
    dry_space(p)
    grit(p, mode="SINFOLD", drive=0.3, tone=0.55, amount=0.55)
    p.master(0.62)
    p.doc("Wavefolded sine: harder notes fold brighter, like bending sheet metal", "E1–A2", "Industrial techno, hybrid trap, game score",
          "Velocity-sensitive 8ths; accents fold harder", "FOREGROUND",
          "TONE sets the fold depth; darker for verses, brighter for the drop")
    out.append(p)

    p = B("CABLE GROWL", "GROWL", "BASIC")
    p.osc(0, level=0.7, wt=0.35, unison=2, detune=0.08, width=0.05)
    p.sub(0.6, "SINE")
    p.filter("LP24", hz=1500, res=0.2, keytrack=0.3, drive=0.2)
    p.env(1, a=0.002, d=0.3, s=0.85, r=0.08)
    mono(p, glide=0.03, vel_tone=0.16, vel=0.55)
    p.tone("A_WTPOS", 0.2)
    p.lfo(1, "SINE", sync="1/8", mode="TRIG")
    p.set("macro2", 0.4)
    p.motion("LFO1", "A_WTPOS", 0.22)
    p.motion("LFO1", "CUTOFF", 0.06)
    dry_space(p)
    grit(p, mode="HARD", drive=0.3, tone=0.55, amount=0.55)
    p.comp(mode="MULTIBAND", threshold=0.6, depth=0.35, gain=0.05)
    p.master(0.6)
    p.doc("Controlled 1/8 growl over a clean sub; MOTION is the wobble depth", "E1–G2", "Dubstep, riddim-lite, hybrid trap",
          "Held notes; ride MOTION for the wobble, TONE for the vowel", "FOREGROUND",
          "At MOTION 0 it is a steady growl you can sequence; keep drums' 1–3 kHz clear")
    out.append(p)

    p = B("SYNC SNARL", "SYNC_SWEEP", "BASIC")
    p.osc(0, level=0.7, wt=0.15, warp="SYNC", warp_amt=0.1)
    p.sub(0.55, "SINE")
    p.filter("LP24", hz=1300, res=0.18, keytrack=0.4, drive=0.25)
    p.env(1, a=0.002, d=0.3, s=0.8, r=0.08)
    p.env(4, a=0.001, d=0.35, s=0.1, r=0.1)
    p.mod("ENV4", "A_WARP", 0.35)
    p.mod("VELOCITY", "A_WARP", 0.15)
    mono(p, glide=0.03)
    p.tone("A_WARP", 0.2)
    p.lfo(1, "TRIANGLE", sync="1/4")
    p.set("macro2", 0.2)
    p.motion("LFO1", "A_WARP", 0.1)
    dry_space(p)
    grit(p, mode="SOFT", drive=0.4, tone=0.55, amount=0.6)
    p.master(0.6)
    p.doc("Hard-sync bark that opens on each note, over a clean sub", "E1–A2", "Electro, midtempo, industrial, breaks",
          "Punchy 8ths; accents snarl harder", "FOREGROUND",
          "Its bite is 1–3 kHz: give it that space from snares or push it back with TONE")
    out.append(p)

    p = B("SIGNAL FM", "BASIC", "BASIC")
    p.osc(0, level=0.75, wt=0.0, warp="FM", warp_amt=0.15)
    p.osc(1, level=0.002, wt=0.0, octave=1)
    p.filter("LP24", hz=2200, res=0.05, keytrack=0.3)
    p.env(1, a=0.001, d=0.35, s=0.6, r=0.06)
    p.env(4, a=0.001, d=0.18, s=0.05, r=0.05)
    p.mod("ENV4", "A_WARP", 0.35)
    p.mod("VELOCITY", "A_WARP", 0.12)
    mono(p, glide=0.0, legato=False, vel_tone=0.0)
    p.tone("A_WARP", 0.12)
    p.lfo(1, "SINE", hz=0.3)
    p.set("macro2", 0.2)
    p.motion("LFO1", "A_WARP", 0.05)
    dry_space(p)
    grit(p, mode="TUBE", drive=0.35, tone=0.6, amount=0.7)
    p.master(0.68)
    p.doc("Clean FM bass with a woody attack, like a digital upright", "E1–E3", "House, garage, city pop, jazz-funk",
          "Walking lines and syncopation; velocity sets the attack", "SUPPORT",
          "Very little low mud: it can sit louder than a saw bass under the same kick")
    out.append(p)

    p = B("HOLLOW PULSE", "PWM", "BASIC")
    p.osc(0, level=0.75, wt=0.05)
    p.sub(0.35, "SINE")
    p.filter("LP12", hz=700, res=0.1, keytrack=0.5, env=0.1)
    p.filter2("NOTCH", hz=900, res=0.3)
    p.env(1, a=0.002, d=0.35, s=0.7, r=0.08)
    p.env(2, a=0.001, d=0.2, s=0.1, r=0.08)
    mono(p, glide=0.02)
    p.tone("CUTOFF", 0.14)
    p.lfo(1, "TRIANGLE", hz=0.3)
    p.set("macro2", 0.3)
    p.motion("LFO1", "F2_CUTOFF", 0.1)
    dry_space(p)
    grit(p, mode="TUBE", drive=0.35, tone=0.6, amount=0.7)
    p.master(0.68)
    p.doc("Hollow square bass with a scooped middle that leaves room for vocals", "E1–E3", "Synth-pop, indie, electro-pop",
          "8ths and offbeats", "SUPPORT",
          "Already scooped around 900 Hz: it sits under a vocal without EQ")
    out.append(p)

    p = B("ORGAN FLOOR", "ORGAN", "BASIC")
    p.osc(0, level=0.75, wt=0.2)
    p.filter("LP12", hz=1400, res=0.05, keytrack=0.4)
    p.env(1, a=0.002, d=0.3, s=0.85, r=0.06)
    mono(p, glide=0.0, legato=False, vel_tone=0.06)
    p.tone("A_WTPOS", 0.25)
    p.lfo(1, "SINE", hz=5.5, mode="FREE")
    p.set("macro2", 0.0)
    p.motion("LFO1", "A_PITCH", 0.001)
    p.chorus(mix=0.0, rate=0.5, depth=0.3)
    p.mod("MACRO2", "CHORUS_MIX", 0.4)
    dry_space(p)
    grit(p, mode="TUBE", drive=0.4, tone=0.6, amount=0.7)
    p.master(0.68)
    p.doc("Drawbar organ bass with a clean fundamental", "C1–C3", "Deep house, gospel-house, garage",
          "Short offbeat notes and walking lines", "SUPPORT",
          "Works as the only bass; MOTION adds chorus shimmer to the upper drawbars")
    out.append(p)

    # -- cinematic ---------------------------------------------------------------
    p = B("CATHEDRAL LOW", "ANALOG", "HARMONIC_SWEEP")
    p.osc(0, level=0.65, wt=0.35)
    p.osc(1, level=0.35, wt=0.25, octave=1)
    p.sub(0.5, "SINE")
    p.filter("LP24", hz=420, res=0.12, keytrack=0.5)
    p.env(1, a=0.06, d=0.8, s=0.85, r=0.5)
    p.voice(voices=2, glide=0.0, vel=0.4)
    p.mod("VELOCITY", "CUTOFF", 0.06)
    p.tone("CUTOFF", 0.16)
    p.lfo(1, "SINE", hz=0.12)
    p.set("macro2", 0.4)
    p.motion("LFO1", "B_WTPOS", 0.2)
    p.motion("LFO1", "CUTOFF", 0.06)
    dry_space(p, time="1/4")
    grit(p, mode="SOFT", drive=0.3, tone=0.4, amount=0.6)
    p.master(0.65)
    p.doc("Soft-attack orchestral-weight low end for scores", "C1–C3", "Film, trailer, ambient, post-rock",
          "Long held roots; octaves", "SUPPORT",
          "Slow attack keeps it off the kick; for trailer hits layer it with a short BASS or PERC")
    p.context(bpm=90)
    out.append(p)

    p = B("DARK MATTER", "GROWL", "FORMANT")
    p.osc(0, level=0.55, wt=0.2)
    p.osc(1, level=0.35, wt=0.3, octave=1)
    p.sub(0.6, "SINE")
    p.filter("LP24", hz=700, res=0.2, keytrack=0.4, env=0.12)
    p.env(1, a=0.25, d=1.0, s=0.9, r=0.6)
    p.env(2, a=0.8, d=1.5, s=0.6, r=0.6)
    p.voice(voices=1, glide=0.1, legato=True, glide_always=False, vel=0.55)
    p.mod("VELOCITY", "CUTOFF", 0.12)
    p.tone("CUTOFF", 0.15)
    p.lfo(1, "SMOOTH_RANDOM", hz=0.25, mode="TRIG")
    p.set("macro2", 0.45)
    p.motion("LFO1", "B_WTPOS", 0.25)
    p.motion("LFO1", "CUTOFF", 0.07)
    dry_space(p, time="1/4")
    grit(p, mode="DIODE", drive=0.3, tone=0.45, amount=0.6)
    p.master(0.62)
    p.doc("Swelling low growl that opens over a bar: tension under a scene", "C1–G2", "Trailer, horror, dark ambient, industrial",
          "Whole notes and slow slides; hold for the swell", "TEXTURE",
          "Everything above the sub moves slowly; MOTION 0 freezes it for dialogue-heavy moments")
    p.context(bpm=90)
    out.append(p)

    p = B("MACHINE HEART", "BASIC", "BASIC")
    p.osc(0, level=0.8, wt=0.12)
    p.filter("LP24", hz=700, res=0.08, keytrack=0.5)
    p.env(1, a=0.002, d=0.3, s=0.9, r=0.1)
    mono(p, glide=0.02)
    p.tone("A_WTPOS", 0.2)
    p.pump(sync="1/4", depth=0.55 / 0.6, default=0.6, sharpness=3.5)
    dry_space(p)
    grit(p, mode="TUBE", drive=0.4, tone=0.5, amount=0.7)
    p.master(0.72)
    p.doc("Pulsing quarter-note sub that breathes with the kick", "E1–D2", "Cinematic pulse, techno, ambient techno",
          "Hold one note for a bar or more; the pulse is tempo-synced", "RHYTHM",
          "Lock the kick on the beat; the dip already makes room for it. MOTION 0 turns the pulse off")
    out.append(p)

    p = B("GLASS FLOOR", "FM_BELL", "BASIC")
    p.osc(0, level=0.6, wt=0.35)
    p.sub(0.6, "SINE")
    p.filter("LP24", hz=2400, res=0.1, keytrack=0.3, env=0.15)
    p.env(1, a=0.001, d=0.5, s=0.5, r=0.12)
    p.env(2, a=0.001, d=0.25, s=0.1, r=0.1)
    p.env(4, a=0.001, d=0.3, s=0.2, r=0.1)
    p.mod("ENV4", "A_WTPOS", 0.25)
    mono(p, glide=0.0, legato=False, vel_tone=0.1)
    p.tone("A_WTPOS", 0.2)
    p.lfo(1, "SINE", hz=0.2)
    p.set("macro2", 0.3)
    p.motion("LFO1", "A_WTPOS", 0.06)
    dry_space(p, time="3/16")
    grit(p, mode="SOFT", drive=0.35, tone=0.6, amount=0.6)
    p.master(0.64)
    p.doc("Bell-edged FM bass: a glassy attack on a solid sub", "E1–A2", "UK garage, future garage, liquid DnB",
          "Syncopated 8ths and offbeats", "FOREGROUND",
          "The attack cuts at 1–2 kHz; with a busy top line, pull TONE down")
    out.append(p)

    p = B("DIESEL", "ANALOG", "ANALOG")
    p.osc(0, level=0.7, wt=0.95)
    p.osc(1, level=0.45, wt=0.95, octave=-1)
    p.filter("LP24", hz=750, res=0.2, env=0.2, keytrack=0.4, drive=0.3)
    p.env(1, a=0.002, d=0.3, s=0.85, r=0.07)
    p.env(2, a=0.001, d=0.25, s=0.3, r=0.07)
    mono(p, glide=0.02)
    p.tone("CUTOFF", 0.15)
    p.lfo(1, "TRIANGLE", sync="1/2")
    p.set("macro2", 0.2)
    p.motion("LFO1", "CUTOFF", 0.05)
    dry_space(p)
    grit(p, mode="HARD", drive=0.35, tone=0.5, base=0.35, amount=0.45)
    p.comp(mode="SINGLE", threshold=0.55, ratio=0.35, attack=0.25, release=0.3, gain=0.4, depth=0.6)
    p.master(0.6)
    p.doc("Overdriven saw bass with weight and a controlled edge", "E1–A2", "Industrial rock, EBM, trap metal, midtempo",
          "Power-bass 8ths, held roots", "FOREGROUND",
          "Distortion is moderate by default; GRIT takes it to full. Let a guitar own 2–4 kHz if one is playing")
    out.append(p)

    p = B("NEEDLE LAYER", "PWM", "BASIC")
    p.osc(0, level=0.9, wt=0.3, unison=2, detune=0.08, width=0.06)
    p.filter("HP24", hz=150, res=0.05)
    p.filter2("LP12", hz=2600, res=0.1, keytrack=0.3)
    p.env(1, a=0.002, d=0.25, s=0.7, r=0.06)
    mono(p, glide=0.0, legato=False, vel_tone=0.0)
    p.mod("VELOCITY", "F2_CUTOFF", 0.12)
    p.tone("F2_CUTOFF", 0.15)
    p.lfo(1, "TRIANGLE", hz=0.5)
    p.set("macro2", 0.3)
    p.motion("LFO1", "A_WTPOS", 0.1)
    dry_space(p)
    grit(p, mode="SOFT", drive=0.45, tone=0.55, base=0.55, amount=0.4)
    p.master(0.66)
    p.doc("Buzzy mid-bass with no sub, made to layer over IRON SUB or an 808", "E1–E3", "Trap, industrial, EBM, hyperpop",
          "Same notes as the sub layer", "SUPPORT",
          "No low end by design: pair it with a sub on another track and bus them together")
    out.append(p)

    return out
