from lunatk import Preset
from bank._common import grit, space, velocity


def D(name, a="ANALOG", b="ANALOG"):
    return Preset(name, "DRONE", a, b)


def drone_voice(p, voices=6):
    return p.voice(voices=voices, glide=0.0, vel=0.25, bend=2)


def hall(p, mix=0.28, decay=0.45, size=0.75, amount=0.2, damp=0.55, width=0.9):
    return space(p, mix, mode="HALL", size=size, decay=decay, damp=damp, predelay=0.2, width=width, amount=amount)


def low_hall(p, mix=0.22, decay=0.42, amount=0.18, damp=0.6, width=0.3):
    """LUNATK's reverb has no low cut: a low drone keeps it narrow so the
    low end stays in the middle."""
    return hall(p, mix=mix, decay=decay, amount=amount, damp=damp, width=width)


def mono_low(p, hz=None):
    """Drones may have low end, but it stays centred: wide layers get
    high-passed, the sub sits in the middle."""
    if hz:
        p.filter2("HP12", hz=hz)
    return p


def presets():
    out = []

    p = D("TURBINE HALL", "BASIC", "SPECTRAL_COMB")
    p.osc(0, level=0.55, wt=0.4)
    p.osc(1, level=0.3, wt=0.5, octave=1, unison=3, detune=0.12, width=0.15)
    p.noise(0.18, "METAL", color=0.55, pitch=0.45, keytrack=True)
    p.filter("LP24", hz=900, res=0.2, keytrack=0.4)
    mono_low(p, 55)
    p.env(1, a=2.0, d=2.0, s=0.95, r=2.5)
    drone_voice(p)
    velocity(p, 0.25, 0.05)
    p.tone("CUTOFF", 0.15)
    p.lfo(1, "SINE", hz=0.07, mode="TRIG")
    p.lfo(2, "SMOOTH_RANDOM", hz=0.3, mode="TRIG")
    p.motion("LFO1", "NOISE_LEVEL", 0.1)
    p.motion("LFO2", "CUTOFF", 0.06)
    low_hall(p, mix=0.24)
    grit(p, mode="HARD", drive=0.3, tone=0.45, amount=0.35)
    p.master(0.6)
    p.doc("A tuned machine hum with metal overtones spinning up and down", "C1–C3", "Industrial, sci-fi, horror, documentary",
          "Hold the root under a scene or a breakdown", "TEXTURE",
          "Tuned to the note you hold, so it can sit under harmony; MOTION 0 is a steady hum")
    out.append(p)

    p = D("DREAD CURRENT", "ANALOG", "ANALOG")
    p.osc(0, level=0.6, wt=0.5, unison=2, detune=0.08, width=0.0)
    p.osc(1, level=0.4, wt=0.45, fine=-8)
    p.sub(0.35, "SINE")
    p.filter("LP24", hz=500, res=0.18, keytrack=0.4)
    p.env(1, a=2.5, d=2.0, s=0.95, r=3.0)
    drone_voice(p)
    velocity(p, 0.25, 0.04)
    p.tone("CUTOFF", 0.15)
    p.lfo(1, "SINE", hz=0.05, mode="TRIG")
    p.motion("LFO1", "CUTOFF", 0.08)
    p.motion("LFO1", "B_FINE", 0.08)
    low_hall(p, width=0.12, mix=0.22, decay=0.4)
    grit(p, mode="DIODE", drive=0.3, tone=0.4, amount=0.35)
    p.master(0.6)
    p.doc("A dark, slowly beating low drone for dread", "C1–C2", "Horror, thriller, dark ambient, industrial",
          "One note, or root and fifth, for as long as the tension lasts", "SUPPORT",
          "The low end is mono and beats slowly; MOTION sets how much it churns")
    out.append(p)

    p = D("CATHEDRAL AIR", "CHOIR", "GLASS")
    p.osc(0, level=0.55, wt=0.35, unison=5, detune=0.15, width=0.7)
    p.osc(1, level=0.3, wt=0.5, octave=1, unison=3, detune=0.1, width=0.7)
    p.filter("LP12", hz=4200, res=0.08, keytrack=0.3)
    mono_low(p, 200)
    p.env(1, a=2.0, d=2.0, s=0.95, r=3.0)
    drone_voice(p)
    velocity(p, 0.25, 0.0)
    p.tone("B_LEVEL", 0.2)
    p.lfo(1, "SINE", hz=0.06, mode="TRIG")
    p.lfo(2, "SMOOTH_RANDOM", hz=0.15, mode="TRIG")
    p.motion("LFO1", "A_WTPOS", 0.15)
    p.motion("LFO2", "B_WTPOS", 0.15)
    hall(p, mix=0.32, decay=0.48)
    grit(p, mode="SOFT", drive=0.3, tone=0.5, amount=0.3)
    p.eq(high=-3, high_hz=9000)
    p.master(0.6)
    p.doc("Luminous choir-and-glass drone: beauty with space around it", "C3–C5", "Film, sacred-ambient, post-rock, meditation",
          "Hold one or two notes for a long time", "TEXTURE",
          "High-passed at 200 Hz: it floats over everything; SPACE sets the size of the room")
    p.context(root=57)
    out.append(p)

    p = D("POWER LINE", "BASIC", "BASIC")
    p.osc(0, level=0.55, wt=0.67)
    p.osc(1, level=0.25, wt=0.9, octave=2)
    p.noise(0.05, "CRACKLE", color=0.5, pitch=0.4, keytrack=False)
    p.filter("LP12", hz=1200, res=0.1, keytrack=0.3)
    mono_low(p, 45)
    p.env(1, a=0.8, d=1.0, s=0.95, r=1.5)
    drone_voice(p)
    velocity(p, 0.25, 0.04)
    p.tone("CUTOFF", 0.15)
    p.lfo(1, "SAMPLE_HOLD", hz=6.0, mode="TRIG")
    p.lfo(2, "SINE", hz=0.2, mode="TRIG")
    p.set("macro2", 0.4)
    p.motion("LFO1", "AMP", 0.08)
    p.motion("LFO2", "NOISE_LEVEL", 0.08)
    low_hall(p, mix=0.12, decay=0.3)
    grit(p, mode="HARD", drive=0.35, tone=0.5, amount=0.35)
    p.master(0.6)
    p.doc("Electrical hum with crackle, tuned to the note you hold", "C1–C3", "Industrial, horror, found-sound ambient, film",
          "Hold the root; use it as a bed under dialogue or between cues", "TEXTURE",
          "Narrow and mid-focused: it sits under anything; MOTION adds flicker")
    out.append(p)

    p = D("DEEP WATER", "ANALOG", "HARMONIC_SWEEP")
    p.osc(0, level=0.55, wt=0.3, unison=3, detune=0.1, width=0.0)
    p.osc(1, level=0.3, wt=0.2)
    p.noise(0.12, "BROWN", color=0.6, keytrack=False)
    p.filter("LP24", hz=380, res=0.2, keytrack=0.4)
    mono_low(p, 40)
    p.env(1, a=3.0, d=2.0, s=0.95, r=3.0)
    drone_voice(p)
    velocity(p, 0.25, 0.04)
    p.tone("CUTOFF", 0.15)
    p.lfo(1, "SINE", hz=0.08, mode="TRIG")
    p.motion("LFO1", "CUTOFF", 0.1)
    p.motion("LFO1", "NOISE_LEVEL", 0.08)
    low_hall(p, width=0.12, mix=0.26, damp=0.8)
    grit(p, mode="SOFT", drive=0.3, tone=0.4, amount=0.3)
    p.master(0.62)
    p.doc("Muffled low drone with slow swells, as if heard underwater", "C1–C3", "Ambient, dub, nature doc, underwater cues",
          "Hold a low note; let the swells move on their own", "TEXTURE",
          "Almost nothing above 1 kHz: it can be loud without masking anything")
    out.append(p)

    p = D("RADIO STATIC", "BASIC", "BASIC")
    p.set("a.on", 0)
    p.noise(0.7, "DIGITAL", color=0.3, pitch=0.5, keytrack=True)
    p.filter("BP", cut=0.5, res=0.45, keytrack=1.0)
    mono_low(p, 150)
    p.env(1, a=0.8, d=1.0, s=0.95, r=1.5)
    drone_voice(p)
    velocity(p, 0.25, 0.0)
    p.tone("NOISE_COLOR", -0.2)
    p.lfo(1, "SMOOTH_RANDOM", hz=0.4, mode="TRIG")
    p.lfo(2, "SAMPLE_HOLD", hz=3.0, mode="TRIG")
    p.motion("LFO1", "CUTOFF", 0.1)
    p.motion("LFO2", "NOISE_PITCH", 0.08)
    hall(p, mix=0.14, decay=0.3)
    grit(p, mode="BITCRUSH", drive=0.3, tone=0.5, amount=0.35)
    p.eq(high=-6, high_hz=7000)
    p.master(0.6)
    p.doc("Tuned radio static that searches around the note", "C3–C5", "Sci-fi, glitch, found-sound, transitions",
          "Hold a note as a bed, or sweep TONE for a tuning-dial move", "TEXTURE",
          "Band-passed and tamed at the top; bring it in under a breakdown")
    p.context(root=57, unpitched=True)
    out.append(p)

    p = D("GLASS HORIZON", "GLASS", "GLASS")
    p.osc(0, level=0.5, wt=0.6, unison=4, detune=0.12, width=0.8)
    p.osc(1, level=0.3, wt=0.8, octave=1, unison=2, detune=0.1, width=0.7)
    p.filter("LP12", hz=6000, res=0.05)
    mono_low(p, 250)
    p.env(1, a=2.5, d=2.0, s=0.95, r=3.0)
    drone_voice(p)
    velocity(p, 0.25, 0.0)
    p.tone("A_WTPOS", 0.15)
    p.lfo(1, "TRIANGLE", hz=0.05, mode="TRIG")
    p.motion("LFO1", "A_WTPOS", 0.2)
    p.motion("LFO1", "B_WTPOS", -0.15)
    hall(p, mix=0.3)
    grit(p, mode="SOFT", drive=0.3, tone=0.5, amount=0.3)
    p.eq(high=-5, high_hz=9000)
    p.master(0.58)
    p.doc("High shimmering partials drifting like light on a horizon", "C4–C6", "Ambient, film, post-rock, worship",
          "Hold high notes above the harmony", "TEXTURE",
          "Lives above 500 Hz: it adds air to a mix without touching the body of it")
    p.context(root=69)
    out.append(p)

    p = D("CORRODED TONE", "BASIC", "DIGITAL")
    p.osc(0, level=0.55, wt=0.05)
    p.osc(1, level=0.3, wt=0.3, octave=1)
    p.filter("LP12", hz=2400, res=0.1, keytrack=0.3)
    mono_low(p, 60)
    p.env(1, a=1.5, d=2.0, s=0.95, r=2.5)
    drone_voice(p)
    velocity(p, 0.25, 0.04)
    p.tone("B_LEVEL", 0.2)
    p.lfo(1, "SINE", hz=0.12, mode="TRIG")
    p.motion("LFO1", "DIST_MIX", 0.25)
    p.motion("LFO1", "B_WTPOS", 0.15)
    p.dist(mode="DOWNSAMPLE", drive=0.35, tone=0.45, mix=0.2)
    p.grit(("DIST_MIX", 0.45), ("DIST_DRIVE", 0.2))
    low_hall(p, mix=0.2)
    p.master(0.6)
    p.doc("A pure tone that breathes in and out of digital decay", "C2–C4", "Industrial ambient, glitch, dark pop intros",
          "Hold one note; let it decay and recover", "TEXTURE",
          "MOTION is the breathing damage, GRIT the ceiling; both at 0 is a clean tone")
    out.append(p)

    p = D("MONOLITH", "HARMONIC_SWEEP", "ANALOG")
    p.osc(0, level=0.55, wt=0.35, unison=4, detune=0.15, width=0.0, stack="OCTAVE_FIFTH")
    p.osc(1, level=0.3, wt=0.5, unison=2, detune=0.1, width=0.0)
    p.sub(0.3, "SINE")
    p.filter("LP24", hz=1400, res=0.12, keytrack=0.3)
    p.env(1, a=2.0, d=2.0, s=0.95, r=3.0)
    p.env(4, a=8.0, d=1.0, s=1.0, r=3.0, acurve=0.3)
    p.mod("ENV4", "CUTOFF", 0.12)
    drone_voice(p)
    velocity(p, 0.25, 0.04)
    p.tone("CUTOFF", 0.15)
    p.lfo(1, "SINE", hz=0.07, mode="TRIG")
    p.motion("LFO1", "CUTOFF", 0.1)
    p.motion("LFO1", "A_DETUNE", 0.12)
    low_hall(p, width=0.12, mix=0.28)
    grit(p, mode="TUBE", drive=0.3, tone=0.45, amount=0.35)
    p.master(0.56)
    p.doc("A huge stacked-fifth drone that slowly opens over eight seconds", "C1–C3", "Trailer, epic score, doom, post-metal",
          "One low note; hold it for the whole build", "SUPPORT",
          "The octave-and-fifth stack is built in: hold one note, not a chord. Low end stays centred")
    p.context(fifth=False, fifths=True)
    out.append(p)

    p = D("WIND TUNNEL", "BASIC", "BASIC")
    p.set("a.on", 0)
    p.noise(0.8, "BREATH", color=0.45, pitch=0.5, keytrack=True)
    p.filter("BP", cut=0.55, res=0.35, keytrack=0.8)
    mono_low(p, 120)
    p.env(1, a=1.5, d=2.0, s=0.95, r=2.5)
    drone_voice(p)
    velocity(p, 0.25, 0.0)
    p.tone("CUTOFF", 0.15)
    p.lfo(1, "SMOOTH_RANDOM", hz=0.25, mode="TRIG")
    p.lfo(2, "SINE", hz=0.1, mode="TRIG")
    p.motion("LFO1", "CUTOFF", 0.12)
    p.motion("LFO2", "NOISE_LEVEL", 0.12)
    hall(p, mix=0.2)
    grit(p, mode="SOFT", drive=0.3, tone=0.5, amount=0.3)
    p.eq(high=-4, high_hz=8000)
    p.master(0.6)
    p.doc("Wind that whistles around the note you hold", "C3–C5", "Film, game ambience, winter, desolate cues",
          "Hold a note; gusts come and go on their own", "TEXTURE",
          "Faintly pitched: it fits the key while reading as weather")
    p.context(root=57, unpitched=True)
    out.append(p)

    p = D("HOLLOW EARTH", "ANALOG", "BASIC")
    p.osc(0, level=0.55, wt=0.45, unison=2, detune=0.08, width=0.0)
    p.osc(1, level=0.3, wt=0.0, octave=-1)
    p.noise(0.1, "PINK", color=0.5, keytrack=False)
    p.filter("COMB_NEG", cut=0.25, res=0.45, keytrack=1.0, mix=0.5)
    p.filter2("LP24", hz=1200, res=0.1)
    p.env(1, a=2.0, d=2.0, s=0.95, r=2.5)
    drone_voice(p)
    velocity(p, 0.25, 0.04)
    p.tone("F2_CUTOFF", 0.15)
    p.lfo(1, "SINE", hz=0.06, mode="TRIG")
    p.motion("LFO1", "CUTOFF", 0.1)
    low_hall(p, width=0.12, mix=0.24)
    grit(p, mode="SOFT", drive=0.3, tone=0.45, amount=0.3)
    p.master(0.6)
    p.doc("A hollow, cavernous low drone with a slow comb sweep", "C1–C3", "Cave and tomb cues, dark ambient, doom",
          "One low note", "TEXTURE",
          "The comb scoops the middle: it leaves room for voices above it")
    out.append(p)

    p = D("SIGNAL DECAY", "FM_BELL", "BASIC")
    p.osc(0, level=0.55, wt=0.3, warp="FM", warp_amt=0.1)
    p.osc(1, level=0.15, wt=0.0, semi=7)
    p.filter("LP12", hz=3000, res=0.08, keytrack=0.3)
    mono_low(p, 70)
    p.env(1, a=1.5, d=2.0, s=0.95, r=2.5)
    drone_voice(p)
    velocity(p, 0.25, 0.0)
    p.tone("A_WTPOS", 0.15)
    p.lfo(1, "TRIANGLE", hz=0.09, mode="TRIG")
    p.lfo(2, "SMOOTH_RANDOM", hz=0.2, mode="TRIG")
    p.motion("LFO1", "A_WARP", 0.12)
    p.motion("LFO2", "A_WTPOS", 0.15)
    low_hall(p, mix=0.24)
    grit(p, mode="SOFT", drive=0.3, tone=0.5, amount=0.3)
    p.master(0.6)
    p.doc("An FM drone whose overtones drift in and out like a fading signal", "C2–C4", "Sci-fi, IDM, experimental score",
          "One note or a fifth", "TEXTURE",
          "The FM index moves slowly; MOTION 0 gives a steady metallic tone")
    out.append(p)

    p = D("FROZEN CHOIR", "CHOIR", "FORMANT")
    p.osc(0, level=0.55, wt=0.5, unison=6, detune=0.18, width=0.15)
    p.osc(1, level=0.3, wt=0.3, octave=1, unison=3, detune=0.12, width=0.15)
    p.filter("FORMANT", cut=0.45, res=0.3, mix=0.5)
    mono_low(p, 150)
    p.env(1, a=2.5, d=2.0, s=0.95, r=3.0)
    drone_voice(p)
    velocity(p, 0.25, 0.0)
    p.tone("CUTOFF", 0.15)
    p.lfo(1, "SMOOTH_RANDOM", hz=0.3, mode="TRIG")
    p.motion("LFO1", "CUTOFF", 0.18)
    p.motion("LFO1", "A_WTPOS", 0.2)
    low_hall(p, mix=0.3, decay=0.46)
    grit(p, mode="SOFT", drive=0.3, tone=0.5, amount=0.3)
    p.master(0.58)
    p.doc("A choir holding one vowel forever, slowly shifting", "C2–C4", "Film, sacred, dark ambient, game",
          "Hold one note or a fifth", "SUPPORT",
          "Occupies 300 Hz–3 kHz: keep other sustained parts out of it")
    out.append(p)

    p = D("NIGHT FIELD", "GLASS", "BASIC")
    p.osc(0, level=0.25, wt=0.6)
    p.noise(0.3, "CRACKLE", color=0.3, pitch=0.7, keytrack=False)
    p.filter("HP12", hz=1500, res=0.1)
    p.env(1, a=1.5, d=2.0, s=0.95, r=2.0)
    drone_voice(p)
    velocity(p, 0.25, 0.0)
    p.tone("CUTOFF", 0.12)
    p.lfo(1, "SMOOTH_RANDOM", hz=0.5, mode="TRIG")
    p.lfo(2, "SAMPLE_HOLD", hz=8.0, mode="TRIG")
    p.motion("LFO1", "NOISE_LEVEL", 0.12)
    p.motion("LFO2", "A_LEVEL", 0.12)
    hall(p, mix=0.22)
    grit(p, mode="SOFT", drive=0.3, tone=0.5, amount=0.3)
    p.eq(high=-8, high_hz=8000)
    p.master(0.6)
    p.doc("Crackling night air with a faint flickering tone, like insects and wires", "C4–C6",
          "Film, horror, found-sound ambient, game night scenes", "Hold a high note; it sits as ambience", "TEXTURE",
          "All above 1.5 kHz: a background layer that never clouds the mix")
    p.context(root=69, unpitched=True)
    out.append(p)

    p = D("VOID ENGINE", "VOID_FOLD", "ANALOG")
    p.osc(0, level=0.55, wt=0.3, unison=2, detune=0.08, width=0.0)
    p.osc(1, level=0.3, wt=0.4, octave=-1)
    p.filter("LP24", hz=1100, res=0.18, keytrack=0.3)
    mono_low(p, 40)
    p.env(1, a=1.5, d=2.0, s=0.95, r=2.5)
    drone_voice(p)
    velocity(p, 0.25, 0.04)
    p.tone("A_WTPOS", 0.15)
    p.lfo(1, "TRIANGLE", sync="2 BAR", mode="TRIG")
    p.motion("LFO1", "A_WTPOS", 0.2)
    p.motion("LFO1", "CUTOFF", 0.05)
    low_hall(p, width=0.12, mix=0.2)
    grit(p, mode="SINFOLD", drive=0.25, tone=0.45, amount=0.3)
    p.master(0.58)
    p.doc("Wavefolding engine drone that revs slowly in time", "C1–C3", "Sci-fi, cyberpunk, industrial, game",
          "One note; the folding revs over two bars", "TEXTURE",
          "Tempo-synced movement: useful as a groove-aware bed under a breakdown")
    out.append(p)

    p = D("SLOW BURN", "ANALOG", "HARMONIC_SWEEP")
    p.osc(0, level=0.55, wt=0.6, unison=4, detune=0.15, width=0.15)
    p.osc(1, level=0.3, wt=0.3, octave=1)
    p.filter("LP24", hz=250, res=0.2, keytrack=0.3)
    mono_low(p, 60)
    p.env(1, a=2.0, d=2.0, s=0.95, r=2.5)
    p.env(4, a=10.0, d=1.0, s=1.0, r=2.5, acurve=0.35)
    p.mod("ENV4", "CUTOFF", 0.35)
    p.mod("ENV4", "B_WTPOS", 0.4)
    drone_voice(p)
    velocity(p, 0.25, 0.04)
    p.tone("CUTOFF", 0.12)
    p.lfo(1, "SINE", hz=0.15, mode="TRIG")
    p.motion("LFO1", "CUTOFF", 0.05)
    p.motion("LFO1", "A_DETUNE", 0.1)
    low_hall(p, mix=0.22)
    grit(p, mode="TUBE", drive=0.3, tone=0.45, amount=0.35)
    p.master(0.58)
    p.doc("A drone that burns from dark to bright over ten seconds", "C2–C4", "Trailer build, thriller, post-rock swell",
          "Hold one note through a build; retrigger to start again", "TRANSITION",
          "It builds on its own: use it for the last 4–8 bars before a drop or reveal")
    p.context(seconds=12.0)
    out.append(p)

    p = D("ASH FALL", "ANALOG", "BASIC")
    p.osc(0, level=0.4, wt=0.3, unison=3, detune=0.1, width=0.5)
    p.noise(0.3, "VINYL", color=0.5, pitch=0.5, keytrack=False, filtered=False)
    p.filter("LP12", hz=1400, res=0.08, keytrack=0.3)
    mono_low(p, 120)
    p.env(1, a=1.5, d=2.0, s=0.95, r=2.5)
    drone_voice(p)
    velocity(p, 0.25, 0.04)
    p.tone("CUTOFF", 0.15)
    p.lfo(1, "SINE", hz=0.1, mode="TRIG")
    p.motion("LFO1", "NOISE_LEVEL", 0.12)
    p.motion("LFO1", "CUTOFF", 0.05)
    hall(p, mix=0.2)
    grit(p, mode="SOFT", drive=0.3, tone=0.4, amount=0.3)
    p.eq(high=-4, high_hz=7000)
    p.master(0.6)
    p.doc("Soft tone under vinyl crackle, like ash drifting in still air", "C3–C5", "Lo-fi, film, ambient, spoken-word beds",
          "Hold a note or chord as a bed", "TEXTURE",
          "The crackle is always there, the tone breathes; MOTION 0 holds both still")
    p.context(root=57)
    out.append(p)

    p = D("ORGAN PEDAL", "ORGAN", "ORGAN")
    p.osc(0, level=0.55, wt=0.2)
    p.osc(1, level=0.3, wt=0.7, octave=1)
    p.filter("LP12", hz=2400, res=0.05, keytrack=0.3)
    p.env(1, a=0.6, d=1.0, s=1.0, r=2.0)
    drone_voice(p)
    velocity(p, 0.25, 0.04)
    p.tone("A_WTPOS", 0.2)
    p.lfo(1, "SINE", hz=0.3, mode="FREE")
    p.set("macro2", 0.35)
    p.motion("LFO1", "AMP", 0.06)
    p.motion("LFO1", "B_LEVEL", 0.08)
    low_hall(p, mix=0.3, decay=0.42)
    grit(p, mode="SOFT", drive=0.3, tone=0.45, amount=0.3)
    p.master(0.6)
    p.doc("A church-organ pedal note in a big room", "C1–C3", "Sacred, film, gothic, post-rock",
          "Hold the bass note for as long as the harmony above it lasts", "SUPPORT",
          "A pedal point: the low end is mono and steady, so it can sit under a whole choir")
    out.append(p)

    return out
