from lunatk import Preset
from bank._common import echo, grit, space, velocity


def K(name, a="BASIC", b="BASIC"):
    return Preset(name, "KEYS", a, b)


def keys_voice(p, vel=0.7):
    return p.voice(voices=10, glide=0.0, vel=vel, bend=2)


def room(p, mix=0.16, decay=0.3, amount=0.18):
    return space(p, mix, mode="PLATE", size=0.45, decay=decay, damp=0.55, predelay=0.08, width=0.8, amount=amount)


def low_clear(p, hz=120):
    return p.filter2("HP12", hz=hz, res=0.0)


def autopan(p, lfo=3, hz=4.0, depth=0.25, default=None):
    p.lfo(lfo, "SINE", hz=hz, mode="FREE")
    return p.motion(f"LFO{lfo}", "PAN", depth)


def presets():
    out = []

    p = K("EMBER EP", "BASIC", "BASIC")
    p.osc(0, level=0.7, wt=0.0, warp="FM", warp_amt=0.05)
    p.osc(1, level=0.002, wt=0.0, octave=2)
    p.filter("LP12", hz=4200, res=0.05, keytrack=0.4)
    low_clear(p)
    p.env(1, a=0.002, d=2.2, s=0.25, r=0.45, dcurve=-0.6)
    p.env(4, a=0.001, d=0.35, s=0.05, r=0.3)
    p.mod("ENV4", "A_WARP", 0.12)
    p.mod("VELOCITY", "A_WARP", 0.1, aux="ENV4")
    keys_voice(p)
    velocity(p, 0.75, 0.06)
    p.tone("A_WARP", 0.08)
    p.set("macro2", 0.4)
    autopan(p, hz=4.5, depth=0.3)
    p.lfo(4, "SINE", hz=4.5, mode="FREE")
    p.motion("LFO4", "AMP", 0.1)
    p.chorus(mix=0.18, rate=0.3, depth=0.3)
    room(p)
    grit(p, mode="TUBE", drive=0.4, tone=0.5, amount=0.55)
    p.master(0.66)
    p.doc("Tine electric piano: bell-bright when struck hard, round when soft", "C2–C6", "Neo-soul, R&B, jazz-pop, lo-fi",
          "Comping chords; dynamics matter, play it with velocity", "SUPPORT",
          "MOTION is tremolo and autopan; at 0 it sits dead-centre for dense mixes")
    out.append(p)

    p = K("WURLI RUST", "PWM", "BASIC")
    p.osc(0, level=0.7, wt=0.12)
    p.osc(1, level=0.3, wt=0.0, octave=1)
    p.filter("LP12", hz=2400, res=0.12, keytrack=0.5, env=0.15)
    low_clear(p)
    p.env(1, a=0.002, d=1.5, s=0.3, r=0.3, dcurve=-0.5)
    p.env(2, a=0.001, d=0.4, s=0.1, r=0.3)
    keys_voice(p)
    velocity(p, 0.75, 0.14)
    p.tone("CUTOFF", 0.15)
    p.lfo(3, "SINE", hz=5.5, mode="FREE")
    p.set("macro2", 0.35)
    p.motion("LFO3", "AMP", 0.12)
    room(p, mix=0.14)
    grit(p, mode="TUBE", drive=0.45, tone=0.5, base=0.25, amount=0.5)
    p.master(0.64)
    p.doc("Reedy electric piano that growls when you dig in", "C2–C5", "Soul, indie, gospel, blues-rock",
          "Chords and bluesy fills; accents bark", "SUPPORT",
          "Its growl is 1–2 kHz: pull the guitar there, not this")
    out.append(p)

    p = K("GLASS KEYS", "FM_BELL", "GLASS")
    p.osc(0, level=0.65, wt=0.3)
    p.osc(1, level=0.3, wt=0.4, octave=1)
    p.filter("LP12", hz=5500, res=0.05, keytrack=0.3)
    low_clear(p, 150)
    p.env(1, a=0.001, d=1.8, s=0.2, r=0.5, dcurve=-0.6)
    p.env(4, a=0.001, d=0.4, s=0.1, r=0.3)
    p.mod("ENV4", "A_WTPOS", 0.25)
    keys_voice(p)
    velocity(p, 0.7, 0.0)
    p.mod("VELOCITY", "A_WTPOS", 0.15)
    p.tone("A_WTPOS", 0.15)
    p.lfo(1, "SINE", hz=0.25, mode="TRIG")
    p.set("macro2", 0.35)
    p.motion("LFO1", "B_WTPOS", 0.15)
    p.chorus(mix=0.2, rate=0.2, depth=0.3)
    room(p, mix=0.18)
    grit(p, mode="SOFT", drive=0.35, tone=0.5, amount=0.45)
    p.eq(high=-2, high_hz=9000)
    p.master(0.62)
    p.doc("Crystalline digital keys with a hard FM strike", "C3–C6", "Pop, city pop, 80s ballad, future funk",
          "Chords and fast right-hand figures", "FOREGROUND",
          "Bright attack: in a busy chorus, drop TONE a little rather than EQ-ing the top")
    out.append(p)

    p = K("FELT UPRIGHT", "BASIC", "BASIC")
    p.osc(0, level=0.7, wt=0.2)
    p.osc(1, level=0.25, wt=0.0, octave=1, fine=3)
    p.noise(0.06, "BROWN", color=0.6, keytrack=False)
    p.filter("LP12", hz=1800, res=0.05, keytrack=0.6, env=0.12)
    low_clear(p)
    p.env(1, a=0.003, d=1.6, s=0.0, r=0.35, dcurve=-0.7)
    p.env(2, a=0.001, d=0.25, s=0.0, r=0.3)
    keys_voice(p)
    velocity(p, 0.8, 0.12)
    p.tone("CUTOFF", 0.15)
    p.lfo(1, "SMOOTH_RANDOM", hz=0.9, mode="TRIG")
    p.set("macro2", 0.3)
    p.motion("LFO1", "PITCH", 0.002)
    p.motion("LFO1", "CUTOFF", 0.04)
    room(p, mix=0.18)
    grit(p, mode="SOFT", drive=0.35, tone=0.4, amount=0.5)
    p.master(0.68)
    p.doc("Muted felt piano: soft hammers, short sustain, intimate", "C2–C6", "Neo-classical, lo-fi, indie folk, film",
          "Quiet chords and simple melodies; play soft", "SUPPORT",
          "Very little above 3 kHz: sit it close and dry with SPACE down for intimacy")
    out.append(p)

    p = K("FACTORY KEYS", "BASIC", "BASIC")
    p.osc(0, level=0.65, wt=0.5, warp="RM", warp_amt=0.3)
    p.osc(1, level=0.002, wt=0.0, semi=7, octave=1)
    p.noise(0.05, "METAL", color=0.5, pitch=0.6, keytrack=True)
    p.filter("COMB_POS", cut=0.5, res=0.35, keytrack=1.0, mix=0.35)
    p.filter2("LP12", hz=3800, res=0.05, keytrack=0.3)
    p.env(1, a=0.002, d=1.2, s=0.15, r=0.4, dcurve=-0.6)
    keys_voice(p)
    velocity(p, 0.75, 0.0)
    p.mod("VELOCITY", "A_WARP", 0.2)
    p.tone("F2_CUTOFF", 0.15)
    p.lfo(1, "SINE", hz=0.3, mode="TRIG")
    p.set("macro2", 0.35)
    p.motion("LFO1", "A_WARP", 0.12)
    room(p, mix=0.16)
    grit(p, mode="HARD", drive=0.35, tone=0.45, amount=0.45)
    p.eq(low=-6, low_hz=140)
    p.master(0.6)
    p.doc("Metallic ring-mod keys: struck machinery with a pitch", "C3–C5", "Industrial, EBM, dark electro, game",
          "Short chords and ostinatos; accents ring harder", "FOREGROUND",
          "Inharmonic by design: keep chords to three notes so it stays readable")
    out.append(p)

    p = K("SOFT DIGITAL", "DIGITAL", "BASIC")
    p.osc(0, level=0.65, wt=0.18)
    p.osc(1, level=0.3, wt=0.33, octave=1)
    p.filter("LP12", hz=2800, res=0.08, keytrack=0.4, env=0.1)
    low_clear(p)
    p.env(1, a=0.004, d=1.2, s=0.35, r=0.45)
    p.env(2, a=0.002, d=0.4, s=0.1, r=0.4)
    keys_voice(p)
    velocity(p, 0.7, 0.1)
    p.tone("A_WTPOS", 0.2)
    p.lfo(1, "SINE", hz=0.3, mode="TRIG")
    p.set("macro2", 0.35)
    p.motion("LFO1", "CUTOFF", 0.1)
    p.motion("LFO1", "A_WTPOS", 0.12)
    p.chorus(mix=0.25, rate=0.25, depth=0.35)
    room(p, mix=0.16)
    grit(p, mode="BITCRUSH", drive=0.3, tone=0.5, amount=0.4)
    p.master(0.64)
    p.doc("Soft, slightly stepped digital keys, like a cheap 90s module in a good room", "C3–C5",
          "Lo-fi, vaporwave, bedroom pop, game", "Chords and simple toplines", "SUPPORT",
          "Gentle and narrow: it fits under a vocal at almost any level")
    out.append(p)

    p = K("CLAV WIRE", "PWM", "BASIC")
    p.osc(0, level=0.7, wt=0.7)
    p.filter("LP12", hz=1400, res=0.25, keytrack=0.5, env=0.3)
    p.filter2("HP12", hz=220)
    p.env(1, a=0.001, d=0.45, s=0.25, r=0.08, dcurve=-0.6)
    p.env(2, a=0.001, d=0.15, s=0.05, r=0.08)
    keys_voice(p)
    velocity(p, 0.7, 0.2)
    p.tone("CUTOFF", 0.15)
    p.lfo(1, "TRIANGLE", sync="1/4", mode="TRIG")
    p.set("macro2", 0.0)
    p.motion("LFO1", "CUTOFF", 0.2)
    room(p, mix=0.1)
    grit(p, mode="TUBE", drive=0.45, tone=0.55, amount=0.5)
    p.master(0.62)
    p.doc("Snappy clavinet-style keys with an envelope filter", "C3–C5", "Funk, disco, P-funk, pop-funk",
          "Staccato 16ths, muted comping, ghost notes", "RHYTHM",
          "Already high-passed at 220 Hz; MOTION turns it into an auto-wah")
    out.append(p)

    p = K("CHAPEL DRAWBARS", "ORGAN", "ORGAN")
    p.osc(0, level=0.65, wt=0.35)
    p.osc(1, level=0.25, wt=0.9, octave=1)
    p.filter("LP12", hz=5000, res=0.05)
    low_clear(p, 100)
    p.env(1, a=0.004, d=0.3, s=1.0, r=0.1)
    keys_voice(p, vel=0.3)
    p.mod("VELOCITY", "B_LEVEL", 0.35)
    p.mod("VELOCITY", "A_WTPOS", 0.15)
    p.tone("A_WTPOS", 0.25)
    p.lfo(1, "SINE", hz=6.2, mode="FREE")
    p.set("macro2", 0.35)
    p.motion("LFO1", "AMP", 0.08)
    p.chorus(mix=0.0, rate=0.6, depth=0.4)
    p.mod("MACRO2", "CHORUS_MIX", 0.45)
    room(p, mix=0.18)
    grit(p, mode="TUBE", drive=0.45, tone=0.5, amount=0.5)
    p.master(0.6)
    p.doc("Drawbar organ with a rotary shimmer on MOTION and tube overdrive on GRIT", "C2–C6", "Gospel, soul, rock, house",
          "Sustained chords, stabs, glissandos", "SUPPORT",
          "No release tail: it stops dead, so it can sit loud without smearing the groove")
    out.append(p)

    p = K("HOLLOW CELESTE", "GLASS", "BASIC")
    p.osc(0, level=0.65, wt=0.45)
    p.osc(1, level=0.3, wt=0.0, octave=2)
    p.filter("LP12", hz=7000, res=0.05)
    low_clear(p, 200)
    p.env(1, a=0.001, d=1.4, s=0.0, r=0.8, dcurve=-0.7)
    keys_voice(p)
    velocity(p, 0.7, 0.0)
    p.mod("VELOCITY", "B_LEVEL", 0.15)
    p.tone("A_WTPOS", 0.2)
    p.lfo(1, "SINE", hz=5.0, mode="FREE")
    p.set("macro2", 0.3)
    p.motion("LFO1", "AMP", 0.18)
    p.context(motion_window=(0.05, 1.3))
    room(p, mix=0.2)
    grit(p, mode="SOFT", drive=0.3, tone=0.5, amount=0.4)
    p.eq(high=-3, high_hz=10000)
    p.master(0.64)
    p.doc("Celeste-like bell keys, clean and hollow", "C4–C7", "Film, lullaby, Christmas, fairy-tale score",
          "Simple high melodies and broken chords", "FOREGROUND",
          "Lives above 1 kHz: it can double a melody without muddying anything")
    p.context(shift=12)
    out.append(p)

    p = K("TAPE PIANO", "BASIC", "HARMONIC_SWEEP")
    p.osc(0, level=0.65, wt=0.25)
    p.osc(1, level=0.3, wt=0.35, octave=1)
    p.filter("LP12", hz=2200, res=0.05, keytrack=0.5, env=0.1)
    low_clear(p)
    p.env(1, a=0.002, d=2.0, s=0.1, r=0.5, dcurve=-0.6)
    p.env(2, a=0.001, d=0.4, s=0.0, r=0.4)
    keys_voice(p)
    velocity(p, 0.75, 0.1)
    p.tone("CUTOFF", 0.15)
    p.lfo(1, "SINE", hz=0.5, mode="FREE")
    p.lfo(2, "SMOOTH_RANDOM", hz=1.5, mode="TRIG")
    p.set("macro2", 0.45)
    p.motion("LFO1", "PITCH", 0.003)
    p.motion("LFO2", "PITCH", 0.002)
    p.motion("LFO2", "AMP", 0.05)
    room(p, mix=0.14)
    grit(p, mode="SOFT", drive=0.35, tone=0.35, amount=0.5)
    p.eq(high=-4, high_hz=6000)
    p.master(0.64)
    p.doc("Piano-ish keys played back from a warped cassette", "C2–C6", "Lo-fi hip-hop, chillhop, bedroom pop",
          "Jazz chords, 7ths and 9ths, lazy timing", "SUPPORT",
          "The top is gone on purpose: pair with a crisp drum loop. MOTION 0 plays straight")
    out.append(p)

    p = K("NIGHT STAB", "ANALOG", "ANALOG")
    p.osc(0, level=0.65, wt=0.9, unison=3, detune=0.12, width=0.2)
    p.osc(1, level=0.35, wt=0.8, octave=1)
    p.filter("LP24", hz=900, res=0.2, keytrack=0.4, env=0.35)
    low_clear(p, 200)
    p.env(1, a=0.001, d=0.45, s=0.0, r=0.2)
    p.env(2, a=0.001, d=0.25, s=0.0, r=0.2)
    keys_voice(p)
    velocity(p, 0.6, 0.15)
    p.tone("CUTOFF", 0.18)
    p.lfo(1, "SINE", sync="2 BAR", mode="FREE")
    p.set("macro2", 0.3)
    p.motion("LFO1", "CUTOFF", 0.08)
    echo(p, time="3/16", mix=0.14, feedback=0.25, amount=0.12, pingpong=True)
    room(p, mix=0.12, decay=0.25)
    grit(p, mode="SOFT", drive=0.45, tone=0.6, base=0.45, amount=0.4)
    p.master(0.6)
    p.doc("Short filtered chord stab with a dotted echo", "C3–C5", "House, deep house, UK garage, rave",
          "Off-beat stabs and syncopated chord hits", "RHYTHM",
          "The echo is dotted-1/8; SPACE takes it from dry to dub. MOTION slowly sweeps the filter over 2 bars")
    out.append(p)

    p = K("VAPOR EP", "FM_BELL", "BASIC")
    p.osc(0, level=0.65, wt=0.18, unison=2, detune=0.06, width=0.4)
    p.osc(1, level=0.35, wt=0.0, fine=6)
    p.filter("LP12", hz=4500, res=0.05, keytrack=0.4)
    low_clear(p)
    p.env(1, a=0.002, d=1.8, s=0.3, r=0.5, dcurve=-0.6)
    p.env(4, a=0.001, d=0.5, s=0.05, r=0.3)
    p.mod("ENV4", "A_WTPOS", 0.2)
    keys_voice(p)
    velocity(p, 0.7, 0.0)
    p.mod("VELOCITY", "A_WTPOS", 0.12)
    p.tone("A_WTPOS", 0.12)
    p.lfo(1, "SINE", hz=0.35, mode="FREE")
    p.set("macro2", 0.4)
    p.motion("LFO1", "CHORUS_DEPTH", 0.3)
    p.chorus(mix=0.35, rate=0.35, depth=0.35)
    room(p, mix=0.2)
    grit(p, mode="SOFT", drive=0.3, tone=0.5, amount=0.4)
    p.master(0.62)
    p.doc("Chorused digital EP with a glassy strike, the 80s ballad sound", "C3–C5", "City pop, future funk, vaporwave, AOR",
          "Lush 7th and 9th chords", "SUPPORT",
          "Wide from the chorus: SPACE and MOTION down if it crowds the stereo field")
    out.append(p)

    p = K("IRON VIBES", "BASIC", "GLASS")
    p.osc(0, level=0.65, wt=0.05)
    p.osc(1, level=0.25, wt=0.55, octave=2)
    p.filter("LP12", hz=6000, res=0.05)
    low_clear(p, 160)
    p.env(1, a=0.002, d=2.2, s=0.0, r=0.6, dcurve=-0.6)
    p.env(4, a=0.001, d=0.2, s=0.0, r=0.1)
    p.mod("ENV4", "B_LEVEL", 0.25)
    keys_voice(p)
    velocity(p, 0.75, 0.0)
    p.mod("VELOCITY", "B_LEVEL", 0.1)
    p.tone("B_LEVEL", 0.15)
    p.lfo(1, "SINE", hz=5.5, mode="FREE")
    p.set("macro2", 0.5)
    p.motion("LFO1", "AMP", 0.2)
    p.context(motion_window=(0.05, 1.6))
    room(p, mix=0.18)
    grit(p, mode="SOFT", drive=0.3, tone=0.5, amount=0.4)
    p.master(0.64)
    p.doc("Vibraphone-like bars with a motor tremolo on MOTION", "C3–C6", "Jazz, trip-hop, lounge, noir score",
          "Four-note chords, sparse melodies", "SUPPORT",
          "MOTION is the vibes motor speed setting; at 0 the motor is off")
    out.append(p)

    p = K("GRAIN KEYS", "DIGITAL", "BASIC")
    p.osc(0, level=0.65, wt=0.35)
    p.osc(1, level=0.3, wt=0.0, octave=1)
    p.filter("LP12", hz=3200, res=0.1, keytrack=0.4, env=0.12)
    low_clear(p)
    p.env(1, a=0.002, d=1.0, s=0.2, r=0.35)
    p.env(2, a=0.001, d=0.3, s=0.05, r=0.3)
    keys_voice(p)
    velocity(p, 0.7, 0.1)
    p.tone("A_WTPOS", 0.2)
    p.lfo(1, "SAMPLE_HOLD", sync="1/8", mode="TRIG")
    p.set("macro2", 0.3)
    p.motion("LFO1", "DIST_MIX", 0.3)
    p.dist(mode="DOWNSAMPLE", drive=0.35, tone=0.5, mix=0.25)
    p.grit(("DIST_MIX", 0.5), ("DIST_DRIVE", 0.2))
    room(p, mix=0.14)
    p.master(0.62)
    p.doc("Keys through a damaged sampler: grain drops in and out in 1/8s", "C3–C5", "Glitch hop, IDM, experimental pop",
          "Chords and repeated figures", "TEXTURE",
          "MOTION is the 1/8 damage; GRIT is how damaged. Both at 0 give clean keys")
    out.append(p)

    p = K("POLY WARMTH", "ANALOG", "PWM")
    p.osc(0, level=0.65, wt=0.75, unison=2, detune=0.1, width=0.4)
    p.osc(1, level=0.3, wt=0.3, fine=-6)
    p.filter("LP24", hz=1400, res=0.12, keytrack=0.5, env=0.2)
    low_clear(p)
    p.env(1, a=0.003, d=1.0, s=0.5, r=0.4)
    p.env(2, a=0.002, d=0.5, s=0.2, r=0.4)
    keys_voice(p)
    velocity(p, 0.65, 0.12)
    p.tone("CUTOFF", 0.15)
    p.lfo(1, "SINE", hz=0.25, mode="TRIG")
    p.set("macro2", 0.35)
    p.motion("LFO1", "CUTOFF", 0.05)
    p.chorus(mix=0.35, rate=0.3, depth=0.4)
    room(p, mix=0.14)
    grit(p, mode="TUBE", drive=0.35, tone=0.5, amount=0.45)
    p.master(0.62)
    p.doc("Classic analog poly-synth keys with ensemble chorus", "C2–C5", "Synth-pop, disco, 80s, indie",
          "Chords, octave lines, arpeggios", "SUPPORT",
          "The bread-and-butter synth: TONE for brightness, SPACE for size")
    out.append(p)

    p = K("HARMONIUM", "ORGAN", "BASIC")
    p.osc(0, level=0.65, wt=0.7)
    p.noise(0.05, "BREATH", color=0.5, pitch=0.5, keytrack=True)
    p.filter("LP12", hz=2600, res=0.08, keytrack=0.4)
    low_clear(p)
    p.env(1, a=0.06, d=0.5, s=0.9, r=0.25)
    keys_voice(p, vel=0.5)
    p.mod("VELOCITY", "CUTOFF", 0.1)
    p.tone("CUTOFF", 0.15)
    p.lfo(1, "SINE", hz=0.6, mode="FREE")
    p.set("macro2", 0.35)
    p.motion("LFO1", "AMP", 0.1)
    p.motion("LFO1", "NOISE_LEVEL", 0.05)
    room(p, mix=0.16)
    grit(p, mode="SOFT", drive=0.3, tone=0.5, amount=0.4)
    p.master(0.62)
    p.doc("Reed organ with a breathing bellows on MOTION", "C2–C5", "Folk, chamber pop, film, drone-folk",
          "Held chords and drones; the bellows breathe on MOTION", "SUPPORT",
          "Mid-heavy and narrow: place it under acoustic guitar or voice without EQ")
    out.append(p)

    return out
