from lunatk import Preset
from bank._common import echo, grit, pressure, space, velocity, vibrato


def L(name, a="ANALOG", b="BASIC"):
    return Preset(name, "LEAD", a, b)


def mono_lead(p, glide=0.06, legato=True, always=False):
    return p.voice(voices=1, glide=glide, legato=legato, glide_always=always, bend=2)


def lead_fx(p, verb=0.12, delay=0.12, time="3/16", pingpong=False):
    space(p, verb, mode="PLATE", size=0.4, decay=0.35, damp=0.55, width=0.6, amount=0.18)
    if delay is not None:
        echo(p, time=time, mix=delay, feedback=0.22, amount=0.12, pingpong=pingpong, lowcut=0.45, highcut=0.45)
    return p


def presets():
    out = []

    p = L("SEARING WIRE", "SYNC_SWEEP", "ANALOG")
    p.osc(0, level=0.7, wt=0.2, warp="SYNC", warp_amt=0.18, unison=2, detune=0.08, width=0.2)
    p.osc(1, level=0.4, wt=0.9, octave=-1)
    p.filter("LP24", hz=2600, res=0.2, env=0.12, keytrack=0.5, drive=0.2)
    p.filter2("HP12", hz=160)
    p.env(1, a=0.004, d=0.4, s=0.85, r=0.18)
    p.env(2, a=0.002, d=0.5, s=0.4, r=0.2)
    p.env(4, a=0.01, d=0.6, s=0.25, r=0.2)
    p.mod("ENV4", "A_WARP", 0.25)
    mono_lead(p, glide=0.05)
    velocity(p, 0.5, 0.1)
    vibrato(p)
    pressure(p, "A_WARP", 0.2)
    p.tone("CUTOFF", 0.14)
    p.lfo(1, "TRIANGLE", hz=0.25, mode="TRIG")
    p.motion("LFO1", "A_WARP", 0.08)
    lead_fx(p)
    grit(p, mode="TUBE", drive=0.45, tone=0.55, base=0.25, amount=0.55)
    p.master(0.6)
    p.doc("Hard-sync lead that snarls on each note and cuts through guitars", "C4–C6", "Industrial rock, synth-rock, EBM, trailer",
          "Monophonic lines with slides; mod wheel for vibrato, pressure opens the sync", "FOREGROUND",
          "Give it 2–4 kHz and pull guitars back there; TONE is the brightness ride")
    p.context(legato=True)
    out.append(p)

    p = L("GLASS VOICE", "GLASS", "BASIC")
    p.osc(0, level=0.7, wt=0.25, unison=2, detune=0.06, width=0.25)
    p.osc(1, level=0.35, wt=0.0, octave=1)
    p.noise(0.05, "BREATH", color=0.4, pitch=0.6, keytrack=True)
    p.filter("LP12", hz=3800, res=0.1, keytrack=0.6, env=0.08)
    p.filter2("HP12", hz=180)
    p.env(1, a=0.03, d=0.6, s=0.8, r=0.35)
    p.env(2, a=0.02, d=0.6, s=0.5, r=0.3)
    p.voice(voices=4, glide=0.03, legato=False, bend=2)
    velocity(p, 0.55, 0.08)
    vibrato(p, depth=0.008)
    pressure(p, "CUTOFF", 0.12)
    p.tone("A_WTPOS", 0.2)
    p.lfo(1, "SINE", hz=0.35, mode="TRIG")
    p.motion("LFO1", "A_WTPOS", 0.06)
    lead_fx(p, verb=0.16, delay=0.1)
    grit(p, mode="SOFT", drive=0.35, tone=0.6, amount=0.5)
    p.master(0.65)
    p.doc("Soft, breathy, glass-toned lead that sits like a voice", "C4–C6", "Pop, ambient pop, R&B, film",
          "Slow melodies and long notes; up to four notes of harmony", "FOREGROUND",
          "Duck it under the real vocal or play it in the gaps; TONE sets how glassy it is")
    out.append(p)

    p = L("SHATTERED WHISTLE", "DIGITAL", "BASIC")
    p.osc(0, level=0.7, wt=0.15, warp="QUANTIZE", warp_amt=0.3)
    p.osc(1, level=0.3, wt=0.0, octave=1)
    p.filter("LP12", hz=4200, res=0.12, keytrack=0.5)
    p.filter2("HP12", hz=220)
    p.env(1, a=0.006, d=0.5, s=0.8, r=0.22)
    mono_lead(p, glide=0.08)
    velocity(p, 0.5, 0.08)
    vibrato(p)
    p.tone("A_WTPOS", 0.25)
    p.lfo(1, "SAMPLE_HOLD", sync="1/16", mode="TRIG")
    p.set("macro2", 0.3)
    p.motion("LFO1", "A_WARP", 0.32)
    lead_fx(p, delay=0.14, time="1/8")
    grit(p, mode="DOWNSAMPLE", drive=0.35, tone=0.6, amount=0.5)
    p.master(0.62)
    p.doc("Clean whistle that degrades into stepped digital grit", "C4–C7", "Glitch pop, hyperpop, game music, IDM",
          "Simple hooks; MOTION adds 1/16 digital stutter", "FOREGROUND",
          "A narrow sound: it cuts through at low level, so start quieter than you think")
    out.append(p)

    p = L("FORMANT CRY", "FORMANT", "BASIC")
    p.osc(0, level=0.75, wt=0.4, unison=3, detune=0.1, width=0.25)
    p.filter("FORMANT", cut=0.45, res=0.45, mix=0.75)
    p.filter2("HP12", hz=160)
    p.env(1, a=0.02, d=0.5, s=0.85, r=0.25)
    mono_lead(p, glide=0.07)
    velocity(p, 0.5, 0.0)
    p.mod("VELOCITY", "A_WTPOS", 0.12)
    vibrato(p)
    pressure(p, "CUTOFF", 0.2)
    p.tone("CUTOFF", 0.2)
    p.lfo(1, "TRIANGLE", sync="1/2", mode="TRIG")
    p.motion("LFO1", "CUTOFF", 0.2)
    p.motion("LFO1", "A_WTPOS", 0.15)
    lead_fx(p)
    grit(p, mode="TUBE", drive=0.4, tone=0.55, amount=0.5)
    p.master(0.6)
    p.doc("Vowel-shaped lead that sings between A and O", "C4–C6", "Future bass, melodic dubstep, synth-pop",
          "Expressive held notes; MOTION sweeps the vowel in half notes, TONE picks it", "FOREGROUND",
          "Vowels overlap a singer's: use it in instrumental sections or pan it off the vocal")
    out.append(p)

    p = L("PRESSURE LINE", "ANALOG", "ANALOG")
    p.osc(0, level=0.7, wt=0.85, unison=2, detune=0.08, width=0.2)
    p.osc(1, level=0.45, wt=0.7, fine=6)
    p.filter("LADDER", hz=1500, res=0.3, keytrack=0.6, env=0.12, drive=0.2)
    p.filter2("HP12", hz=150)
    p.env(1, a=0.005, d=0.5, s=0.85, r=0.2)
    p.env(2, a=0.01, d=0.5, s=0.35, r=0.2)
    mono_lead(p, glide=0.05)
    p.set("mpe", 1)
    velocity(p, 0.55, 0.12)
    vibrato(p)
    pressure(p, "CUTOFF", 0.25)
    p.mod("TIMBRE", "RES", 0.2)
    p.tone("CUTOFF", 0.15)
    p.lfo(1, "SINE", hz=0.2, mode="TRIG")
    p.motion("LFO1", "CUTOFF", 0.04)
    lead_fx(p)
    grit(p, mode="TUBE", drive=0.4, tone=0.6, amount=0.55)
    p.master(0.6)
    p.doc("Classic two-saw ladder lead built for expression: pressure opens it, timbre adds bite", "C3–C6",
          "Synthwave, prog, jazz-fusion, film", "Play it like an instrument: aftertouch or MPE pressure, wheel vibrato", "FOREGROUND",
          "On a plain keyboard, ride TONE instead of pressure; it answers the same way")
    out.append(p)

    p = L("HOLLOW REED", "PWM", "BASIC")
    p.osc(0, level=0.7, wt=0.0)
    p.osc(1, level=0.2, wt=0.33, octave=1)
    p.noise(0.07, "BREATH", color=0.5, pitch=0.55, keytrack=True)
    p.filter("LP12", hz=2400, res=0.15, keytrack=0.6, env=0.1)
    p.filter2("HP12", hz=180)
    p.env(1, a=0.035, d=0.4, s=0.85, r=0.15)
    p.env(2, a=0.03, d=0.3, s=0.6, r=0.15)
    mono_lead(p, glide=0.04)
    velocity(p, 0.6, 0.1)
    vibrato(p, depth=0.008, delay=0.4)
    pressure(p, "NOISE_LEVEL", 0.12)
    p.tone("CUTOFF", 0.14)
    p.lfo(1, "SINE", hz=4.8, mode="TRIG", delay=0.5, rise=0.6)
    p.set("macro2", 0.35)
    p.motion("LFO1", "AMP", 0.08)
    lead_fx(p, verb=0.16, delay=None)
    grit(p, mode="SOFT", drive=0.3, tone=0.5, amount=0.5)
    p.master(0.64)
    p.doc("Woody square-wave reed with a breath edge; MOTION adds a player's tremolo", "C4–C6", "Film, folk-electronic, ambient, game",
          "Legato phrases with breaths between them", "FOREGROUND",
          "Mid-focused and narrow: it reads over strings and pads without EQ")
    out.append(p)

    p = L("LUNAR SUPERLEAD", "ANALOG", "ANALOG")
    p.osc(0, level=0.7, wt=0.95, unison=7, detune=0.28, width=0.35, unimode="SUPER")
    p.osc(1, level=0.35, wt=0.9, octave=1, unison=3, detune=0.15, width=0.2)
    p.filter("LP24", hz=5200, res=0.1, keytrack=0.4, env=0.08)
    p.filter2("HP12", hz=200)
    p.env(1, a=0.004, d=0.5, s=0.85, r=0.25)
    p.env(2, a=0.002, d=0.4, s=0.5, r=0.25)
    p.voice(voices=6, glide=0.0, bend=2)
    velocity(p, 0.5, 0.08)
    vibrato(p)
    p.tone("CUTOFF", 0.15)
    p.lfo(1, "SINE", hz=0.2, mode="FREE")
    p.motion("LFO1", "A_DETUNE", 0.06)
    lead_fx(p, verb=0.14, delay=0.14, time="3/16", pingpong=True)
    grit(p, mode="SOFT", drive=0.35, tone=0.6, amount=0.5)
    p.master(0.55)
    p.doc("Big unison saw lead for hooks and drops", "C4–C6", "Trance, EDM, big-room, future rave",
          "Hooks and stabs; chords of two or three notes", "FOREGROUND",
          "High-passed at 200 Hz already; if it fights the vocal, pull SPACE down before cutting it")
    out.append(p)

    p = L("SIGNAL HORN", "ANALOG", "PWM")
    p.osc(0, level=0.7, wt=0.8, unison=2, detune=0.1, width=0.25)
    p.osc(1, level=0.4, wt=0.15, fine=-5)
    p.filter("LP24", hz=900, res=0.12, env=0.32, keytrack=0.5)
    p.filter2("HP12", hz=150)
    p.env(1, a=0.03, d=0.5, s=0.85, r=0.22)
    p.env(2, a=0.06, d=0.45, s=0.4, r=0.25, acurve=0.3)
    p.voice(voices=6, glide=0.0, bend=2)
    velocity(p, 0.6, 0.12)
    vibrato(p, delay=0.5)
    pressure(p, "CUTOFF", 0.15)
    p.tone("CUTOFF", 0.15)
    p.lfo(1, "SINE", hz=0.3, mode="TRIG")
    p.set("macro2", 0.3)
    p.motion("LFO1", "CUTOFF", 0.04)
    lead_fx(p, verb=0.15, delay=None)
    grit(p, mode="TUBE", drive=0.4, tone=0.55, amount=0.5)
    p.master(0.6)
    p.doc("Brassy synth lead with a swelling filter, polyphonic for section lines", "C3–C5", "Synthwave, funk, city pop, film",
          "Short swells and chordal stabs; accents open the brass", "FOREGROUND",
          "Its swell lives at 700 Hz–2 kHz: thin that range in keys while it plays")
    p.context(root=55)
    out.append(p)

    p = L("NEON PULSE", "PWM", "PWM")
    p.osc(0, level=0.7, wt=0.25)
    p.osc(1, level=0.5, wt=0.45, fine=7)
    p.filter("LP24", hz=3000, res=0.15, keytrack=0.5, env=0.08)
    p.filter2("HP12", hz=160)
    p.env(1, a=0.003, d=0.4, s=0.8, r=0.2)
    mono_lead(p, glide=0.06)
    velocity(p, 0.5, 0.1)
    vibrato(p)
    p.tone("CUTOFF", 0.15)
    p.lfo(1, "TRIANGLE", hz=0.6, mode="TRIG")
    p.motion("LFO1", "A_WTPOS", 0.18)
    p.motion("LFO1", "B_WTPOS", -0.12)
    lead_fx(p, delay=0.16, time="3/16", pingpong=True)
    grit(p, mode="SOFT", drive=0.35, tone=0.6, amount=0.5)
    p.master(0.6)
    p.doc("Two pulse waves with moving widths: a bright retro solo voice", "C4–C6", "Synthwave, outrun, 80s pop, game",
          "Fast runs and held notes with glide", "FOREGROUND",
          "MOTION is the pulse-width sweep; at 0 it holds still for dense mixes")
    out.append(p)

    p = L("FURNACE SCREAM", "ANALOG", "SYNC_SWEEP")
    p.osc(0, level=0.7, wt=0.95, unison=3, detune=0.12, width=0.2)
    p.osc(1, level=0.5, wt=0.3, warp="SYNC", warp_amt=0.3)
    p.filter("LP24", hz=3200, res=0.18, keytrack=0.4, drive=0.3)
    p.filter2("HP12", hz=200)
    p.env(1, a=0.003, d=0.4, s=0.9, r=0.18)
    p.env(4, a=0.001, d=0.25, s=0.3, r=0.2)
    p.mod("ENV4", "B_WARP", 0.25)
    mono_lead(p, glide=0.05)
    velocity(p, 0.45, 0.08)
    vibrato(p, depth=0.014)
    pressure(p, "B_WARP", 0.2)
    p.tone("CUTOFF", 0.14)
    p.lfo(1, "SINE", hz=5.8, mode="TRIG", delay=0.25, rise=0.3)
    p.set("macro2", 0.3)
    p.motion("LFO1", "PITCH", 0.006)
    lead_fx(p, verb=0.1, delay=0.1)
    grit(p, mode="HARD", drive=0.4, tone=0.5, base=0.4, amount=0.45)
    p.comp(mode="SINGLE", threshold=0.5, ratio=0.35, attack=0.2, release=0.3, gain=0.42, depth=0.5)
    p.master(0.55)
    p.doc("Distorted sync lead that screams without turning to fizz", "C4–C6", "Industrial metal, trailer, hard techno",
          "Held notes with bends; MOTION is automatic vibrato", "FOREGROUND",
          "It already carries distortion: don't add more, sit it with a high cut near 8 kHz if the cymbals are bright")
    out.append(p)

    p = L("FRAGILE SINE", "BASIC", "GLASS")
    p.osc(0, level=0.7, wt=0.03)
    p.osc(1, level=0.18, wt=0.35, octave=1)
    p.noise(0.03, "PINK", color=0.6, keytrack=False)
    p.filter("LP12", hz=5000, res=0.05, keytrack=0.4)
    p.filter2("HP12", hz=200)
    p.env(1, a=0.05, d=0.8, s=0.8, r=0.5)
    p.voice(voices=4, glide=0.04, bend=2)
    velocity(p, 0.65, 0.05)
    vibrato(p, depth=0.006, delay=0.6)
    p.tone("B_LEVEL", 0.2)
    p.lfo(1, "SINE", hz=4.5, mode="TRIG", delay=0.8, rise=1.0)
    p.set("macro2", 0.35)
    p.motion("LFO1", "AMP", 0.1)
    p.lfo(2, "SINE", hz=0.3, mode="TRIG")
    p.motion("LFO2", "B_LEVEL", 0.12)
    lead_fx(p, verb=0.2, delay=0.12, time="1/4")
    grit(p, mode="SOFT", drive=0.3, tone=0.5, amount=0.5)
    p.master(0.72)
    p.doc("Almost-pure sine lead with a faint glass overtone; intimate and exposed", "C4–C6", "Ambient, piano-led pop, film, lullaby",
          "Slow, sparse melodies; leave space around it", "FOREGROUND",
          "It is quiet in energy: low-cut everything else under 200 Hz rather than boosting it")
    out.append(p)

    p = L("RUST THEREMIN", "BASIC", "BASIC")
    p.osc(0, level=0.75, wt=0.12)
    p.filter("LP12", hz=3000, res=0.08, keytrack=0.5)
    p.filter2("HP12", hz=200)
    p.env(1, a=0.12, d=0.5, s=0.9, r=0.4)
    p.voice(voices=1, glide=0.22, legato=True, glide_always=True, bend=12)
    velocity(p, 0.4, 0.06)
    vibrato(p, depth=0.016, delay=0.1)
    p.tone("A_WTPOS", 0.2)
    p.lfo(1, "SINE", hz=5.5, mode="TRIG", delay=0.3, rise=0.8)
    p.set("macro2", 0.4)
    p.motion("LFO1", "PITCH", 0.008)
    lead_fx(p, verb=0.18, delay=0.1, time="1/4")
    grit(p, mode="TUBE", drive=0.4, tone=0.5, amount=0.5)
    p.master(0.68)
    p.doc("Gliding, wavering sine that slides into every note", "C4–C6", "Horror, sci-fi score, dark pop, lounge",
          "Slow lines; every note glides, so write the slide in", "FOREGROUND",
          "MOTION sets the waver; keep it low when doubling a vocal line")
    p.context(legato=True)
    out.append(p)

    p = L("DEGRADED LOOP", "ANALOG", "BASIC")
    p.osc(0, level=0.7, wt=0.7, unison=2, detune=0.06, width=0.2)
    p.filter("LP12", hz=2600, res=0.12, keytrack=0.4, env=0.06)
    p.filter2("HP12", hz=200)
    p.env(1, a=0.006, d=0.5, s=0.75, r=0.2)
    p.voice(voices=4, glide=0.0, bend=2)
    velocity(p, 0.55, 0.08)
    vibrato(p)
    p.tone("CUTOFF", 0.14)
    p.lfo(1, "SMOOTH_RANDOM", hz=1.6, mode="TRIG")
    p.lfo(2, "SINE", hz=0.5, mode="FREE")
    p.set("macro2", 0.45)
    p.motion("LFO1", "PITCH", 0.003)
    p.motion("LFO2", "PITCH", 0.0025)
    p.motion("LFO1", "CUTOFF", 0.04)
    lead_fx(p, verb=0.12, delay=0.12, time="1/4")
    grit(p, mode="DOWNSAMPLE", drive=0.3, tone=0.4, amount=0.45)
    p.eq(high=-3, high_hz=7000)
    p.master(0.62)
    p.doc("Worn-tape lead: warped pitch, dull top, a little unstable", "C4–C6", "Lo-fi, chillwave, bedroom pop, vaporwave",
          "Lazy melodies and short hooks", "FOREGROUND",
          "MOTION is the tape wow; at 0 it plays straight and in tune")
    out.append(p)

    p = L("BIT RELIC", "PWM", "BASIC")
    p.osc(0, level=0.7, wt=0.0, warp="QUANTIZE", warp_amt=0.4)
    p.osc(1, level=0.3, wt=0.0, octave=-1)
    p.filter("LP12", hz=6000, res=0.05)
    p.filter2("HP12", hz=180)
    p.env(1, a=0.001, d=0.3, s=0.8, r=0.08)
    mono_lead(p, glide=0.0, legato=False)
    velocity(p, 0.5, 0.05)
    p.mod("VELOCITY", "A_WARP", 0.15)
    vibrato(p)
    p.tone("A_WARP", 0.25)
    # Unipolar square, 0 then +1: the octave trill goes up, never down.
    p.lfo(1, "CUSTOM", sync="1/32", mode="TRIG", smooth=False, points=[0.0] * 16 + [1.0] * 16)
    p.set("macro2", 0.0)
    p.motion("LFO1", "PITCH", 0.5)
    lead_fx(p, verb=0.08, delay=0.12, time="1/8")
    grit(p, mode="BITCRUSH", drive=0.35, tone=0.6, amount=0.5)
    p.eq(high=-4, high_hz=9000)
    p.master(0.55)
    p.doc("Square-wave chip lead; MOTION flips it into octave arpeggio", "C4–C6", "Chiptune, hyperpop, game, indie-electronic",
          "Fast melodies; MOTION up for classic octave trills", "FOREGROUND",
          "Very bright by nature: the high shelf is already down 4 dB; pull TONE down under a vocal")
    out.append(p)

    p = L("STEEL FLUTE", "FM_BELL", "BASIC")
    p.osc(0, level=0.7, wt=0.2)
    p.noise(0.05, "BREATH", color=0.45, pitch=0.6)
    p.filter("LP12", hz=4500, res=0.1, keytrack=0.5, env=0.08)
    p.filter2("HP12", hz=220)
    p.env(1, a=0.04, d=0.5, s=0.85, r=0.25)
    p.env(4, a=0.02, d=0.3, s=0.1, r=0.2)
    p.mod("ENV4", "A_WTPOS", 0.2)
    mono_lead(p, glide=0.04)
    velocity(p, 0.55, 0.08)
    vibrato(p, depth=0.008, delay=0.45)
    pressure(p, "NOISE_LEVEL", 0.1)
    p.tone("A_WTPOS", 0.2)
    p.lfo(1, "SINE", hz=5.0, mode="TRIG", delay=0.6, rise=0.8)
    p.set("macro2", 0.35)
    p.motion("LFO1", "PITCH", 0.005)
    lead_fx(p, verb=0.18, delay=0.1, time="1/4")
    grit(p, mode="SOFT", drive=0.3, tone=0.5, amount=0.5)
    p.master(0.65)
    p.doc("Breathy FM flute with a metallic overtone on the attack", "C4–C6", "Film, world-electronic, ambient, game",
          "Legato phrases; wheel or MOTION for vibrato", "FOREGROUND",
          "The breath adds air at 6–8 kHz: pull SPACE down in dense mixes before EQ")
    out.append(p)

    p = L("GHOST VOWEL", "CHOIR", "FORMANT")
    p.osc(0, level=0.6, wt=0.4, unison=4, detune=0.15, width=0.3)
    p.osc(1, level=0.35, wt=0.6, octave=1, unison=2, detune=0.08)
    p.filter("FORMANT", cut=0.55, res=0.4, mix=0.6)
    p.filter2("HP12", hz=200)
    p.env(1, a=0.08, d=0.6, s=0.85, r=0.4)
    p.voice(voices=6, glide=0.0, bend=2)
    velocity(p, 0.5, 0.0)
    p.mod("VELOCITY", "A_WTPOS", 0.1)
    vibrato(p, depth=0.006)
    p.tone("CUTOFF", 0.2)
    p.lfo(1, "SMOOTH_RANDOM", hz=0.4, mode="TRIG")
    p.motion("LFO1", "CUTOFF", 0.08)
    p.motion("LFO1", "B_WTPOS", 0.15)
    lead_fx(p, verb=0.2, delay=0.1, time="1/4")
    grit(p, mode="SOFT", drive=0.3, tone=0.5, amount=0.5)
    p.master(0.6)
    p.doc("Wordless synthetic voice for lines and harmony", "C4–C6", "Dark pop, film, ambient, witch house",
          "Slow melodies and two- or three-part lines", "FOREGROUND",
          "Occupies the vocal range: use it where the singer rests")
    out.append(p)

    p = L("CORROSION LEAD", "ANALOG", "BASIC")
    p.osc(0, level=0.75, wt=0.95)
    p.filter("LADDER", hz=900, res=0.55, env=0.3, keytrack=0.5, drive=0.3)
    p.filter2("HP12", hz=180)
    p.env(1, a=0.002, d=0.4, s=0.7, r=0.12)
    p.env(2, a=0.001, d=0.25, s=0.15, r=0.1)
    mono_lead(p, glide=0.06)
    velocity(p, 0.35, 0.12)
    p.mod("VELOCITY", "RES", 0.08)
    vibrato(p)
    p.tone("CUTOFF", 0.2)
    p.lfo(1, "SINE", sync="1 BAR", mode="FREE")
    p.set("macro2", 0.3)
    p.motion("LFO1", "CUTOFF", 0.07)
    lead_fx(p, verb=0.08, delay=0.14, time="3/16")
    grit(p, mode="DIODE", drive=0.45, tone=0.5, amount=0.5)
    p.master(0.58)
    p.doc("Resonant acid lead that squelches above the bass", "C3–C5", "Acid, techno, electro, breakbeat",
          "Overlapping 16ths to slide; accent with velocity", "FOREGROUND",
          "Ride TONE through the section; if the resonance bites the snare, lower MOTION first")
    p.context(legato=True, root=48)
    out.append(p)

    p = L("OCTAVE PUNCH", "ANALOG", "BASIC")
    p.osc(0, level=0.7, wt=0.9, unison=3, detune=0.08, width=0.25, stack="OCTAVE")
    p.osc(1, level=0.3, wt=0.33, octave=-1)
    p.filter("LP24", hz=2200, res=0.12, env=0.25, keytrack=0.5)
    p.filter2("HP12", hz=170)
    p.env(1, a=0.002, d=0.3, s=0.7, r=0.12)
    p.env(2, a=0.001, d=0.2, s=0.3, r=0.12)
    p.voice(voices=4, glide=0.0, bend=2)
    velocity(p, 0.5, 0.12)
    vibrato(p)
    p.tone("CUTOFF", 0.15)
    p.lfo(1, "SAW_DOWN", sync="1/8", mode="TRIG")
    p.set("macro2", 0.0)
    p.motion("LFO1", "CUTOFF", 0.3)
    lead_fx(p, verb=0.1, delay=0.12, time="1/8")
    grit(p, mode="SOFT", drive=0.4, tone=0.6, amount=0.5)
    p.master(0.58)
    p.doc("Octave-stacked saw hook: punchy, simple, big", "C4–C6", "House, electro-pop, hyperpop, future bounce",
          "Short hooks and stabs; MOTION adds 1/8 filter chops", "FOREGROUND",
          "Its punch is the filter envelope: shorter notes read louder, so level it on the hook, not a held note")
    out.append(p)

    return out
