from lunatk import Preset
from bank._common import echo, grit, space, velocity


def P(name, a="ANALOG", b="ANALOG"):
    return Preset(name, "PAD", a, b)


def pad_voice(p, voices=8, vel=0.35):
    return p.voice(voices=voices, glide=0.0, vel=vel, bend=2)


def pad_space(p, mix=0.28, size=0.65, decay=0.38, amount=0.22, damp=0.55):
    """Hall at a controlled length (t60 = 0.6 + decay^2 x 18 s)."""
    return space(p, mix, mode="HALL", size=size, decay=decay, damp=damp, predelay=0.2, width=0.9, amount=amount)


def keep_low_clear(p, hz=140):
    return p.filter2("HP12", hz=hz, res=0.0)


def presets():
    out = []

    p = P("ASH VEIL", "ANALOG", "ANALOG")
    p.osc(0, level=0.65, wt=0.55, unison=5, detune=0.22, width=0.4)
    p.osc(1, level=0.4, wt=0.4, octave=-1, unison=3, detune=0.15, width=0.0)
    p.filter("LP24", hz=1300, res=0.15, keytrack=0.4, env=0.1)
    keep_low_clear(p, 170)
    p.env(1, a=0.9, d=1.5, s=0.9, r=1.6)
    p.env(2, a=1.5, d=2.5, s=0.6, r=1.6)
    pad_voice(p)
    velocity(p, 0.35, 0.06)
    p.tone("CUTOFF", 0.15)
    p.lfo(1, "SINE", hz=0.08, mode="TRIG")
    p.lfo(2, "SMOOTH_RANDOM", hz=0.2, mode="TRIG")
    p.motion("LFO1", "CUTOFF", 0.08)
    p.motion("LFO2", "A_WTPOS", 0.1)
    p.chorus(mix=0.25, rate=0.15, depth=0.4)
    pad_space(p)
    p.set("reverb.width", 0.6)
    grit(p, mode="TUBE", drive=0.35, tone=0.5, amount=0.5)
    p.master(0.6)
    p.doc("Warm, dark analog pad that breathes slowly", "C3–C5", "Film, ambient, darkwave, cinematic pop",
          "Sustained chords, change every bar or two", "SUPPORT",
          "High-passed at 140 Hz: it will not fight the bass. Lower SPACE before lowering the fader")
    out.append(p)

    p = P("GLASS CATHEDRAL", "GLASS", "GLASS")
    p.osc(0, level=0.6, wt=0.3, unison=4, detune=0.12, width=0.8)
    p.osc(1, level=0.35, wt=0.55, octave=1, unison=3, detune=0.1, width=0.8)
    p.filter("LP12", hz=5200, res=0.1, keytrack=0.3)
    keep_low_clear(p, 180)
    p.env(1, a=0.6, d=2.0, s=0.85, r=2.0)
    pad_voice(p)
    velocity(p, 0.35, 0.05)
    p.tone("B_LEVEL", 0.25)
    p.lfo(1, "TRIANGLE", hz=0.12, mode="TRIG")
    p.motion("LFO1", "A_WTPOS", 0.15)
    p.motion("LFO1", "B_WTPOS", -0.12)
    p.hyper(mix=0.2, detune=0.2, rate=0.25, dim=0.25)
    pad_space(p, mix=0.3, size=0.75, decay=0.42)
    grit(p, mode="DOWNSAMPLE", drive=0.3, tone=0.6, amount=0.4)
    p.eq(high=-3, high_hz=9000)
    p.master(0.6)
    p.doc("Shimmering glass partials in a large hall", "C3–C6", "Ambient, post-rock, worship, film",
          "Open voicings, long holds", "SUPPORT",
          "The shimmer is 2–6 kHz: keep hi-hats darker or pull TONE down under them")
    out.append(p)

    p = P("CORRODED HALO", "HARMONIC_SWEEP", "ANALOG")
    p.osc(0, level=0.6, wt=0.5, unison=4, detune=0.18, width=0.7)
    p.osc(1, level=0.4, wt=0.6, unison=2, detune=0.1, fine=-6, width=0.5)
    p.filter("LP24", hz=2400, res=0.12, keytrack=0.3)
    keep_low_clear(p)
    p.env(1, a=0.7, d=1.5, s=0.85, r=1.5)
    pad_voice(p)
    velocity(p, 0.35, 0.05)
    p.tone("CUTOFF", 0.15)
    p.lfo(1, "SMOOTH_RANDOM", hz=0.3, mode="TRIG")
    p.motion("LFO1", "A_WTPOS", 0.15)
    p.motion("LFO1", "DIST_MIX", 0.12)
    p.dist(mode="DOWNSAMPLE", drive=0.3, tone=0.5, mix=0.2)
    p.grit(("DIST_MIX", 0.45), ("DIST_DRIVE", 0.2))
    p.chorus(mix=0.3, rate=0.2, depth=0.5)
    pad_space(p, mix=0.26)
    p.master(0.6)
    p.doc("Beautiful chord pad with a corroded, sample-rate-reduced edge", "C3–C5", "Industrial ambient, dark pop, trailer",
          "Slow chords; let the damage drift in and out", "TEXTURE",
          "The grit lives above 3 kHz: GRIT 0 and MOTION 0 give you the clean pad underneath")
    out.append(p)

    p = P("SUSPENDED BREATH", "BASIC", "GLASS")
    p.osc(0, level=0.55, wt=0.1, unison=3, detune=0.08, width=0.6)
    p.osc(1, level=0.2, wt=0.4, octave=1)
    p.noise(0.22, "BREATH", color=0.45, pitch=0.55, keytrack=True)
    p.filter("LP12", hz=3800, res=0.1, keytrack=0.4)
    keep_low_clear(p, 170)
    p.env(1, a=1.0, d=1.5, s=0.9, r=1.8)
    pad_voice(p)
    velocity(p, 0.35, 0.05)
    p.tone("NOISE_LEVEL", 0.15)
    p.lfo(1, "SINE", hz=0.15, mode="TRIG")
    p.motion("LFO1", "NOISE_LEVEL", 0.1)
    p.motion("LFO1", "CUTOFF", 0.05)
    pad_space(p, mix=0.3)
    grit(p, mode="SOFT", drive=0.3, tone=0.5, amount=0.4)
    p.master(0.64)
    p.doc("Pitched breath over a soft sine: air with a note in it", "C3–C6", "Ambient, singer-songwriter, neo-classical, film",
          "Sparse chords, long notes", "TEXTURE",
          "Sits behind a vocal almost by itself; TONE trades breath for tone")
    out.append(p)

    p = P("IRON LUNG", "ANALOG", "SPECTRAL_COMB")
    p.osc(0, level=0.6, wt=0.6, unison=3, detune=0.12, width=0.6)
    p.osc(1, level=0.35, wt=0.4)
    p.noise(0.06, "METAL", color=0.5, pitch=0.5, keytrack=True)
    p.filter("COMB_POS", cut=0.5, res=0.35, keytrack=1.0, mix=0.45)
    p.filter2("LP24", hz=2600, res=0.1)
    p.env(1, a=0.5, d=1.5, s=0.9, r=1.4)
    pad_voice(p)
    velocity(p, 0.35, 0.0)
    p.tone("F2_CUTOFF", 0.15)
    p.pump(sync="1/2", depth=0.5 / 0.5, default=0.5, sharpness=1.8)
    pad_space(p, mix=0.24)
    grit(p, mode="HARD", drive=0.3, tone=0.45, amount=0.4)
    p.eq(low=-6, low_hz=150)
    p.master(0.6)
    p.doc("Metal-tinged pad that inhales and exhales in half notes", "C3–C5", "Industrial, dark techno breakdowns, horror",
          "Hold chords across bars; the breathing is tempo-synced", "TEXTURE",
          "MOTION is the breath depth: 0 for a steady bed. Start chords on a beat so the breath lines up")
    out.append(p)

    p = P("NIGHT CHOIR", "CHOIR", "CHOIR")
    p.osc(0, level=0.6, wt=0.35, unison=5, detune=0.18, width=0.7)
    p.osc(1, level=0.35, wt=0.6, octave=1, unison=3, detune=0.12, width=0.6)
    p.filter("FORMANT", cut=0.5, res=0.35, mix=0.55)
    keep_low_clear(p, 160)
    p.env(1, a=0.8, d=1.5, s=0.9, r=1.6)
    pad_voice(p)
    velocity(p, 0.35, 0.0)
    p.tone("CUTOFF", 0.15)
    p.lfo(1, "SMOOTH_RANDOM", hz=0.2, mode="TRIG")
    p.lfo(2, "SINE", hz=0.1, mode="TRIG")
    p.motion("LFO1", "CUTOFF", 0.08)
    p.motion("LFO2", "A_WTPOS", 0.15)
    p.chorus(mix=0.25, rate=0.12, depth=0.35)
    pad_space(p, mix=0.3, size=0.7, decay=0.4)
    grit(p, mode="SOFT", drive=0.3, tone=0.5, amount=0.4)
    p.master(0.6)
    p.doc("Wordless choir that drifts slowly between vowels", "C3–C5", "Film, sacred-ambient, dark pop, game",
          "Slow chords; voice-lead them like a choir", "SUPPORT",
          "It shares the vocal range: carve 1–3 kHz under a lead singer or use it between lines")
    out.append(p)

    p = P("WARM TAPE BED", "ANALOG", "BASIC")
    p.osc(0, level=0.6, wt=0.5, unison=3, detune=0.15, width=0.6)
    p.osc(1, level=0.35, wt=0.33, fine=5)
    p.filter("LP12", hz=1800, res=0.1, keytrack=0.4)
    keep_low_clear(p)
    p.env(1, a=0.35, d=1.2, s=0.9, r=1.0)
    pad_voice(p)
    velocity(p, 0.4, 0.06)
    p.tone("CUTOFF", 0.15)
    p.lfo(1, "SMOOTH_RANDOM", hz=1.3, mode="TRIG")
    p.lfo(2, "SINE", hz=0.45, mode="FREE")
    p.set("macro2", 0.45)
    p.motion("LFO1", "PITCH", 0.002)
    p.motion("LFO2", "PITCH", 0.002)
    p.motion("LFO1", "CUTOFF", 0.04)
    p.chorus(mix=0.25, rate=0.3, depth=0.35)
    pad_space(p, mix=0.2, decay=0.3)
    grit(p, mode="SOFT", drive=0.3, tone=0.4, amount=0.5)
    p.eq(high=-4, high_hz=6500)
    p.master(0.62)
    p.doc("Warm, slightly warped chord bed like a worn cassette", "C3–C5", "Lo-fi hip-hop, bedroom pop, chillwave",
          "Chords on the bar; works for 7ths and 9ths", "SUPPORT",
          "The top is already rolled off: it sits behind drums without EQ. MOTION 0 plays in tune")
    out.append(p)

    p = P("SPECTRAL TIDE", "SPECTRAL_COMB", "HARMONIC_SWEEP")
    p.osc(0, level=0.6, wt=0.3, unison=4, detune=0.15, width=0.75)
    p.osc(1, level=0.35, wt=0.4, unison=2, detune=0.1, width=0.6)
    p.filter("LP24", hz=3000, res=0.12, keytrack=0.3)
    keep_low_clear(p)
    p.env(1, a=1.2, d=2.0, s=0.9, r=2.0)
    pad_voice(p)
    velocity(p, 0.3, 0.05)
    p.tone("CUTOFF", 0.15)
    p.lfo(1, "TRIANGLE", sync="2 BAR", mode="TRIG")
    p.lfo(2, "SINE", sync="4 BAR", mode="TRIG")
    p.motion("LFO1", "A_WTPOS", 0.2)
    p.motion("LFO2", "B_WTPOS", 0.2)
    p.phaser(mix=0.25, rate=0.08, depth=0.5)
    pad_space(p, mix=0.3)
    grit(p, mode="SOFT", drive=0.3, tone=0.5, amount=0.4)
    p.master(0.6)
    p.doc("Comb-filtered harmonics that roll in and out over bars", "C3–C5", "Ambient techno, progressive, film",
          "Hold a chord for 4–8 bars and let it evolve", "TEXTURE",
          "Its movement is tempo-synced: it rises into bar 3 of every 4. Pull MOTION down in busy sections")
    out.append(p)

    p = P("FROZEN STRINGS", "ANALOG", "ANALOG")
    p.osc(0, level=0.6, wt=0.85, unison=7, detune=0.2, width=0.7, unimode="SUPER")
    p.osc(1, level=0.35, wt=0.7, octave=1, unison=4, detune=0.15, width=0.6)
    p.filter("LP24", hz=2400, res=0.08, keytrack=0.5, env=0.08)
    keep_low_clear(p, 150)
    p.env(1, a=0.45, d=1.0, s=0.9, r=0.9)
    p.env(2, a=0.6, d=1.5, s=0.7, r=0.9)
    pad_voice(p)
    velocity(p, 0.45, 0.1)
    p.tone("CUTOFF", 0.15)
    p.lfo(1, "SINE", hz=5.0, mode="TRIG", delay=0.6, rise=1.0)
    p.set("macro2", 0.35)
    p.motion("LFO1", "PITCH", 0.002)
    p.lfo(2, "SINE", hz=0.15, mode="TRIG")
    p.motion("LFO2", "CUTOFF", 0.05)
    p.chorus(mix=0.3, rate=0.25, depth=0.4)
    pad_space(p, mix=0.26, size=0.7)
    grit(p, mode="TUBE", drive=0.3, tone=0.5, amount=0.4)
    p.master(0.58)
    p.doc("Synth string ensemble with a slow bow and gentle vibrato", "C3–C6", "Film, synthwave, pop ballad, trailer",
          "Legato chords; velocity sets the bow pressure", "SUPPORT",
          "Layer under real strings for size, or alone as a warm bed; TONE darkens it behind vocals")
    out.append(p)

    p = P("DUST HARMONICS", "HARMONIC_SWEEP", "BASIC")
    p.osc(0, level=0.65, wt=0.25, unison=3, detune=0.1, width=0.6)
    p.osc(1, level=0.3, wt=0.0, octave=1)
    p.filter("LP12", hz=4000, res=0.08, keytrack=0.3)
    keep_low_clear(p)
    p.env(1, a=0.8, d=1.5, s=0.9, r=1.6)
    p.env(4, a=3.0, d=2.0, s=0.8, r=1.5)
    p.mod("ENV4", "A_WTPOS", 0.2)
    pad_voice(p)
    velocity(p, 0.35, 0.0)
    p.mod("VELOCITY", "A_WTPOS", 0.1)
    p.tone("A_WTPOS", 0.15)
    p.lfo(1, "SINE", hz=0.18, mode="TRIG")
    p.motion("LFO1", "A_WTPOS", 0.18)
    p.motion("LFO1", "CUTOFF", 0.07)
    p.chorus(mix=0.25, rate=0.18, depth=0.4)
    pad_space(p, mix=0.28)
    grit(p, mode="SOFT", drive=0.3, tone=0.5, amount=0.4)
    p.master(0.62)
    p.doc("Pure harmonics that open slowly over three seconds", "C3–C6", "Ambient, neo-classical, meditation, film",
          "Hold chords; the longer you hold, the more partials appear", "SUPPORT",
          "Starts nearly pure: great under piano. TONE sets how far it opens")
    out.append(p)

    p = P("FAULT LINE", "ANALOG", "HARMONIC_SWEEP")
    p.osc(0, level=0.6, wt=0.6, unison=4, detune=0.2, width=0.6, unimode="RANDOM")
    p.osc(1, level=0.35, wt=0.5, unison=2, detune=0.12)
    p.filter("LP24", hz=1800, res=0.15, keytrack=0.3)
    keep_low_clear(p)
    p.env(1, a=0.7, d=1.5, s=0.9, r=1.4)
    pad_voice(p)
    velocity(p, 0.35, 0.05)
    p.tone("CUTOFF", 0.15)
    p.lfo(1, "SMOOTH_RANDOM", hz=0.35, mode="TRIG")
    p.lfo(2, "SMOOTH_RANDOM", hz=0.18, mode="TRIG")
    p.set("macro2", 0.4)
    p.motion("LFO1", "A_FINE", 0.12)
    p.motion("LFO2", "B_FINE", -0.12)
    p.motion("LFO1", "CUTOFF", 0.05)
    p.chorus(mix=0.2, rate=0.2, depth=0.35)
    pad_space(p, mix=0.28)
    grit(p, mode="DIODE", drive=0.3, tone=0.45, amount=0.4)
    p.master(0.6)
    p.doc("Chord pad whose voices drift slightly apart and back: uneasy, never wrong", "C3–C5", "Horror, psychological thriller, dark ambient",
          "Sustained chords, especially minor and suspended", "TEXTURE",
          "MOTION is how far it drifts; at 0 it is a stable dark pad for dialogue scenes")
    out.append(p)

    p = P("HALOGEN", "ANALOG", "ANALOG")
    p.osc(0, level=0.6, wt=0.95, unison=9, detune=0.3, width=0.75, unimode="SUPER")
    p.osc(1, level=0.3, wt=0.9, octave=1, unison=5, detune=0.2, width=0.7)
    p.filter("LP24", hz=4200, res=0.1, keytrack=0.4, env=0.1)
    keep_low_clear(p, 180)
    p.env(1, a=0.08, d=0.8, s=0.85, r=0.8)
    p.env(2, a=0.05, d=0.6, s=0.5, r=0.7)
    pad_voice(p)
    velocity(p, 0.5, 0.1)
    p.tone("CUTOFF", 0.16)
    p.pump(sync="1/4", depth=0.5, default=0.0, sharpness=3.0)
    p.hyper(mix=0.2, detune=0.2, rate=0.35)
    pad_space(p, mix=0.22, decay=0.32)
    grit(p, mode="SOFT", drive=0.35, tone=0.6, amount=0.4)
    p.master(0.55)
    p.doc("Bright supersaw chord pad for builds and drops", "C3–C6", "EDM, trance, future bass, pop drops",
          "Full chords; MOTION adds a 1/4 pump for tracks without sidechain", "FOREGROUND",
          "High-passed at 180 Hz: stack it over a bass freely. Start chords on the beat when pumping")
    out.append(p)

    p = P("VELVET CHORDS", "ANALOG", "BASIC")
    p.osc(0, level=0.6, wt=0.45, unison=3, detune=0.12, width=0.55)
    p.osc(1, level=0.35, wt=0.2)
    p.filter("LP24", hz=1500, res=0.08, keytrack=0.5, env=0.1)
    keep_low_clear(p)
    p.env(1, a=0.12, d=1.0, s=0.85, r=0.7)
    p.env(2, a=0.1, d=0.8, s=0.5, r=0.6)
    pad_voice(p)
    velocity(p, 0.5, 0.1)
    p.tone("CUTOFF", 0.15)
    p.lfo(1, "SINE", hz=0.2, mode="TRIG")
    p.set("macro2", 0.35)
    p.motion("LFO1", "CUTOFF", 0.05)
    p.chorus(mix=0.3, rate=0.25, depth=0.4)
    pad_space(p, mix=0.2, decay=0.3)
    grit(p, mode="TUBE", drive=0.3, tone=0.5, amount=0.4)
    p.master(0.62)
    p.doc("Soft, warm chord pad with a quick-enough attack to play rhythms", "C3–C5", "Pop, R&B, gospel-pop, indie",
          "Chords on the beat or the bar", "SUPPORT",
          "A do-everything bed: put it 3–6 dB under the vocal and it will not need EQ")
    out.append(p)

    p = P("UNDERCURRENT", "ANALOG", "GROWL")
    p.osc(0, level=0.6, wt=0.4, unison=3, detune=0.15, width=0.1)
    p.osc(1, level=0.3, wt=0.15)
    p.filter("LP24", hz=900, res=0.18, keytrack=0.4)
    keep_low_clear(p, 150)
    p.env(1, a=0.9, d=1.5, s=0.9, r=1.5)
    pad_voice(p)
    velocity(p, 0.35, 0.05)
    p.tone("CUTOFF", 0.15)
    p.lfo(1, "SINE", hz=0.07, mode="TRIG")
    p.motion("LFO1", "CUTOFF", 0.08)
    p.phaser(mix=0.35, rate=0.06, depth=0.6, freq=0.35)
    p.mod("MACRO2", "PHASER_MIX", 0.2)
    pad_space(p, mix=0.24)
    p.set("reverb.width", 0.5)
    grit(p, mode="DIODE", drive=0.3, tone=0.45, amount=0.4)
    p.master(0.62)
    p.doc("Low, dark, phasing pad for tension under a scene", "C2–C4", "Thriller score, dark techno, drone-pop",
          "Low chords and open fifths", "SUPPORT",
          "It sits in 200–800 Hz: keep the bass simple under it and let this carry the harmony")
    p.context(shift=-12)
    out.append(p)

    p = P("PULSE CLOUD", "PWM", "PWM")
    p.osc(0, level=0.6, wt=0.3, unison=3, detune=0.15, width=0.6)
    p.osc(1, level=0.4, wt=0.5, unison=2, detune=0.1, fine=-5, width=0.5)
    p.filter("LP24", hz=2200, res=0.1, keytrack=0.4)
    keep_low_clear(p)
    p.env(1, a=0.3, d=1.0, s=0.9, r=1.0)
    pad_voice(p)
    velocity(p, 0.4, 0.06)
    p.tone("CUTOFF", 0.15)
    p.lfo(1, "TRIANGLE", hz=0.35, mode="FREE")
    p.lfo(2, "TRIANGLE", hz=0.23, mode="FREE", phase=0.5)
    p.motion("LFO1", "A_WTPOS", 0.2)
    p.motion("LFO2", "B_WTPOS", 0.2)
    p.chorus(mix=0.3, rate=0.2, depth=0.4)
    pad_space(p, mix=0.24)
    grit(p, mode="SOFT", drive=0.3, tone=0.5, amount=0.4)
    p.master(0.6)
    p.doc("Classic PWM string pad with two widths drifting against each other", "C3–C5", "Synthwave, 80s pop, new wave, retro score",
          "Chords, octaves, slow melodies", "SUPPORT",
          "Its movement is the pulse width; MOTION 0 leaves a still, clean pulse pad")
    out.append(p)

    p = P("FM MIST", "FM_BELL", "GLASS")
    p.osc(0, level=0.6, wt=0.2, unison=3, detune=0.1, width=0.6)
    p.osc(1, level=0.3, wt=0.3, octave=1, width=0.5)
    p.filter("LP12", hz=4200, res=0.08, keytrack=0.3)
    keep_low_clear(p, 170)
    p.env(1, a=0.6, d=1.5, s=0.85, r=1.8)
    pad_voice(p)
    velocity(p, 0.35, 0.0)
    p.mod("VELOCITY", "A_WTPOS", 0.1)
    p.tone("A_WTPOS", 0.15)
    p.lfo(1, "SINE", hz=0.12, mode="TRIG")
    p.motion("LFO1", "A_WTPOS", 0.1)
    p.motion("LFO1", "B_LEVEL", 0.1)
    p.chorus(mix=0.25, rate=0.15, depth=0.35)
    pad_space(p, mix=0.3, size=0.7)
    grit(p, mode="SOFT", drive=0.3, tone=0.5, amount=0.4)
    p.master(0.62)
    p.doc("Soft FM bell partials blurred into a pad", "C3–C6", "Ambient, lo-fi, new age, film",
          "Open chords and slow melodies", "SUPPORT",
          "Glassy but gentle: it layers under piano or guitar without masking them")
    out.append(p)

    p = P("VOID BLOOM", "VOID_FOLD", "ANALOG")
    p.osc(0, level=0.55, wt=0.05, unison=3, detune=0.1, width=0.6)
    p.osc(1, level=0.35, wt=0.3, unison=2, detune=0.1)
    p.filter("LP24", hz=2600, res=0.1, keytrack=0.3)
    keep_low_clear(p)
    p.env(1, a=0.9, d=1.5, s=0.9, r=1.5)
    p.env(4, a=2.5, d=2.0, s=0.7, r=1.5)
    p.mod("ENV4", "A_WTPOS", 0.3)
    pad_voice(p)
    velocity(p, 0.35, 0.0)
    p.mod("VELOCITY", "A_WTPOS", 0.1)
    p.tone("CUTOFF", 0.15)
    p.lfo(1, "SINE", hz=0.15, mode="TRIG")
    p.motion("LFO1", "A_WTPOS", 0.1)
    p.chorus(mix=0.25, rate=0.18, depth=0.4)
    pad_space(p, mix=0.26)
    grit(p, mode="SINFOLD", drive=0.25, tone=0.45, amount=0.35)
    p.master(0.6)
    p.doc("Pad that blooms from sine into folded harmonics as you hold it", "C3–C5", "Dark ambient, industrial, sci-fi score",
          "Hold chords for two bars or more", "TEXTURE",
          "The bloom is the point: short chords stay soft. TONE darkens the folded top")
    out.append(p)

    p = P("RUINED ORGAN", "ORGAN", "ORGAN")
    p.osc(0, level=0.6, wt=0.5, unison=2, detune=0.06, width=0.5)
    p.osc(1, level=0.3, wt=0.8, octave=1, width=0.4)
    p.filter("LP12", hz=3000, res=0.08, keytrack=0.3)
    keep_low_clear(p)
    p.env(1, a=0.25, d=1.0, s=0.9, r=0.9)
    pad_voice(p)
    velocity(p, 0.35, 0.05)
    p.tone("A_WTPOS", 0.2)
    p.lfo(1, "SINE", hz=5.5, mode="FREE")
    p.lfo(2, "SMOOTH_RANDOM", hz=0.7, mode="TRIG")
    p.set("macro2", 0.4)
    p.motion("LFO1", "AMP", 0.06)
    p.motion("LFO2", "PITCH", 0.002)
    p.chorus(mix=0.35, rate=0.55, depth=0.35)
    pad_space(p, mix=0.24, decay=0.35)
    grit(p, mode="SOFT", drive=0.35, tone=0.4, amount=0.45)
    p.eq(high=-3, high_hz=6000)
    p.master(0.62)
    p.doc("Drawbar organ chords through a tired rotary and warped tape", "C3–C5", "Gothic pop, indie, psych, film",
          "Sustained chords and slow changes", "SUPPORT",
          "MOTION is the rotary and tape wear: 0 gives a clean organ bed")
    out.append(p)

    p = P("HOLLOW SKY", "PWM", "GLASS")
    p.osc(0, level=0.6, wt=0.05, unison=3, detune=0.12, width=0.6)
    p.osc(1, level=0.3, wt=0.5, octave=1, unison=2, detune=0.08, width=0.6)
    p.filter("LP12", hz=3200, res=0.08, keytrack=0.3)
    p.filter2("NOTCH", hz=1100, res=0.3)
    p.env(1, a=0.6, d=1.5, s=0.9, r=1.6)
    pad_voice(p)
    velocity(p, 0.35, 0.05)
    p.tone("CUTOFF", 0.15)
    p.lfo(1, "SINE", hz=0.1, mode="TRIG")
    p.motion("LFO1", "F2_CUTOFF", 0.12)
    p.hyper(mix=0.2, detune=0.2, rate=0.2, dim=0.3)
    pad_space(p, mix=0.3, size=0.75)
    grit(p, mode="SOFT", drive=0.3, tone=0.5, amount=0.4)
    p.eq(low=-8, low_hz=160)
    p.master(0.6)
    p.doc("Hollow, notched pad with an open sky above it", "C3–C6", "Post-rock, ambient pop, shoegaze, film",
          "Wide voicings and pedal tones", "SUPPORT",
          "Scooped at 1 kHz already: it leaves the middle to vocals and guitars")
    out.append(p)

    p = P("TENSION FIELD", "ANALOG", "SPECTRAL_COMB")
    p.osc(0, level=0.6, wt=0.6, unison=4, detune=0.18, width=0.6)
    p.osc(1, level=0.35, wt=0.5, fine=-20)
    p.filter("LP24", hz=900, res=0.2, keytrack=0.3)
    keep_low_clear(p)
    p.env(1, a=1.5, d=2.0, s=0.9, r=1.5)
    p.env(4, a=6.0, d=1.0, s=1.0, r=1.5, acurve=0.4)
    p.mod("ENV4", "CUTOFF", 0.25)
    pad_voice(p)
    velocity(p, 0.3, 0.0)
    p.tone("CUTOFF", 0.15)
    p.lfo(1, "TRIANGLE", hz=0.09, mode="TRIG")
    p.motion("LFO1", "FLANGER_DEPTH", 0.25)
    p.flanger(mix=0.3, rate=0.05, depth=0.4, feedback=0.6)
    pad_space(p, mix=0.28)
    grit(p, mode="DIODE", drive=0.3, tone=0.45, amount=0.4)
    p.master(0.6)
    p.doc("Slowly rising, flanging pad that builds unease over six seconds", "C3–C5", "Thriller, horror, trailer build",
          "Hold one chord across a build; retrigger to restart the rise", "TRANSITION",
          "It rises on its own: automate TONE down to hold it back, or MOTION 0 for a flat bed")
    out.append(p)

    p = P("LUMEN", "GLASS", "BASIC")
    p.osc(0, level=0.6, wt=0.2, unison=2, detune=0.06, width=0.5)
    p.osc(1, level=0.3, wt=0.33, octave=1)
    p.filter("LP12", hz=3600, res=0.08, keytrack=0.4, env=0.12)
    keep_low_clear(p, 160)
    p.env(1, a=0.15, d=2.5, s=0.6, r=2.2)
    p.env(2, a=0.05, d=1.5, s=0.3, r=1.5)
    pad_voice(p)
    velocity(p, 0.5, 0.1)
    p.tone("CUTOFF", 0.15)
    p.lfo(1, "SINE", hz=0.2, mode="TRIG")
    p.set("macro2", 0.35)
    p.motion("LFO1", "A_WTPOS", 0.1)
    p.chorus(mix=0.25, rate=0.2, depth=0.35)
    pad_space(p, mix=0.28, size=0.7)
    grit(p, mode="SOFT", drive=0.3, tone=0.5, amount=0.4)
    p.master(0.64)
    p.doc("Glassy key-pad: a soft strike that blooms into a sustained glow", "C3–C6", "Ambient pop, lo-fi, piano-led film cues",
          "Arpeggiated chords or held voicings", "SUPPORT",
          "Pairs with a real piano: pan them apart and let this fill the sustain")
    out.append(p)

    p = P("SEAFLOOR", "ANALOG", "HARMONIC_SWEEP")
    p.osc(0, level=0.6, wt=0.35, unison=3, detune=0.12, width=0.55)
    p.osc(1, level=0.3, wt=0.3, octave=-1)
    p.filter("LP24", hz=650, res=0.2, keytrack=0.4)
    p.filter2("COMB_NEG", hz=300, res=0.35, keytrack=1.0, mix=0.4)
    p.env(1, a=1.2, d=2.0, s=0.9, r=2.0)
    pad_voice(p)
    velocity(p, 0.3, 0.04)
    p.tone("CUTOFF", 0.15)
    p.lfo(1, "SINE", hz=0.06, mode="TRIG")
    p.motion("LFO1", "F2_CUTOFF", 0.1)
    p.motion("LFO1", "CUTOFF", 0.06)
    pad_space(p, mix=0.3, damp=0.75)
    grit(p, mode="SOFT", drive=0.3, tone=0.4, amount=0.4)
    p.eq(low=-8, low_hz=150)
    p.master(0.62)
    p.doc("Submerged, muffled pad with a slow comb shimmer", "C3–C5", "Deep ambient, dub techno, underwater cues",
          "Long chords; dub-style chord stabs with SPACE up", "TEXTURE",
          "Almost no top end: it can be loud without masking anything above 1 kHz")
    out.append(p)

    return out
